#+title: Anki Dokazi
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{esint}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}

* Trditev 2.19

Naj bo \(  K \subset \mathbb{R}^n \) kvader in \(  f: K \to [0, \infty) \) omejena. Tedaj velja

\[ \int\limits_K f \,dx = 0 \ \implies \  f = 0 \text{ s.p. } K
\]
** Dokaz
*** 1.
Case: \(  K_n = \left\{ x \in K; \ f(x) \le \frac{1}{n} \right\}, \ n \in \mathbb{N} \)
*** 2.
\(  0 \le \chi_{K_n} \le nf \) velja povsod na \(  K \)
**** <2>.1
\(  f \ge 0 \)
Dokaz: zaradi definicije funkcije \(  f(x) \) v 1.
**** <2>.2 QED
*** 3.
\[ 0 \le S(\chi_{K_n}) \le n \cdot S(f) = 0
\]
**** <3>.1
Case: \(  S(\chi_{K_n}) = \inf_D S(\chi_{K_n}, D)  \).
**** <3>.2
\(  0 \le S(\chi_{K_n}, D) \le S(nf, D) = n S(f, D) \) za vsako delitev \(  D \) kvadra \(  K \)
Dokaz: 2. ter definicije zgornje Darbouxove vsote:

\begin{align*}
  S(f, D) &= \sum\limits_{i = 1}^n \sum\limits_{j = 1}^m M_{ij} \left| P_{ij} \right| && M_{ij} = \sup f(x, y) \\
S(nf, D) &= \sum\limits_{i=1}^n \sum\limits_{j=1}^m n M_{ij} \left| P_{ij} \right|\\
= n S(f, D)
\end{align*}
**** <3>.3
\( n \cdot S(f) = 0  \), ker je \(  \int\limits_K^{} f\,\mathrm{d x} = 0 \)
Dokaz: predpostavka v trditvi
**** <3>.4 QED
*** 4.
\(  S(\chi_{K_n}) = 0 \)

Dokaz: 3.
*** 5.
\[ \int\limits_K^{} \chi_{K_n}\,\mathrm{d x} = \int\limits_{K_n}^{}1\,\mathrm{d x} = 0
\]

Dokaz: definicija karakteristične funkcije \(  \chi_{K_n} \) ter 4.

/zdi se mi, da je implicitno privzeto, da je funkcija integrabilna in po definiciji je integrabilna, ko sta \(  s(f) = S(f) \) enaki.
*** 6.
\[ V(K_n) \exists \ \land \ V(K_n = 0)
\]

Dokaz: 5.
*** 7.
\[ m(K_n) = 0 \ \forall n \in \mathbb{N}
\]

Dokaz: Trditev 2.17, če je \(  A \subset \mathbb{R}^n \) kompaktna množica, potem je \(  V(A) = 0 \ \iff \ m(A) = 0 \).
*** 8.
\[ m(\left\{ f \ne 0 \right\}) = m(\bigcup_{n \in \mathbb{N}} K_n) = 0
\]

Dokaz: 7.
* Izrek 2.20 (Fubini-Tonelli)

Naj bo \(  f:[a,b] \times [c, d] \to \mathbb{R} \) integrabilna. Privzamemo, da je \(  \forall x \in [a, b] \) funkcija \(  f(x, \cdot): [c, d] \to \mathbb{R}, \ y \mapsto f(x, y) \) definirana kot integrabilna na \(  [c, d] \). Tedaj je

\[ \iint\limits_{[a, b] \times [c, d]}^{} f(x, y) \,\mathrm{dx dy} = \int\limits_a^b \int\limits_c^d f(x, y) \,\mathrm{d y}\,\mathrm{d x}
\]

Če je \(  f \) zvezna, potem je

\[ \iint\limits_{[a, b]\times [c, d]}^{} f(x, y) \,\mathrm{d xdy} = \int\limits_{a }^b \left( \int\limits_c^d f(x, y) \,\mathrm{d y} \right)\,\mathrm{d x} = \int\limits_c^d \left( \int\limits_a^b f(x, y)\,\mathrm{d x} \right)\,\mathrm{d y}
\]

** Dokaz
*** <1>1
\(  g: [a, b] \to \mathbb{R} \),

\[ g (x) = \int\limits_c^d f(x, y) \,\mathrm{d y}
\]

Dokaz: Funkcija \(  g \) obstaja, ker je \(  f \) integrabilna.
*** <1>2
Assume: \(  I = [a, b], \ J = [c, d] \)
Prove:
\[ \iint\limits_{I \times J}^{} f(x, y)  \,\mathrm{d x dy} = \int\limits_I^{} g(x) \,\mathrm{d x}
\]
Dokaz:
**** <2>1
Assume: delitvi \(  D_1 = \left\{ I_i = [x_{i-1}, x_i]; \ i = 1, \ldots, m \right\} \) za \(  I \) in \( D_2 = \{J_j = [y_{j - 1}, y_j]; \ j = 1, \ldots n \} \) za \(  J \).
Prove: \(  D_1 \times D_2 \) je delitev za \(  I \times J \)
***** <3>1
\(  D_1 \) je projekcija na \(  I \)
***** <3>2
\(  D_2 \) je projekcija \(  J \)
***** <3>3 QED
By: <3>1 in <3>2
**** <2>2
Assume: \(  P_{ij} = I_i \times J_j \) in

\(  m_{ij} (f) = \inf_{P_{ij}} f \) in \(  M_{ij} (f) = \sup_{P_{ij}} f \)

Prove:
\[ s(f, D) \le \sum\limits_{i = 1}^m \inf_{x \in I_i} g(x) \left| I_i \right| = s(g, D_1)
\]

Dokaz:
***** <3>1
\[ s(f, D) = \sum\limits_{i = 1, j=1}^{m, n} m_{ij} (f) \left| P_{ij} \right| = \sum\limits_{i=1}^m \left( \sum\limits_{j = 1}^n m_{ij}(f) \left| J_j \right| \right) \left| I_i \right|
\]
Dokaz: definicija spodnje Darbouxove vsote ter \(  \left| P_{ij} \right| = \left| J_j \right| \left| I_i \right|\)
***** <3>2
\[ \sum\limits_{j =1}^{n} m_{ij} (f) \left| J_j \right| \le \sum\limits_{j = 1}^m m_j (f(x, \cdot)) \left| J_j \right| = s(f(x, \cdot), D_2) \le \int\limits_J^{} f(x, y) \,\mathrm{d y} = g(x)
\]

Dokaz: Integrabilno po Darbouxu ter definicije \(  m_{ij} \) in \(  m_j \).
***** <3>3
\[ \sum\limits_{j=1}^n m_{ij} (f) \left| J_j \right| \le \inf_{x \in I_i} g(x)
\]

Dokaz: <3>2 in \(  \inf_{x \in I_i} g(x) \le g(x) \)
***** <3>2 QED
Dokaz: <3>1, in <3>3 ter definicija spodnje Darbouxove vsote
**** <2>3
Simetrično s supremumi
**** <2>4
 \( s(f, D) \le s(g, D_1) \le S(g, D_1) \le S(f, D)  \)
 Dokaz: <2>2 in <2>3
**** <2>5
Assume: \(\forall \epsilon > 0 \)
Prove:
\[ S(g, D_1) - s(g, D_1) < \epsilon
\]
Dokaz:
***** <3>1
\[ S(f, D) - s(f, D) < \epsilon
\]
Dokaz: \(  f \) je integrabilna in obstaja taka delitev \(  D \)
***** <3>2 QED
Dokaz: <3>1 in <2>4
**** <2>6 QED
*** <1>3 QED
Dokaz: <1>2
* Trdite 2.43
Predpostavke:
- \( I = [a,b] \)
- \( \alpha, \beta: I \to \mathbb{R} \) zvezne in \( \alpha \le \beta \)
- \( A: \left\{ \left( x, y) \right) \in \mathbb{R} ^2, \ x \in I, y \in \left[ \alpha(x), \beta(x) \right] \right\} \)
- \( f: A \to \mathbb{R} \)

\[ \iint\limits_A^{} f(x, y)  \,\mathrm{d x dy} = \int\limits_a^b \int\limits_{\alpha(x)}^{\beta(x)} f(x, y) \mathrm{dy dx}
\]
** Dokaz
*** <1> 1
Obstaja pravokotnik \( P \subset \mathbb{R} ^2 \) tako, da \( A \subset P \)

Dokaz: \( \alpha(x), \beta (x) \) sta zvezni in na intervalu \( [a, b] \) omejeni.
*** <1>2
Case: \( \tilde{f}: A \to \mathbb{R} \):
\[ \tilde{f} (x, y) = \begin{cases}
f(x, y), \ (x, y) \in A \\
0; \text{ else}
\end{cases} = f \cdot \chi_{A}
\]
Prove: \( \tilde{f} \)  je integrabilna na \( P \)
Dokaz:
**** <2>1
Točke nezveznosti funkcije \( \tilde{f} \) so vsebovane v \( \Gamma_{\alpha} \cup \Gamma_{\beta} \).
**** <2>2
\( V(\Gamma_{\alpha} \cup \Gamma_{\beta}) = 0 \)
Dokaz:
Prostornina unije grafov s prostornino 0 je 0.
**** <2>3
\( \tilde{f}\) je zvezna skoraj povsod
Dokaz: <2>2 ter definicija s.p.
**** <2>4 QED
Dokaz: <2>3 in Lebesgue
*** <1>3
Prove: \( \tilde{f}(x, \cdot) \) je integrabilna \( \forall x \in I \)
Dokaz: \( \tilde{f} \) je odsekoma zvezna na \( [c, d] \)
*** <1>4
\begin{align*}
  \iint\limits_A^{} f(x, y) \,\mathrm{dx dy} &= \iint\limits_P^{} \tilde{f}(x, y) \,\mathrm{d x dy} \\
&= \int\limits_a^{ b } \left( \int\limits_c^d \tilde{f}(x, y) \mathrm{dy}) \right\mathbb{dx} \\
&= \int\limits_a^b \int\limits_{\alpha}^{\beta} f(x, y) \mathrm{dx dy}
\end{align*}
* Izrek 2.45
Predpostavke:
- \( A \subset \mathbb{R}^n, \ B \subset \mathbb{R} ^n  \) kvadra
- \( f: A \times B \to \mathbb{R} \) integrabilna
- \( f(x, \cdot) \) integrabilna na \( B \forall x \in A \)

\[ \iint\limits_{A \times B}^{}f \,\mathrm{d x dy} = \int\limits_A^{} \left( \int\limits_B^{}f(x, y) \, \mathrm{dx} \right) \, \mathrm{dy}
\]
* Posledica 2.46
\( F: K = [a, b] \times [c, d] \times [e, f] \to \mathbb{R} \) zvezna

\[ \iiint\limits_K^{} F(x, y, z) \,\mathrm{d V} = \iint\limits_{[a,b] \times [c, d]}^{} \left( \int\limits_e^f F(x, y, z)\, \mathrm{dz} \right) \,\mathrm{d dxdy} = \int\limits_a^b \left( \int\limits_c^d \left[ \int\limits_e^f F(x, y, z) \, \mathrm{dz} \right] \mathrm{dy} \right) \mathrm{dx}
\]
* Trditev 2.47
Predpostavke:
- \( A \subset \mathbb{R} ^2  \) ima ploščino
- \( \alpha, \beta: A \to \mathbb{R} \) zvezna in \( \alpha < \beta \)
- \( B = \left\{ (x, y, z) \in A \times \mathbb{R}, \, \alpha(x, y) \le y \le B(x, y) \right\} \)
- \( f: B \to \mathbb{R} \) je zvezna

\[ \iiint\limits_B^{} f(x,y, z)  \,\mathrm{d V} = \iint\limits_A^{} \left( \int\limits_{\alpha(x)}^{\beta(x)} f(x, y, z) \, \mathrm{dz} \right) \,\mathrm{d y dx}
\]
* Definicija 2.50
Predpostavke:
- \( U^{\text{odp}} \subset \mathbb{R}^n \)
- \( \phi_1, \ldots, \phi_m: U \to \mathbb{R} \) parcialno odvedljiva na vse spremenljivke

/Jacobijevo matriko/ za \( \phi = \left( \phi_1, \ldots, \phi_m \right) \) definiramo kot

\[ J\phi = \begin{bmatrix}
\frac{\partial \phi_1}{\partial x_1} & \mathbb{ldots} & \frac{\partial \phi_1}{\partial x_m}  \\
\vdots & \ddots & \ldots \\
\frac{\partial \phi_m}{\partial x_1} & \ldots & \frac{\partial \phi_m}{\partial x_m}
\end{bmatrix}
\]
* Izrek 2.51
Predpostavek:
- \( A \subset \mathbb{R} ^n \) omejena množica s prostornino
- \( \phi: A \to \mathbb{R} ^n \) injektivna in razreda \( C^1 \)
- \( \det J\phi(x) \ne 0 \forall x \in A \)
- \( x \mapsto \det(J(\phi(x))) \) omejena in različna od 0
- \( \phi(A) \) je odprta v \( R ^n \) s prostornino
- \( f: \phi(A) \to \mathbb{R} \) je integrabilna

  Tedaj je tudi \( x \mapsto f(\phi(x)) \left| \det J\phi(x) \right| \) integrabilna na \( A \) in velja

  \[ \int\limits_{\phi(A)}^{} f(x) \, \mathrm{dx} = \int\limits_A^{} f(\phi(t)) \left| \det J \phi(t) \right| \, \mathrm{dt}
  \]
* Skica dokaza:
*** <1>1
Case:
- \( A \) je pravokotnik,
- \( n = 2 \),
- \( f \) je zvezna,
- \( \left\{ P_j \right\} \) neka delitev za \( A \)
Prove:

\[ \iint\limits_{\phi(A)}^{} f(x, y)  \,\mathrm{d x dy} = \sum\limits_{ j}^{} \iint\limits_{\phi(P_j)}^{} f(x, y) \,\mathrm{d x dy}
\]

Dokaz: Injektivnost
*** <1>2
Prove:

\[ \sum\limits_j^{} \iint\limits_{\phi(P_j)}^{} f(x, y) \,\mathrm{d x dy} = \sum\limits_j^{} \left\langle f \right\rangle_{\phi(P_j)} \left| \phi(P_j) \right|
\]

Dokaz: Izrek o srednji vrednosti med \( f \) in \( Q \)

\[ \left\langle f \right\rangle_Q = \frac{1}{\left| Q \right|} \int\limits_Q^{} f \, \mathrm{dx}
\]
*** <1>3
\( \left\langle f \right\rangle_{\phi(P_j)} = f(\phi(u_j, v_j)) \)
*** <1>4
Prove:
\[ \left| \phi(P_j) \right| \approx = \left| \det J\phi  \right|
\]
Dokaz:
**** <2>1
[[file:jacobi_dokaz.svg]]
**** <2>2 QED

\begin{align*}
  \left| \phi(P_j) \right| &= \left| \left( \phi(u + \Delta u, v) - \phi(u, v) \right) \times \left( \phi(u, v + \Delta v) - \phi(u, v) \right) \right| \\
&= \frac{\partial \phi}{\partial u} \Delta u \times \frac{\partial \phi}{\partial v} \Delta v \\
&= \left| \phi_u \times \phi_v \right| \Delta u \Delta v \\
&= \begin{bmatrix}
\left( \phi_1 \right)_u & \left( \phi_1 \right)_v \\
\left( \phi_2 \right)_u & \left( \phi_2 \right)_v
 \end{bmatrix} = \left| \det J \phi \right|
\end{align*}
*** <1>5
Prove:
\[ \iint\limits_{\phi(A)}^{} f(x, y) \,\mathrm{d xdy} = \sum\limits_j^{} f(\phi(x, y)) \left| \det J\phi \right| \Delta u \Delta v
\]

Dokaz: <1>2, ter <1>4
*** <1>6 QED
Dokaz: <1>5 je Riemannova vsota za funkcijo \( f \circ \phi \left| \det J \phi \right|  \), kjer je \( \Delta u \Delta v \) velikost delilnega pravokotnika za \( A \). Posledično v limiti dobimo

\[ \int\limits_A^{} f \circ \phi \left| \det J \phi \right| \, \mathrm{dS} = \int\limits_A^{} f(\phi(\xi, \eta)) \left| \det J\phi(\xi, \eta) \right| \mathbb{d} \xi \mathrm{d}\eta
\]

* Definicija 2.16

Naj ima telo \(  T \subset \mathbb{R}^3 \) gostoto \(  \rho = \rho(x, y, z) \). Če je \(  \rho = \text{ konst. } \) je telo homogeno.

Masa telesa \(  T \) je definirana kot

\[ m(T) = \iiint\limits_T \rho(x, y, z) \, \mathrm{dV}
\]
* Definicija 2.17
Težišče telesa \(  T \) je točka \(  (x_t, y_t, z_t) \subset \mathbb{R} ^3 \) za katero velja

\begin{align*}
  x_t &= \frac{1}{m(T)} \iiint\limits_T x \rho(x, y, z) \, \mathrm{dV} \\
  y_t &= \frac{1}{m(T)} \iiint\limits_T y \rho(x, y, z) \, \mathrm{dV}\\
  z_t &= \frac{1}{m(T)} \iiint\limits_T z \rho(x, y, z) \, \mathrm{dV}
\end{align*}

Kompaktneje se to zapiše kot

\[ \mathbf{x}_t = \frac{1}{m(T)} \int\limits_T (x, y, z) \rho \,\mathrm{dx} = \frac{1}{m(T)} \int\limits_T \vec{\xi} \rho\,\mathrm{dV}
\]

kjer je \(  \vec{\xi} = (x, y, z) \) vektorska funkcija. Težišče nam pove povprečje položajev glede na utež \(  \rho \)
* Definicja 2.18

Vztrajnostni moment telesa \(  T \subset \mathbb{R} ^3 \) pri vrtenju okoli osi \(  \gamma \subset \mathbb{R}^3 \) je enako

\[ J_{\gamma} = \int\limits_T d(\vec{x}, \gamma) ^2 \rho(\vec{x}) \,\mathrm{d\vec{x}}
\]

kjer je \(  d(\vec{x}, \gamma) \) oddaljenost točke \(  \vec{x} = (x, y, z) \) od osi \(  \gamma \).

V posebnem primeru je to:

\[ J_z = \iiint\limits_T (x ^2 + y ^2) \rho(x, y, z) \, \mathrm{dx}\, \mathrm{dy} \mathrm{dz}
\]
* Posplošeni RD integral v \(  \mathbb{R} ^n \)
1) \(  f: D \to [0, \infty] \) omejena.

   \[ \int\limits_D f\,\mathrm{dV} := \lim_{a \to \infty} \int\limits_{D \cap [-a, a] ^n} f\,\mathrm{dV}
   \]

   Če vsi izrazi na desni obstajajo.

2) \(  f: D \to [0, \infty) \) neomejena. Tedaj definiramo

   \[ \int\limits_D f\,\mathrm{dV} := \lim_{M \to \infty} \int\limits_D \min \{f(x), M\}\,\mathrm{dx}
   \]

   če vsi izrazi na desni obstajajo.

3) \(  f:D \to \mathbb{R} \) (ni več pozitiven neskončen interval!)

   Poljubno funkcijo poskusimo izraziti s pomočjo pozitivnih funkcij (saj imam zanje že imamo definicijo).

   Definiramo

   \[ f_+ := \max \{f, 0\}
   \]
    Torej, če je funkcija pozitivna vzamemo njeno pozitivno vrednost, drugače je 0. Obratno velja za

    \[ f_- = \min\{-f, 0\}
    \]

   [[file:figures/izlimitirani_integral.svg]]

    In velja

    \[ f = f_+ - f_-, \quad f_{\pm} \ge 0
    \]

    Iz česar sledi

    \[ \int\limits_D f\,\mathrm{dx} := \int\limits_D f_+\,\mathrm{dV} - \int\limits_D f_-\,\mathrm{dV}
    \]

    Če oba integrala na desni obstaja in sta končna (nočemo razlike dveh neskončnosti).

    Poglejmo absolutno vrednost \(  \left| f \right|  = f_+ + f_-\), iz česar sledi, da je za definicijo \(  \int\limits_D f\,\mathrm{dV} \) pomembno, da obstaja \(  \int\limits_D \left| f \right| \,\mathrm{dV} \).
* Definicija 3.3
Pot je gladka, če je \(  \vec{r} \in C^1 (I) \) za \(  I \subset \mathbb{R} \).
* Definicija 3.4
Gladka krivulja v \(  \mathbb{R} ^3 \) je gladka pot \(  \vec{r} = \left( x, y, z \right): I \to \mathbb{R} ^3 \), za katero velja \(  \odv{r} (t) \ne 0 \) za vsak \(  t \in I \). Taka krivulja je tudi injektivna (in nima samopresečišč).
* Definicija 3.6
Če je \(  \vec{r}: [a, b] \to [0, \infty) \) gladka krivulja, katere tir označimo z \(  \Gamma \), je dolžina \(  \Gamma \) definirana kot

\[ l(\Gamma) = \int\limits_a^b \left| \odv{r}(t) \right|\,\mathrm{d t}
\]
* Trditev 3.7
Prove: Definicija 3.6 je dobra (torej neodvisna od izbrane parametrizacije)
** Dokaz
*** <1>1
Case 1: \(  \vec{r}: I = [a, b] \to \Gamma \)
Case 2: \(  \vec{\rho}: J = [\alpha, \beta] \to \Gamma \) (druga regularna parametrizacija)
Case 3: \(  h \in C^1:J \to I \)

Prove:

\[ \vec{\rho} = \vec{r} \circ h
\]

Dokaz: Case 3, 2, in 1
*** <1>2
\[ \int\limits_{\alpha}^{\beta} \left| \odv{\rho} (u) \right|\,\mathrm{d u} = \int\limits_{\alpha}^{\beta} \left| \odv{r}(h(u)) \right| \left| h'(u) \right|\,\mathrm{d u} = \int\limits_a^b \left| \odv{r} (t) \right|\,\mathrm{d t}
\]
Dokaz: <1>1 in verižno pravilo
*** <1>3 QED
Dokaz: <1>2
* Definicija 3.10
Enotski tangnenti vektor

\[ \frac{\odv{r}(t) }{\left| \odv{r} (t) \right|}
\]

Tangenta v točki \(  \odv{r}(t_0) \) premica skozi \(  \vec{r}(t_0) \) v smeri tangentnega vektorja na \(  \Gamma \) v točki \(  \vec{r}(t_0) \).

Enačba premice je

\[ (x, y, z) = \vec{r}(t_0) + \lambda \odv{r}(t_0)
\]

Normalna ravnina na \(  \vec{r}(t_0) \) je ravnina skozi \(  \vec{r}(t) \) pravokotna na tangentni vektor.
* Izrek 3.15
Predpostavke:

- \(  \gamma \) je regularna parametrizacija \(  C^2 \) neke krivulje \(  \mathbb{R} ^3 \)
- Za dani \(  t_0 \in \mathbb{R} \) privzamemo, da je

\[ \vec{v}_0 = \left( \odv{\gamma} \times \oddv{\gamma} \right) (t_0) \ne 0
\]

Tedaj obstaja \(  \delta > 0 \) tako, da sta za poljubni točki \(  t_1, t_2 \in \left( t_0 - \delta, t_0 + \delta \right) \), kjer so \(  t_1, t_2 \) in \(  t_0 \) različne, točke \(  \tilde{\gamma}(t_1), \vec{\gamma}(t_2), \vec{\gamma(t_0)} \) nekolinearne.

** Dokaz (s protislovjem)
*** <1>1
Assume: točke \(  \gamma(t_1), \gamma(t_2), \gamma(t_0) \) so kolinearne
Case 1: \(  l = l(t_1, t_2) \) je premica z izhodiščem \(  \left( \cdot, \gamma(t_0) \right) \), ki jih povezuje
Case 2: \( w \in l^{\perp}  \)
Case 3: \(  t_0 < t_1 < t_2 \)

Prove:

\[ \left\langle \gamma(t_1) - \gamma(t_0), w \right\rangle = \left\langle \gamma(t_2) - \gamma(t_0), w \right\rangle = 0
\]

Dokaz: Definicija skalarnega produkta ter Case 2, in Assume
*** <1>2 Rolleov izrek
Prove: Obstaja točki \(  \xi_1, \xi_2 \in \mathbb{R} \) tako, da velja

\[ t_0 < \xi_1 < t_1 < \xi_2 < t_2\ \ni: \ \left\langle \odv{\gamma}(\xi_1), w \right\rangle = \left\langle \odv{\gamma}(\xi_2), w \right\rangle = 0
\]

Dokaz: Rolleov izrek, matematika 1, ter odvod \( \frac{\mathrm{d} }{\mathrm{d} t} \left\langle \vec{\gamma}(t) - \vec{\gamma}(t_0), w \right\rangle \) (odvod konstante)

**** Rolleov izrek

/Spomni se/: Rolleov izrek (Matematika 1, Mrčun, str. 163)

Predpostavke:
- \( a, b \in \mathbb{R}, \ a < b \)
- \( f: [a, b] \to \mathbb{R} \) zvezna funkcija
- \( f \) odvedljiva na \( (a, b) \)

Če velja \( f(a) = f(b)  \), potem obstaja takšna točka \( c \in (a, b) \)

\[ f'(c) = 0
\]

V našem primeru je \( f(t) = \left\langle \gamma (t) - \gamma(t_0), w \right\rangle \)
***** Dokaz
****** <2>1

\( f \) omejena.

Dokaz: \( f \) je definirana na zaprti omejeni podmnožici in zvezna.
****** <2>2
Case: \( u, v \in [a, b], \ f(u) = \sup (f), \ f(v) = \inf(f) \)

Prove: \( c = u \)

Dokaz: \( u \in (a, b) \) je ekstrem funkcije \( f \), po Case <2>2
****** <2>3
\( c = v \)
Dokaz: \( v \in (a, b) \) je ekstrem funkcije f , po Case <2>2
****** <2>4
\( \forall c \in (a, b)  \)

Dokaz: \( f = \text{konst} \) za \( \left\{ u, v \right\} \subset \left\{ a, b \right\} \)
****** <2>5 QED
Dokaz: <2>2, <2>3, <2>4

*** <1>3
Prove: Obstaja \(  \xi_3 \in \left( \xi_1, \xi_2 \right) \) tako, da velja

\[ \left\langle \oddv{\gamma}(\xi_3), w \right\rangle = 0
\]

Dokaz: Rolleov izrek ter odvod iste funkcije
*** <1>4
Case 4: \( \epsilon > 0  \)

Prove:

\[ v_0 \times w = \left\langle \dot{\gamma}(t_0) - \dot{\gamma}(\xi_1), w \right\rangle \cdot \ddot{\gamma} (t_0) - \left\langle \ddot{\gamma} (t_0) - \ddot{\gamma}(\xi_3), w \right\rangle \cdot \dot{\gamma} (t_0)
\]

Dokaz: Linearna algebra \( (a \times b) \times c = (a \cdot c) \cdot b - (b \cdot c) \cdot a \) ter odšteli smo \( \dot{\gamma}(t_0) \) <1>2 in od \( \ddot{\gamma}(t_0) \) <1>3, saj je produkt <1>2 in <1>3 z \( w \) enak 0 - in se tako ne spremeni.
*** <1>5
\[ \left| v_0 \times w \right| \le \left( \left| \dot{\gamma}(t_0) - \dot{\gamma}(\xi_1) \right| \cdot \left| \ddot{\gamma}(t_0) \right| - \left| \ddot{\gamma}(t_0) - \ddot{\gamma}(\xi_3) \right| \cdot \left| \dot{\gamma}(t_0) \right|\right) \left| w \right|
\]

Dokaz: Cauchy-Schwartzova neenakost \( \left| \left\langle \vec{a}, \vec{b} \right\rangle \right| \le \left| \vec{a} \right|  \cdot \left| \vec{b} \right|\)
*** <1>6
Case 5: \( \alpha = \left| \dot{\gamma}(t_0) - \dot{\gamma}(\xi_1) \right| \)
Case 6: \( \beta = \left| \ddot{\gamma}(t_0) - \ddot{\gamma}(\xi_3) \right| \)

Prove: \( \alpha, \beta < \epsilon \)

Dokaz
**** <2>1
Obstaja \( \delta > 0 \), da za poljubna \( \xi_1, \xi_3 \in (t_0 - \delta, t_0 + \delta)  \)
Dokaz: \( \dot{\gamma}, \ddot{\gamma} \) sta zvezni v točki \( t_0 \).
**** <2>2 QED
Pogoj velja tudi za \( \xi_1, \xi_3 \) za \( t_1, t_2 \in (t_0, t_0 + \delta) \)
*** <1>7
Prove:

\[ \frac{\left| v_0 \times w \right|}{ \left| w \right|} \le \left( \left| \dot{\gamma}(t_0) \right| + \left| \ddot{\gamma}(t_0) \right| \right) \epsilon \quad \forall t_1, t_2 \in (t_0, t_0 + \delta), \ \forall w \in l(t_1, t_2) ^{\perp} \setminus \left\{ 0 \right\}
\]

Dokaz: \( \alpha = \epsilon, \ \beta = \epsilon \) <1>6, ter <1>5
*** <1>8

Prove: \( \frac{\left| v_0 \times w \right|}{\left| w \right|} = \left| v_0 \right| \sin \phi\)

Dokaz: definicija vektorskega produkta
*** <1>9
Prove:

\[ \sin \phi \le \frac{\left| \dot{\gamma}(t_0) \right| + \left| \ddot{\gamma}(t_0) \right|}{\left| \left( \dot{\gamma} \times \ddot{\gamma} \right) (t_0) \right|} \epsilon
\]

Dokaz: <1>8 in definicija \( \left| v_0 \right| = \left| \left( \dot{\gamma} \times \ddot{\gamma} \right) (t_0) \right| \)
*** <1>10 QED
Iz <1>9 vidimo, da je kot \( \phi \) med \( v_0 \) in \( w \in l(t_1, t_2)^{\perp} \) nujno majhen, za \( t_1 \) in \( t_2 \) blizu \( t_0 \). Tukaj naletimo na protislovje, ker \( l^{\perp} \) ni ravnina kot predpostavljeno na začetku, ampak ozek stožec okoli \( v_0 \).
* Izrek 3.15.1
Predpostavke:

- \(  \gamma \) je regularna parametrizacija \(  C ^2 \) neke krivulje \(  \mathbb{R} ^3 \)
- za poljuben \(  t_0 \in \mathbb{R} \) velja

  \[ v_0 = \left( \dot{\gamma} \times \ddot{\gamma} \right)(t_0) \ne 0
  \]
- \(  t_1, t_2 \in \left( t_0 - \delta, t_0 + \delta \right) \), in \(  t_1 \ne t_2 \ne t_0 \) so različne.

S \(  \Pi (t_1, t_2) \) označimo ravnino skozi \(  \gamma(t_1), \gamma(t_2), \gamma(t_0) \). Ravnina \(  \Pi(t_1, t_2) \) limitira proti ravnini z normalo \(  v_0 \), ko gresta \(  t_1, t_2 \to t_0 \).
** Dokaz
*** <1>1
Ravnina \(  \Pi (t_1, t_2) \) obstaja in je enolično določena.

Dokaz: Izrek 3.15
*** <1>2
Dovolj je dokazati:

Enotske normale \(  \vec{n}(t_1, t_2) \) na \(  \Pi(t_1, t_2) \) limitirajo k \(  \pm \frac{v_0}{\left| v_0 \right|} \), ko \(  t_1, t_2 \to t_0 \).
**** <2>1
Case 1: do predznaka natančno

\[ \vec{n} (t_1, t_2) = \frac{\left[ \gamma(t_1) - \gamma(t_2) \right] \times \left[ \gamma(t_2) - \gamma(t_1) \right]}{\left| \left[ \gamma(t_1) - \gamma(t_2) \right] \times \left[ \gamma(t_2) - \gamma(t_1) \right] \right|}
\]

Prove: \(  \vec{n}(t_1, t_2) \) je zvezna funkcija argumentov \(  t_1, t_2 \in \mathbb{R} ^2 \) na \(  \left( t_0 - \delta, t_0 + \delta \right) \times \left( t_0 - \delta, t_0 + \delta \right) \).

Dokaz: \(  \gamma \) je zvezna funkcija argumentov \(  t_2, t_1 \) iz predpostavke 1.
**** <2>2
Case 2: \(  \epsilon > 0 \)
Case 3: definiramo \(  f(t) = \left\langle \gamma(t) - \gamma(t_0), \vec{n} (t_1, t_2) \right\rangle \).

Obstajata \(  t_0 < \xi_1 < t_1 \xi_2 < t_2 \) tako, da velja

\begin{align*}
  0 &= f'(\xi_1) = \left\langle \dot{\gamma}(\xi_1), \vec{n}(t_1, t_2) \right\rangle \\
0 &= f'(\xi_2) = \left\langle \dot{\gamma} (\xi_2), \vec{n} (t_1, t_2) \right\rangle
\end{align*}

Dokaz: Rolleov izrek
**** <2>3

Obstaja \(  \xi_3 \in \left( \xi_1, \xi_2 \right) \) tako, da velja

\[ f''(\xi_3) = \left\langle \ddot{\gamma}(\xi_3), \vec{n}(t_1, t_2) \right\rangle = 0
\]

Dokaz: Rolleov izrek
**** <2>4

Velja

\[ \left| v_0 \times \vec{n}(t_1, t_2) \right| \le \left( \left| \dot{\gamma}(t_0 - \dot{\gamma}(\xi_1)) \right| \left| \ddot{\gamma})(t_0) \right| + \left| \ddot{\gamma} (t_0) - \ddot{\gamma}(\xi_3) \right| \left| \dot{\gamma}(t_0) \right|\right) \left| \vec{n}(t_1, t_2) \right|
\]

in \(  \left| \vec{n}(t_1, t_2) \right| = 1 \)

Dokaz:
***** <3>1

\begin{align*}
  v_0 &= \left[ \dot{\gamma}(t_0) \times \ddot{\gamma}(t_0) \right] \times \vec{n} (t_1, t_2) \\
&= \left\langle \dot{\gamma}(t_0), \vec{n}(t_1, t_2) \right\rangle \cdot \ddot{\gamma} (t_0) - \left\langle \ddot{\gamma}(t_0), \vec{n}(t_1, t_2) \right\rangle \cdot \dot{\gamma}(t_0) \\
&= \left\langle \dot{\gamma}(t_0) - \dot{\gamma}(\xi_1), \vec{n} (t_1, t_2) \right\rangle \cdot \ddot{\gamma}(t_0) - \left\langle  \ddot{\gamma}(t_0) - \ddot{\gamma}(\xi_3), \vec{n}(t_1, t_2) \right\rangle \cdot \dot{\gamma} (t_0)
\end{align*}

Dokaz:

\(  (a \times b) \times c = (a \cdot c) \cdot b - (b \cdot c) \cdot a \) ter v zadnji vrstici <2>2, ter <2>3
***** <3>2 QED
<3>1 in trikotniška neenakost
**** <2>5
Case 4: \(  \delta > 0 \)

Za \(  \xi_1, \xi_3 \in (t_0 - \delta, t_0 + \delta) \) velja

\begin{align*}
  \left| \dot{\gamma}(t_0) - \dot{\gamma}(\xi_1) \right| &< \epsilon  \\
\left| \ddot{\gamma}(t_0) - \ddot{\gamma}(\xi_3) \right| &< \epsilon
\end{align*}

Dokaz: definicija zveznosti funkcije
**** <2>6

\[ \sin \phi (t_1, t_2) \le \frac{\left| \dot{\gamma}(t_0) \right| + \left| \ddot{\gamma}(t_0) \right|}{\left| \dot{\gamma} \times \ddot{\gamma} \right|(t_0)} \epsilon
\]

Kot \(  \phi(t_1, t_2) \) je oster, saj je \(  \epsilon > 0 \), ampak majhen.

Dokaz:
***** <3>1
\[ \left| v_0 \times \vec{n}(t_1, t_2) \right| = \left| v_0 \right| \sin \phi
\]

Dokaz: definicija vektorskega produkta in \(  \left| \vec{n}(t_1, t_2) \right| = 1 \)
***** <3>2

\[ \left| v_0 \right| \sin \phi \le \frac{\left| \dot{\gamma}(t_0) \right| + \left| \ddot{\gamma}(t_0) \right|}{\left| \dot{\gamma} \times \ddot{\gamma} \right| (t_0)}
\]

Dokaz: <3>1 in <2>4
***** <3>3 QED
Dokaz: <3>2

**** <2>7
Case 5: \(  \tilde{v}_0 = \frac{v_0}{\left| v_0 \right|} \)

\[ \left| \tilde{v}_0 - \vec{n} \right| ^2 = 2(1 - \cos \phi)
\]

Dokaz: analiza 1

\[ \left| \tilde{v}_0 - \vec{n} \right| = \left| \tilde{v}_0 \right| + \left| \vec{n} \right| - 2 \left\langle \tilde{v}_0, \vec{n} \right\rangle = 2 - 2\cos \phi
\]

in \(  \left| \tilde{v}_0 \right| = \left| \vec{n} \right| = 1 \).
**** <2>8 QED
Dokaz: <2>7: razlika \(  1 - \cos \phi \) gre proti 0, ko \(  t_1, t_2 \to t_0 \), ker oster kot \(  \phi \to 0 \).
*** <1>3 QED
Dokaz: <1>2
* Definicija 3.16
Ravnini skozi \(  T_0 = \gamma(t_0) \) in z normalo \(  \left( \dot{\gamma} \times \ddot{\gamma} \right) (t_0) \ne 0  \) pravimo pritisnjena ravnina na krivuljo \(  \gamma \) v točki \(  T_0 \).
* Izrek 3.17

Če je \(  \Pi = \Pi(t_0) \) pritisnjena ravnina na \(  \gamma \) v točki \(  \gamma(t_0)\) velja

\[ d(\gamma(t_0 + h), \Pi) = o \left( h ^2 \right), \ h \to 0
\]

kjer je \(  f(h) = o(g(h)), h \to a \).
** Dokaz
*** <1>1
Case 1: \(  \gamma(t) = \left( \gamma_1(\tilde{t}), \gamma_2 (\tilde{t}), \gamma_3 (\tilde{t}) \right) \) za \(  \tilde{t} = t_0 + h \).
Case 2: \(  \vec{o}(h ^2) = \left( o(h ^2),  o(h ^2),  o(h ^2)  \right) \)

Velja

\[ d (\gamma(\tilde{t}), \Pi) = \left\langle \gamma(\tilde{t}) - \gamma(t_0), \frac{\dot{\gamma}(t_0) \times \ddot{\gamma}(t_0)}{\left| \dot{\gamma}(t_0)\times \ddot{\gamma}(t_0) \right|}  \right\rangle
\]

Dokaz:
Za razdaljo med vektorjem \(  \vec{R} \), ki kaže iz ravnine in poljubno ravnino \(  \Sigma \) z normalnim vektorjem \(  \vec{n}_{\Sigma} \) velja

\[ d \left( \vec{R}, \Sigma \right) = \left\langle \vec{R} - \vec{r}, \frac{\vec{n}_{\Sigma}}{\left| \vec{n}_{\Sigma} \right|} \right\rangle
\]
*** <1>2
Velja

\[ \left| \left\langle \dot{\gamma}(t_0) \cdot h ^2 + \ddot{\gamma}(t_0) \cdot \frac{h ^2}{2} + \vec{o}(h ^2), \vec{n} \right\rangle \right| = o(h ^2)
\]

Dokaz:
**** <2>1
\[ \gamma_i (\tilde{t}) = \gamma_i (t_0) + \dot{\gamma}_i (t_0) \cdot h + \ddot{\gamma}_i (t_0) \cdot \frac{ h ^2}{2} + o(h ^2), \quad i = 1, 2, 3
\]

Dokaz: Razvoj \(  \gamma_i (\tilde{t}) \) v Taylorjevo vrsto
**** <2>2

\begin{align*}
 \left| \left\langle \dot{\gamma}(t_0) \cdot h ^2 + \ddot{\gamma}(t_0) \cdot \frac{h ^2}{2} + \vec{o}(h ^2), \vec{n} \right\rangle \right| &= \left| \left\langle o(h ^2), \vec{n} \right\rangle \right| \\
& \le \left| o(h ^2) \right| = o(h ^2)
\end{align*}

Dokaz: Združimo <1>1 in <2>1, trikotniška neenakost in pa skalarni produkt pravokotnih vektorjev (\(  \dot{\gamma} \), \(  \ddot{\gamma} \) na \(  \vec{n} = \dot{\gamma} \times \ddot{\gamma} \)) je enak 0
**** <2>3 QED
*** <1>3 QED
* Definicija 4.1
Ploskev v \(  \mathbb{R} ^3 \) je podana s parametrizacijo \(  \vec{r} = \vec{r}(u, v): D \to \mathbb{R} \), pri čemer je \(  \vec{r}(u, v) = \left( X(u, v), Y(u, v), Z(u, v) \right) \) preslikava reda vsaj \(  C^2 \). Zahtevamo še, da je \(  \vec{r}_u \times \vec{r}_v \ne 0 \). V tem primeru pravimo, da je parametrizacija regularna. \(  u, v \) sta krivočrtni koordinati na ploskvi \(  M = \left\{ \vec{r}(u, v), \ (u, v)  \in D \right\} \)
* Definicija 4.2

(Afina) tangentna ravnina na ploskev \(  M \) skozi točko \(  m = \vec{r}(u, v) = (x_0, y_0, z_0) \) definiramo kot množico tangentnih vektorjev krivulj skozi to točko. Eksplicitno je to ravnina

\[ m + \mathrm{Lin} \left{ \vec{r}_u (u, v), \vec{r}_v (u, v) \right}
\]

Enačba tangentne ravnine je torej

\[ \left\langle (x, y, z) - \left( x_0, y_0, z_0 \right),  \left( \vec{r}_u \times \vec{r}_v \right)(u, v) \right\rangle
\]

/Opomba/: za predstavitev ravnine potrebujemo začetno točko \(  m \) ter bazna vektorja, ki razpenjata ravnino
** Dodatno:

Upoštevamo stvari definirane v definiciji 4.1

Zanima nas tangentna ravnina v točki \(  \vec{r}(u_0, v_0) \). Imamo krivuljo \(  \gamma: I \to D \), ki preslika \(  \gamma(t_0) = \left( \alpha(t), \beta(t) \right) = (u_0, v_0) \). Krivuljo preslikamo na ploskev \(  \vec{r} \circ \gamma: I \to M \).

\[  \frac{\mathrm{d} }{\mathrm{d} t} \vec{r}(\gamma(t)) = \vec{r}_u(\gamma(t)) \cdot \dot{\alpha}(t) + \vec{r}_v (\gamma(t)) \cdot \dot{\beta}(t)
\]

Pri \(  t_0 \) je to tangentni vektor na krivuljo \(  (\vec{r} \circ \gamma)(t_0) \)

\[ \vec{r}_u(\gamma(t_0)) \cdot \dot{\alpha}(t_0) + \vec{r}_v(\gamma(t_0)) \cdot \dot{\beta}(t_0) = a \cdot \vec{r}_u(u_0, v_0) + b \cdot \vec{r}_v (u_0, v_0)
\]

Kakor v opombi, sta \(  \vec{r}_u \) in \(  \vec{r}_v \) naša bazna vektorja.
* Implicitno podane ploskve

Funkcija \(  F: \mathbb{R} ^3 \to \mathbb{R} \) je funkcija 3 spremenljivk. Ploskev definiramo kot množico ničel oz. nivojnico

\[ M = \left\{ (x, y, z) \in \mathbb{R} ^3, F(x, y, z) = 0 \right\}
\]

z dodanim pogojem \(  \nabla F = \left( \frac{\partial F}{\partial x}, \frac{\partial F}{\partial y}, \frac{\partial F}{\partial z}  \right) \ne 0 \), kar je enakovredno \(  \vec{r}_u \times \vec{r}_v \ne 0 \) pri eksplicitni funkciji.
** Tangentna ravnina implicitno podane ploskve
Imamo točko \(  m = (x_0, y_0, z_0) \) na ploskvi \(  M \) in poljubno krivuljo, ki gre skozi to točko

\[ \vec{r}(t) = \left( x(t), y(t), z(t) \right)
\]

in leži na ploskvi \(  M \) za vsak \(  t \). Poleg tega imamo tudi funkcijo \(  F = F(x, y, z) \) in ker leži na ploskvi, po definiciji velja

\begin{equation}
\label{eq:1}
 F(x(t), y(t), z(t)) = 0
\end{equation}

Enačbo \ref{eq:1} odvajamo po \(  t \) in dobimo

\begin{align*}
  \frac{\mathrm{d} }{\mathrm{d} t} F(x, y, z) &= 0 \\
F_x \cdot \dot{x} + F_y \cdot \dot{y} + F_z \cdot \dot{z} &= 0 && \text{v točki } m\\
\left\langle \nabla F(m), \vec{r}(t_0) \right\rangle = 0
\end{align*}

Tangentni vektor krivulje \(  \odv{r}(t_0) \) leži v tangentni ravnini na ploskev \(  M \) v točki \(  m \), saj je krivulja v ravnini \(  M \). Vektor \(  \nabla F (m) \) je nanj pravokoten (saj je njun skalarni produkt enak 0), kar pomeni, da predstavlja normalni vektor ravnine. Enačba tangentne ravnine na ploskev \(  M \) v točki \(  m \) je torej

\[ \left\langle (x, y, z) - \vec{r}(t_0), \nabla F (\vec{r}(t_0)) \right\rangle = 0
\]
* Rotacijsko invariantne ploskve (vrtenine)

Način podajanja ploskev tako, da krivuljo v \(  xz \) ravnini zavtrimo okrog \(  z \) osi.

Začetna parametrizacija krivulje je

\[ \gamma(t) = \begin{bmatrix} x(t) \\ 0 \\ z(t) \end{bmatrix}, \ t \in I
\]

ki jo pomnožimo z rotacijsko matriko

\[ \begin{bmatrix}
\cos \phi & - \sin \phi & 0 \\
\sin \phi & \cos \phi & 0 \\
0 & 0 & 1
\end{bmatrix} \begin{bmatrix} x(t) \\ 0 \\ z(t) \end{bmatrix} = \begin{bmatrix} x(t) \cos \phi \\ x(t) \sin \phi \\ z(t)  \end{bmatrix}
\]
** Plašč valja

Daljico vzamemo za krivuljo \(  \gamma \):

\[ \gamma(t) = \begin{bmatrix} a \\ 0 \\ t \end{bmatrix}, \ t \in I
\]

in parametrizacija je torej

\[ \vec{r}(t, \phi) = \begin{bmatrix} a \cos \phi \\ a \sin \phi \\ t \end{bmatrix}, \ t \in I, \phi \in [0, 2\pi)
\]
** Stožec

Premica skozi izhodišče kot krivulja \(  \gamma \):

\[ \gamma(t) = \begin{bmatrix} t \\ 0  \\ at  \end{bmatrix}, t \in [0, b]
\]

Parametrizacija stožca je tako

\[ \vec{r}(t, \phi) = \begin{bmatrix} t \cos \phi \\ t \sin \phi \\ a \end{bmatrix}, t \in [0, b], \phi \in [0, 2\pi)
\]
** Sfera

Kot parametrizacijo vzamemo polkrožnico

\[ \gamma(t) = \begin{bmatrix} \cos t \\ 0 \\ \sin t \end{bmatrix}, t \in \left[ - \frac{\pi}{2},  \frac{\pi}{2} \right]
\]

Parametrizacija enotske sfere

\[ \vec{r}(t, \phi) = \begin{bmatrix} \cos t \cos \phi \\ \cos t \sin \phi \\ \sin t \end{bmatrix}, t \in  \left[ - \frac{\pi}{2},  \frac{\pi}{2} \right], \phi \in [0, 2 \pi)
\]
** Torus

Kot parametrizacijo vzamemo krožnico s polmerom \(  r \) na oddaljenosti \(  a \) od izhodišča:

\[ \gamma(t) = \begin{bmatrix} a + r \cos t \\ 0 \\ r \sin t \end{bmatrix}, t \in [0, 2\pi)
\]

Parametrizacija torusa je

\[ \vec{r}(t, \phi) = \begin{bmatrix} (a + r \cos t)\cos \phi \\ (a + r \cos t)\sin \phi  \\ r \sin t \end{bmatrix}, \ t \in [0, 2\pi), \phi \in [0, 2 \pi)
\]
* Površina ploskve
** Lagrangeov izrek
Predpostavke:
- \(  a, b \in \mathbb{R}, \ a < b \)
- \(  f: [a, b] \to \mathbb{R} \) zvezna funkcija
- \(  f \) odvedljiva na \(  (a, b) \)

Obstaja \(  c \in (a, b) \), da je

\[ f(b) - f(a) = f'(c)(b - a)
\]
*** Dokaz
**** <1>1
Case 1: \(  h(x) = f(x) (b - a) - x (f(b) - f(a)) \), zvezna na \(  [a, b] \), odvedljiva na \(  (a, b) \)

Velja

\begin{align*}
  h(a) &= f(a) (b - a) - a(f(b) - f(a)) = f(a) b - f(b) a \\
h(b) &= f(b) (b - a) - b(f(b) - f(a)) = - a f(b) + b f(a)
\end{align*}

Dokaz: Case 1
**** <1>2

\[ 0 = h'(c) = f'(c) (b - a) - (f(b) - f(a))
\]

Dokaz: <1>1 velja Rolleov izrek, \(  h'(x) \) obstaja po Case 1
**** <1>3 QED
Dokaz: <1>2
** Ploščina paralelograma
Predpostavke:
- parametrizacije ploskve \(  \vec{r}: D \to \mathbb{R} ^3 \)
*** <1>1
Majhen pravokotnik \(  P \) z oglišči v \(  (u, v) \) in stranicama \(  \Delta u \), \(  \Delta v \) preslikamo v \(  \vec{r} \).

Za dovolj majhen pravokotnik \(  P \) dobimo približno linearno preslikavo \(  \vec{r}(P) \), ki ga lahko aproksimiramo s ploščino paralelograma z oglišči \(  \vec{r}(u, v), \ \vec{r}(u + \Delta u, v), \vec{r}(u, v + \Delta v), \vec{r}(u + \Delta u, v + \Delta v) \).
*** <1>2

Velja

\begin{align*}
  \vec{r}(u + \Delta u, v) - \vec{r}(u, v) &= \vec{r}_u (u + \xi \Delta u, v) \Delta u && \xi \in (0, 1) \\
  \vec{r}(u, v + \Delta v ) - \vec{r}(u, v) &= \vec{r}_v (u, v  + \eta \Delta v) \Delta v && \eta \in (0, 1) \\
\end{align*}

Dokaz: Lagrangeov izrek za posamezno spremenljivko in definicija, da je \(  \vec{r} \in C^1 \)
*** <1>3

\begin{align*}
  \vec{r}_u(u + \xi \Delta u, v) &= \vec{r}_u (u, v) \\
\vec{r}_v (u, v + \eta \Delta v) &= \vec{r}_v (u, v)
\end{align*}

Dokaz: za majhne \( \xi, \eta  \) to se lahko aproksimira
*** <1>4

Ploščina paralelograma je pribložno enaka

\[ \left| \vec{r}_u \times \vec{r}_v \right| \Delta u \Delta v
\]

Dokaz: <1>3, <1>2
* Definicija 4. 8

Naj bo \(  D \subseteq \mathbb{R} ^2 \) območje in \(  \vec{r}: D \to \mathbb{R} ^3 \) parametrizirana ploskev \(  M = \left\{ \vec{r}(u, v); \ (u, v) \in D \right\} \). Njeno površino izračunamo kot

\[ P(M) = \iint\limits_D^{} \left| \vec{r}_u \times \vec{r}_v \right| \,\mathrm{d S}
\]
** Opomba

Oznaka \(  \left\lVert \cdot \right\rVert \) označuje normo.

\begin{align*}
  \left\lVert \vec{r}_u \times \vec{r}_v \right\rVert ^2 &= \left\lVert \vec{r}_u \right\rVert ^2 \left\lVert \vec{r}_v \right\rVert ^2 \sin \phi \\
&= \left\lVert \vec{r}_u \right\rVert ^2 \left\lVert \vec{r}_v \right\rVert ^2 \left( 1 - \cos ^2 \phi \right) \\
&= \left\lVert \vec{r}_u \right\rVert ^2 \left\lVert \vec{r}_v \right\rVert ^2 - \left| \left\langle \vec{r}_u, \vec{r}_v \right\rangle \right| ^2
\end{align*}

Z oznakami
\[ \left\lVert \vec{r}_u \right\rVert ^2 = E; \ \left\lVert \vec{r}_v \right\rVert ^2 = G; \ \left\langle \vec{r}_u, \vec{r}_v \right\rangle = F
\]

\[ P(M) = \iint\limits_D^{} \sqrt{EG - F ^2} \,\mathrm{d S}
\]
* Trditev 4.9

Definicija za površino ploskve je dobra (neodvisna od parametrizacije).
** Dokaz
*** <1>1
Case 1: \(  \vec{r}: D \to M \) parametrizacija ploskve \(  M \)
Case 2: \(  \vec{\rho} : \Delta \to M \) druga parametrizacija ploskve \(  M \)
Case 3: \(  \Phi: D \to \Delta, \ (x, y) \mapsto (U(x, y), V(x, y)) \) gladka bijekcija \(  \vec{\rho} = \vec{r} \circ \Phi \)

\begin{align*}
  \vec{\rho}_x &= \vec{r}_u \cdot U_x + \vec{r}_v \cdot V_x \\
\vec{\rho}_y &= \vec{r}_u \cdot U_y + \vec{r}_v \cdot V_y
\end{align*}

Dokaz: Verižno pravilo parcialnega odvoda \(  \vec{\rho} \).
*** <1>2

\[ \vec{\rho}_x \times \vec{\rho}_y = \det (J\Phi) \vec{r}_u \times \vec{r}_v
\]

Dokaz: Analiza 1 ter \(  \vec{r}_i \times \vec{r}_i = 0  \)

\begin{align*}
  \vec{\rho}_x \times \vec{\rho}_y &= \left( U_x \cdot V_y - V_x \cdot U_y \right) \cdot (\vec{r}_u \times \vec{r}_v) \\
&= \begin{vmatrix}
 U_x & U_y \\
V_x & V_y
 \end{vmatrix} \cdot (\vec{r}_u \times \vec{r}_v)
\end{align*}
*** <1>3 QED
Dokaz:

\begin{align*}
  P(M) &= \iint\limits_D^{} \left| \vec{r}_u \times \vec{r}_v (u, v) \right|  \,\mathrm{d S} \\
&= \iint\limits_{\Delta}^{} \left| \vec{r}_u \times \vec{r}_v (\Phi(x, y) \right| \left| \det (J \Phi) \right|\,\mathrm{d P} \\
&= \iint\limits_{\Delta}^{} \left| \vec{\rho}_x \times \vec{\rho}_y \right| \,\mathrm{d P}
\end{align*}
* Definicija 4.11

Lokalna orientacija gladke regularne krivulje \(  \Gamma \) brez samopresečišč v točki \(  \gamma \in \Gamma \) je podana z izbiro enotskega tangentnega vektorja v tej točki (imamo samo dve možni izbiri).

Globalna orientacija je podana z zvezno izbiro enotskih tangentnih vektorjev v vsaki točki \(  \gamma \in \Gamma \).
* Definicija 4.12

Lokalna orientacija gladke regularne ploskve \(  M \subseteq \mathbb{R} ^3 \) je izbira enotske normalne v točki \( m \in M \)

Globalna orientacija ploskve \(  M \) je zvezna izbira enotskih normalnih vektorjev za vse \(  m \in M \):


\begin{align*}
  \vec{n}:M &\to S ^2 \\
m & \mapsto \vec{n}(m)
\end{align*}

* Definicija 4.13
Naj bo \(  M \) orientabilna ploskev z robom \(  \partial M \). Za vsako točko \(  m \in \partial M \) naj bo \(  \vec{\mu} \) tisti enotski vektor iz tangentne ravnine \(  T_mM \), ki je pravokoten na \(  T_m\partial M \) (tangentno premico na \(  \partial \) v točki \(  m \)) in kaže ven iz \(  M \), in naj bo \(  \vec{n} \) enotski normalni vektor na \(  M \), podan z orientacijo.

Potem vektor \(  \vec{n} \times \vec{\mu} \) določa inducirano orientacijo roba \(  \partial M \) v točki \(  m \in \partial M \).
* Definicija 5.1
Naj bo \(  \Omega \subseteq \mathbb{R} ^3 \). Skalarno polje na \(  \Omega \) je funkcija \(  f: \Omega \to \mathbb{R} \). Vektorsko polje na \(  \Omega \) je preslikava \(  \vec{F}: \Omega \to \mathbb{R} ^3 \).

Definiramo nablo: \(  \nabla = \left( \frac{\partial }{\partial x}, \frac{\partial }{\partial y}, \frac{\partial }{\partial z}    \right) \)
* Standardni diferencialni operatorji v poljubnih ortogonalnih koordinatah
Vzamemo nabor ortogonalnih koordinat \(  \vec{\xi} = \left( \xi_1, \xi_2, \xi_3 \right) \) v \(  \mathbb{R} ^3 \). S parametrizacijo prostora \(  \mathbb{R} ^3 \) \(  \vec{r} \) dobimo kartezične koordinate

\[ \vec{r} = \vec{r}(\xi)
\]

Zahtevamo za vsak \(  \vec{\xi} \) in \(  \vec{r}_j = \vec{r}_j \left( \vec{\xi} \right) = \frac{\partial \vec{r}}{\partial \xi_j}  \), da velja

\[ \left\langle \vec{r}_j, \vec{r}_k \right\rangle _{\mathbb{R} ^3} = 0 \text{ za } j \ne k
\]

/Opomba/: z drugimi besedami, smerni odvodi oz. tangentni vektorji so me seboj ortogonalni v vsaki točki.
* Definicija 5.8 (Laméjevi koeficienti)
Laméjevi koeficienti so

\[ H_j = \left| \vec{r}_j \right| , \ j = 1, 2, 3
\]

in označimo

\[ H = H_1 H_2 H_3
\]

Definiramo še enotske tangentne vektorje na koordinate krivulje

\[ \vec{\eta}_j = \frac{\vec{r}_j}{H_j} = \frac{\vec{r}_j}{\left| \vec{r}_j \right|}
\]
* Definicija 5.2 (gradient)
Gradient skalarnemu polju \(  f \) priredi vektorsko polje \(  \nabla f \) na sledeč način

\[ \mathrm{grad} f = \nabla f = \left( \frac{\partial f}{\partial x}, \frac{\partial f}{\partial y}, \frac{\partial f}{\partial z}    \right)
\]
* Definicija 5.3 (divergenca)
Divergenca vektorskemu polju \(  \vec{F} = (U, V, W) \) priredi skalarno polje \(  \nabla \cdot \vec{F} \) na

\[ \mathrm{div} \vec{F} = X_x + Y_y + Z_z
\]
* Definicija 5.4 (rotor)
Rotor vektorskemu polju \(  \vec{F} = (U, V, W) \) priredi vektorsko polje \(  \nabla \times \vec{F}  \) na sledeč način

\[ \mathrm{rot} \vec{F} = (Z_y - Y_z, X_z - Z_x, Y_x - X_y)
\]
* Laplaceov operator

\[ \Delta = \mathrm{div} \circ \nabla = \frac{\partial ^2}{\partial x ^2} +  \frac{\partial ^2}{\partial y ^2 } + \frac{\frac{\partial  ^2}{\partial z ^2 }
\]
* Trditev 5.9
Predpostavke:

- nabor ortogonalnih koordinat \(  \vec{\xi} = \left( \xi_1, \xi_2, \xi_3 \right) \) v \(  \mathbb{R} ^3 \)
- skalarno polje \(  u: \mathbb{R} ^3 \to \mathbb{R} \)
- \(  U \) je izražava \(  u(\vec{x}) \) v \(  \xi \), torej \(  U(\vec{\xi}) = u \left( \vec{r} \left( \vec{\xi} \right) \right) \) oz. \(  U = u \circ \vec{r} \)

/Opomba/: \(  \vec{x} \) so kartezične in \(  \epsilon \) so poljubne koordinate

Velja

\[ \left( \nabla_{\vec{x}} u \right) \left( \vec{r} \right) = \left\langle \nabla_{\vec{\xi}} U, \begin{bmatrix} \frac{\vec{\eta}_1}{H_1}  \\ \frac{\vec{\eta}_2}{H_2} \\ \frac{\vec{\eta}_3}{H_3} \end{bmatrix} \right\rangle
\]
** Dokaz
*** <1>1
Case 1: \(  \vec{r} = (X, Y, Z) \)

Velja

\[ \frac{\partial U}{\partial \xi_j} = \left\langle \left( \nabla_{\vec{x}} u \right) \left( \vec{r}(\vec{\xi}) \right), \vec{r}_j (\vec{\xi}) \right\rangle
\]

Dokaz:
**** <2>1

\[ U(\vec{\xi}) = u \left( X (\vec{\xi}), Y(\vec{\xi}), Z(\vec{\xi}) \right) = u \left( \vec{r}(\vec{\xi}) \right)
\]

Dokaz: Case 1
**** <2>2

\[ \frac{\partial U}{\partial \xi_j} = \frac{\partial u}{\partial x} \left( \vec{r}(\vec{\xi}) \right) \cdot \frac{\partial X}{\partial \xi_j} \left( \vec{\xi} \right) + \frac{\partial u}{\partial y} \left( \vec{r}(\vec{\xi}) \right) \cdot \frac{\partial Y}{\partial \xi_j} \left( \vec{\xi} \right) + \frac{\partial u}{\partial z} \left( \vec{r}(\vec{\xi}) \right) \cdot \frac{\partial Z}{\partial \xi_j} \left( \vec{\xi} \right)
\]

Dokaz: <2>1 in verižno pravilo odvajanja
**** <2>3 QED
Dokaz: <2>2 se lahko zapiše kot

\[ \frac{\partial U}{\partial \xi_j} =  \left\langle \left( \nabla_{\vec{x}} u  \right) \left( \vec{r}(\vec{\xi}) \right), r_j \left( \vec{\xi} \right)  \right\rangle
\]
*** <1>2

\[ \left\langle \left( \nabla_{\vec{x}}u \right) \left( \vec{r} \left( \vec{\xi} \right) \right), \vec{r}_j \left( \vec{\xi} \right) \right\rangle = H_j \left\langle \left( \nabla_{\vec{x}} u \right) \left( \vec{r}\left( \vec{\xi} \right) \right), \vec{\eta}_j \right\rangle
\]

Dokaz: definicija Laméjevih koeficientov \(  \vec{r}_j = H_j \cdot \vec{\eta}_j \)
*** <1>3

\[ \left( \nabla_{\vec{x}} u \right) \left( \vec{r} \right) = \sum\limits_{j = 1}^3 \left\langle  \left( \nabla_{\vec{x}} u \right) \left( \vec{r} \right), \vec{\eta}_j  \right\rangle \cdot \vec{\eta}_j
\]

Dokaz: Ortonormirano bazo, kar \(  \vec{\eta}_j \) je, se zapiše za vsak \(  \vec{v} \in \mathbb{R} ^3 \) zapiše kot

\[ \vec{v} = \sum\limits_1^3 \left\langle \vec{v}, \vec{\eta}_j \right\rangle \cdot \vec{\eta}_j
\]

*** <1>4

\[ \sum\limits_{j = 1}^3 \left\langle \left( \nabla_{\vec{x}} u \right) \left( \vec{r} \right), \vec{\eta}_j \right\rangle \cdot \vec{\eta}_j = \left\langle \begin{bmatrix} \frac{\partial U}{\partial \xi_1} \\ \frac{\partial U}{\partial \xi_2}  \\ \frac{\partial U}{\partial \xi_3}  \end{bmatrix}, \begin{bmatrix} \frac{\vec{\eta}_1}{H_1} \\ \frac{\vec{\eta}_2}{H_2} \\ \frac{\vec{\eta}_3}{H_3} \end{bmatrix} \right\rangle
\]

Dokaz: linearna algebra

\begin{align*}
  \sum\limits_{j = 1}^3 \left\langle  \left( \nabla_{\vec{x}} u \right) \left( \vec{r} \right), \vec{\eta}_j \right\rangle \cdot \vec{\eta}_j &=  \sum\limits_{j= 1}^3 \frac{1}{H_j} \cdot \frac{\partial U}{\partial \xi_j} \cdot \vec{\eta}_j \\
&= \sum\limits_{j = 1}^3 \frac{\partial U}{\partial \xi_j} \cdot \frac{\vec{\eta}_j}{H_j}
\end{align*}
*** <1>5 QED
Dokaz: <1>4
* Lema

Predpostavke:
- nabor ortogonalnih koordinat \(  \vec{\xi} = \left( \xi_1, \xi_2, \xi_3 \right) \) v \(  \mathbb{R} ^3 \)
- \(  U \) je izražava \(  u(\vec{x}) \) v \(  \xi \), torej \(  U(\vec{\xi}) = u \left( \vec{r} \left( \vec{\xi} \right) \right) \) oz. \(  U = u \circ \vec{r} \)
- Predpostavka 1: Definiramo inverz \(  \vec{R} = \vec{r}^{-1} \), kjer velja

\[ x = \vec{r}(\vec{\xi}) \iff \vec{\xi} = \vec{R}(\vec{x})
\]

Dokaži

\[ \mathrm{rot}_{\vec{x}} \left( \frac{\vec{\eta}_j}{H_j} \circ \vec{R} \right)
\]

** Dokaz
*** <1>1
Case 1: \(  k = 1, 2, 3 \)
Case 2:

\(  U_k \left( \vec{\xi} \right) = \xi_k \)


Velja

\[ \frac{\partial U_k }{\partial \xi_k} = \delta_{jk} = \begin{cases}
1; \ k = j \\
0; \ k \ne j
\end{cases}
\]

Dokaz: Case 2
*** <1>2 QED
Case 2: \(  U_k \left( \vec{\xi} \right) = u_k \left( \vec{x} \right) \)

\[ \mathrm{rot} \left( \nabla u_{k} \left( \vec{r} \right) \right) = \mathrm{rot} \left( \frac{\vec{\eta}_k}{H_k} \circ \vec{R} \right) = 0
\]

Dokaz:

\[ \mathrm{rot} \circ \nabla = 0
\]

ter
\begin{align*}
\mathrm{rot} \left( \nabla u_k (\vec{r}) \right) &= \sum\limits_{k = 1}^3 \mathrm{rot} \left[ \left( \frac{\partial U}{\partial \xi_k} \cdot \frac{\vec{\eta}_k}{H_k} \circ \vec{R}  \right) \right] \\
&= \mathrm{rot} \left( \frac{\vec{\eta}_k}{H_k} \circ \vec{R} \right)
\end{align*}

za <1>2
* Posledica 1

\[ \mathrm{div} \left( \frac{\vec{r}_j}{H} \circ \vec{R} \right) = 0, \ \forall j
\]

/Opomba/: Pri Laméjevih koeficientih smo definirali \(  H = H_1 H_2 H_3 \), kar pomeni za \(  i, j, k \)

\[ \mathrm{div} \left( \frac{\vec{\eta}_i}{H_j H_k} \circ \vec{R} \right)
\]
** Dokaz:
*** <1>1

Velja

\[ \vec{\eta}_1 + \pm \vec{\eta}_2 \times \vec{\eta}_3
\]

Dokaz: \(  \left\{ \eta_j \right\} \) je ortonormirana baza za \(  \mathbb{R} ^3 \)
*** <1>2

\[ \mathrm{div} \left( \frac{\vec{\eta}_i}{H_j H_k} \right) = \pm \mathrm{div} \left( \frac{\vec{\eta}_j}{H_j} \times \frac{\vec{\eta}_k}{H_k} \right) = \left\langle \mathrm{rot} \left( \frac{\vec{\eta}_j}{H_j} \right), \frac{\vec{\eta}_k}{H_k} \right\rangle - \left\langle \mathrm{rot } \left( \frac{\vec{\eta}_k}{H_k} \right) , \frac{\vec{\eta}_j}{H_j}\right\rangle
\]

Dokaz:

Velja \(  \mathrm{div} \left( \vec{F} \times \vec{G} \right) = \left\langle \mathrm{rot } \vec{F}, \vec{G} \right\rangle - \left\langle \vec{F}, \mathrm{rot } \vec{G} \right\rangle\)
*** <1>3 QED

<1>2 je \(  0 - 0 \) zaradi leme
* Posledica 2

Predpostavka 1: \(  A_j = \frac{1}{H_j} \frac{\partial U}{\partial \xi_j}  \)

Velja

\[ \mathrm{div} \left[ \left( A_j \vec{\eta}_j \right) \circ  \vec{R} \right] = \left[ \frac{1}{H} \frac{\partial }{\partial \xi_j} \left( \frac{H}{H_j ^2} \frac{\partial U}{\partial \xi_j}  \right)  \right] \circ \vec{R}
\]
** Dokaz
*** <1>1
Case 1: \(  j = 1 \)

\[ \mathrm{div} \left( A_1 \vec{\eta}_1 \right) = \mathrm{div} \left( A_1 H_2 H_3 \cdot \frac{\vec{\eta}_1}{H_2 H_3} \right) = \left\langle \nabla \left( A_1 H_2 H_3 \right), \frac{\vec{\eta}_1}{H_2 H_3} \right\rangle + A_1 H_2 H_3 \cdot \mathrm{div} \left( \frac{\vec{\eta}_1}{H_2 H_3} \right)
\]

Dokaz:

Velja

\[  \mathrm{div} \left( \phi \vec{F} \right) = \left\langle \nabla \phi, \vec{F} \right\rangle_{\mathbb{R} ^3} + \phi \mathrm{div} \vec{F}
\]

*** <1>2

\[ \left\langle \nabla \left( A_1 H_2 H_3 \right), \frac{\vec{\eta}_1}{H_2 H_3} \right\rangle = \left\langle \nabla \left( \frac{H_2 H_3}{H_1} \frac{\partial U}{\partial \xi_1} , \frac{\vec{\eta}_1}{H_2 H_3} \right) \right\rangle = \frac{1}{H} \left\langle  \nabla \left( \frac{H}{H_1 ^2} \frac{\partial U}{\partial \xi_1}  \right), \vec{r}_1 \right\rangle
\]


Dokaz:

Velja \(  \vec{\eta}_1 = \frac{\vec{r}_1}{ \left| \vec{r}_1 \right|} = \frac{\vec{r}_1}{H_1} \) in potem posledično

\[ \frac{\vec{\eta}_1}{H_2 H_3} = \frac{\vec{r}_1}{H_1 H_2 H_3} = \frac{\vec{r}_1}{H}
\]

in predpostavka 1.
*** <1>3 QED

\[ \frac{1}{H} \left\langle \nabla \left( \frac{H}{H_1 ^2} \frac{\partial U}{\partial \xi_1}  \right), \vec{r}_1 \right\rangle = \frac{\partial }{\partial \xi_1} \left( \frac{H}{H_1 ^2} \frac{\partial U}{\partial \xi_1} \circ \vec{R}  \right)
\]

Dokaz:

Z verižnim pravilom iz desne strani dobimo, levo
* Izrek

\[  \Delta u = \frac{1}{H} \sum\limits_{j = 1}^3 \frac{\partial }{\partial \xi_j} \left( \frac{H}{H_j ^2} \cdot \frac{\partial U}{\partial \xi_j}  \right) \circ \vec{R}
\]
** Dokaz:
*** <1>1

\[ \Delta u = \mathrm{div} \left( \nabla u \right) = \sum\limits_{j = 1}^{ 3} \mathrm{div} \left[ A_j \vec{\eta}_j \circ \vec{R} \right]
\]
*** <1>2 QED
Upoštevamo posledico 2
* Definicija 6.1

Naj bo \(  \vec{r}: I \to \mathbb{R} ^3 \) regularna parametrizacija neke krivulje \(  \Gamma \) in \(  u: \Gamma \to \mathbb{R} \) zvezna. Integral skalarnega polja \(  u \) po \(  \Gamma \) definiramo kot

\[ \int\limits_{\Gamma}^{} u \, \mathrm{ds} = \int\limits_I^{} u(\vec{r}(t)) \left| \odv{r}(t) \right|\, \mathrm{dt}
\]
* Trditev 6.2

Definicija 6.1 je dobra.
** Dokaz:
*** <1>1
Case 1: \(  I = [a, b] \in \mathbb{R} \)
Case 2: \(  J = [\alpha, \beta] \in \mathbb{R} \)
Case 3: Druga parametrizacija \(  \vec{R}: J \to \mathbb{R} ^3 \) in \(  \phi: J \to I \) in tao velja \(  \vec{R} = \vec{r} \circ \phi \)

Prove:

\[ \int\limits_{\alpha}^{ \beta} u \left( \vec{R}(s) \right) \left| \odv{R} (s) \right| \, \mathrm{ds} = \int\limits_{\alpha}^{\beta} u(\vec{r}(\phi(s))) \cdot \left| \vec{r}(\phi(s)) \right| \, \mathrm{ds}
\]

Dokaz: Upoštevali smo \(  \vec{R} = \vec{r} \circ \phi \)
*** <1>2

\[ \int\limits_{\alpha}^{\beta} u \left( \vec{r}(\phi(s)) \right) \cdot \left| \vec{r}(\phi(s)) \right|\dot{} \, \mathrm{ds} = \int\limits_{\alpha}^{\beta} u \left( \vec{r}(\phi(s)) \right) \left| \odv{r}(\phi(s)) \cdot \dot{\phi}(s) \right|
\]

Dokaz: Verižno pravilo
*** <1>3
Case 4: \(  \phi(s) = w \)

\[ \int\limits_{\alpha}^{\beta} u \left( \vec{r}(\phi(s)) \left| \odv{r} \left( \phi(s)) \right) \cdot \dot{\phi}(s) \right| \right) \, \mathrm{ds} = \int\limits_a^b u \left( \vec{r}(w)\right) \left| \odv{r} (w) \right| \, \mathrm{dw}
\]

Dokaz:

\[ \dot{\phi}(s) = \dot{w}(s)
\]

ter menjava spremenljivk v integralu.
*** <1>4 QED

Imamo dve možnosti:

\[ \begin{cases}
(\alpha, \beta) \mapsto (a, b), \ \dot{\phi} > 0 \\
\left( \alpha, \beta) \mapsto (b, a), \ \dot{\phi} < 0 \right)
\end{cases}
\]
* Definicija 6.4

Naj bo \(  \vec{F}: \Gamma \to \mathbb{R} ^3 \) zvezna. Integral vektorskega polja \(  \vec{F} \) po \(  \Gamma \) definiramo kot

\[ \int\limits_{\Gamma}^{} \vec{F} \, \mathrm{d} \vec{r} = \int\limits_a^b \left\langle \vec{F}\left( \vec{r}(t)) \right), \odv{r}(t) \right\rangle \, \mathrm{ dt}
\]
* Trditev 6.5

Če v definiciji nadomestimo \(  \vec{r} \) z drugo parametrizacijo \(  \vec{R} \) iste krivulje, tedaj je novi izraz

\[ \int\limits_{\Gamma}^{} \left\langle \vec{F} \circ \vec{R}, \odv{R} \right\rangle \, \mathrm{dx}
\]

- enak, če \(  \vec{R} \) ohranja orientacijo
- nasprotno enak, če \(  \vec{R} \) obrne orientacijo.
** Dokaz
*** <1>1
Case 1: \(  I = [a, b] \in \mathbb{R} \)
Case 2: \(  J = [\alpha, \beta] \in \mathbb{R} \)
Case 3: Druga parametrizacija \(  \vec{R}: J \to \mathbb{R} ^3 \) in \(  \phi: J \to I \) in tao velja \(  \vec{R} = \vec{r} \circ \phi \)
* Definicija 6.8
Vektorsko polje \(  \vec{F}: \Omega \to \mathbb{R} ^3 \), kjer je \(  \Omega \subseteq \mathbb{R} ^3 \) odprta množica, je potencialno, če obstaja skalarno polje \(  u: \Omega \to \mathbb{R} \), da je \(  \vec{F} = \mathrm{grad} u = \nabla u \). Funkcijo \(  u \) imenujemo potencial polja \(  \vec{F} \).
* Trditev 6.9
Naj bo \(  \Gamma \) regularna krivulja med točkama \(  A, B \in \mathbb{R} ^3 \) in naj bo \(  \vec{F} = \nabla u \) potencialno vektorsko polje. Potem je

\[ \int\limits_{\Gamma}^{} \vec{F} \mathrm{d} \vec{r} = u(B) - u(A)
\]
** Dokaz
*** <1>1

\[ \int\limits_{\Gamma}^{} \vec{F} \mathrm{d} \vec{r} = \int\limits_{\Gamma}^{} \nabla u \mathrm{d} \vec{r}
\]

Dokaz: Predpostavka iz trditve
*** <1>2
Case 1: parametrizacija \( \vec{r}: [\alpha, \beta] \to \Gamma  \)

\[ \int\limits_{\Gamma}^{} \nabla u \mathrm{d} \vec{r} = \int\limits_{\alpha}^{\beta} \left\langle \left( \nabla u \right) \circ \vec{r}, \odv{r} \right\rangle_{\mathbb{R} ^3} \mathrm{dt}
\]

Dokaz: Definicija integrala vektorskega polja
*** <1>3
\[ \int\limits_{\Gamma}^{} \frac{\mathrm{d} }{\mathrm{d} t} \left( u \circ \vec{r} \right) \, \mathrm{ dt}
\]

Dokaz: Verižno pravilo
*** <1>4

\[ \int\limits_{\alpha}^{\beta} \frac{\mathrm{d} }{\mathrm{d} t} \left( u \circ \vec{r} \right) \, \mathrm{dt} = \left( u \circ \vec{r} \right) \left( \beta \right) - \left( u \circ \vec{r} \right) \left( \alpha \right)
\]

Dokaz: Osnovni izrek analize
*** <1>5 QED

\[ \left( u \circ \vec{r} \right) \left( \beta \right) - \left( u \circ \vec{r} \right) \left( \alpha \right) = u (B) - u(A)
\]
* Trditev 6.10
Predpostavke 1: \(  \Omega \subset \mathbb{R} ^3 \) povezana odprta množica
Predpostavka 2: \(  \vec{F}: \Omega \to \mathbb{R} ^3 \)

1) \(  \vec{F} \) je potencialno
2) integral \(  \vec{F} \) po vsaki sklenjeni krivulji je enak 0
3) za vsak \(  A, B \subset \Omega \) je integral \(  \vec{F} \) od \(  A \) do \(  B \) neodvisno od izbire poti med točkama
** Dokaz:
*** <1>1
\(  1 \implies 2 \)

Dokaz:
**** <2>1
Case 1: \(  \Gamma \) sklenjena krivulja v \(  \Omega \)
Case 2: \(  A \in \Gamma \)

\[ \oint\limits_{\Gamma}^{} \vec{F} \mathrm{d}\vec{r}  = u(A) - u(A) = 0
\]

Dokaz: Trditev 6.9
**** <2>2 QED
*** <1>2

\(  2 \implies 3 \)

Dokaz:
**** <2>1
Case 1: \(  \Gamma_1 \) in \(  \Gamma_2 \) sta dve krivulji, ki povezujeta točki \(  A \) in \(  B \)
Case 2: \(  \Gamma = \Gamma_1 \cup \left( - \Gamma_2 \right) \), kjer je \(  -\Gamma_2 \) krivulja \(  \Gamma_2 \) z nasprotno orientacijo.

\[ \int\limits_{\Gamma}^{} \vec{F} \mathrm{d} \vec{r} = 0
\]

Dokaz: 2)
**** <2>2

\[ \int\limits_{\Gamma_1}^{} \vec{F} \mathrm{d} \vec{r} + \int\limits_{- \Gamma_2}^{} \vec{F} \mathrm{d}\vec{r} = \int\limits_{\Gamma_1}^{} \vec{F} \mathrm{d}\vec{r} - \int\limits_{\Gamma_2}^{} \vec{F} \mathrm{d} \vec{r} = 0
\]


Dokaz: Trditev 6.5 za spremembo predznaka
**** <2>3 QED

Dokaz: <2>2

\[ \int\limits_{\Gamma_1}^{} \vec{F} \mathrm{d}\vec{r} = \int\limits_{\Gamma_2}^{} \vec{F} \mathrm{d} \vec{r}
\]
*** <1>3

\(  3 \implies 1 \)
**** <2>1
Case 1: \(  \vec{F} = \left( U, V, W \right) = \nabla u \)
Case 2: \(  \Gamma \) je pote od \(  A \) do \(  B \)

Definiramo funkcijo

\[ u(B) = u(A) + \int\limits_{\Gamma}^{} \vec{F} \mathrm{d} \vec{r}
\]

kjer je \(  u(A) \) konstanten.
Dokaz: Trditev 6.9
**** <2>2

\[ \nabla (u + C) = \vec{F}
\]

za konstanto \(  C \in \mathbb{R} \).

Dokaz: Case 1 in odvod po konstanti
**** <2>3

\[ u(A) = 0
\]

Dokaz: Gradient je po <2>2 in <2>1 določen do aditivne konstante natančno
**** <2>4
Case 3: \(  \Gamma \) je poljubna pot od \(  A \) do \(  T \) znotraj \(  \Omega \)

\[ u(T) = \int\limits_{\Gamma}^{} \vec{F} \mathrm{d} \vec{r}
\]

je dobro definiran.

Dokaz: Predpostavka
**** <2>5

Velja

\[ \nabla u = \vec{F}
\]
***** <3>1
Case 1: \(  \Gamma_1 \) je poljubna pot od \(  A \) do \(  (x, y, z) \)
Case 2: \(  \Gamma_2 \) je poljubna pot od \(  A \) do \(  (x + h, y, z) \)

\[ u_x = \lim_{h \to 0} \frac{1}{h} \left[ u(x + h, y, z) - u(x, y, z) \right] = \lim_{h \to 0} \frac{1}{h} \left[ \int\limits_{\Gamma_2}^{} \vec{F} \mathrm{d}\vec{r} - \int\limits_{\Gamma_1}^{} \vec{F} \mathrm{d} \vec{r} \right]
\]

Dokaz: Definicija odvoda funkcije \(  u \) po \(  x \) ter <2>4
***** <3>2
Case 3: \(  \Gamma_3 \) je daljica \(  \left( x, y, z \right) \) do \(  \left( x + h, y, z \right) \)

Velja \(  \Gamma_2 = \Gamma_1 \cup \Gamma_3 \)

Dokaz: \(  \Gamma_2  \) je poljubna pot
***** <3>3
Case 4: parametriziramo \(  \Gamma_2 \) \(  \vec{r}(t) = \left( x + ht, y, z \right), t \in [0, 1] \)
Case 5: \(  \odv{r} = \left( h, 0, 0 \right) \)

\[ u(x + h, y, z) - u(x, y, z) = \int\limits_{\Gamma_3}^{} \vec{F} \mathrm{d} \vec{r} = \int\limits_0^1 \vec{F}\left( \vec{r}(t) \right) \cdot \odv{r} \mathrm{dt} = \int\limits_0^1 U \left( x + h, y, z \right) h \mathrm{dt}
\]

Dokaz: <2>4, <3>2 ter Case 4 in Case 5
***** <3>4 QED

\[ u_x = \lim_{h \to 0} \frac{1}{h} \int\limits_0^1 h \cdot U (x + h, y, z) \mathrm{dt} = U(x, y, z)
\]

Dokaz: upoštevamo <3>1, <3>3, ter, da je U zvezna in posledično tudi integral.

Analogno še za \(  y \) in \(  z \).
**** <2>6 QED
Dokaz <2>5
*** <1>4 QED
* Izrek 6.12
Delo rezultante sil (= vsote vseh sil), ki delujejo na delec, je enako spremembi kinetične energije. Ker je celotna energija enaka vsota kinetične in potencialne energije, je delo enako negativni spremembi potencialne energije

\[ A = - \Delta u = U(r_0) - U(r_1)
\]
* Definicija 6.14
Območje \(  \Omega \subset \mathbb{R} ^3 \) je zvezdasto, če obstaja \(  \omega_0 \in \Omega \) tako, da velja za vsak \(  \omega \in \Omega \) je daljica \(  \left[ \omega_0, \omega \right] \) cela vsebovana v \(  \Omega \).

\[ \left[ \omega_0, \omega \right] = \left\{ (1 - t) \omega_0 + t \omega; \ t \in [0, 1] \right\}
\]

/Opomba/: Konveksna množica je množica, ki vsebuje vse daljice med dvema poljubnima točkama iz množice. Posledično je vsaka konveksna množica zvezdasta.
* Izrek 6.15

Predpostavka 1: \(  \Omega \subseteq \mathbb{R} ^3 \) zvezdasto območje
Predpostavka 2: \(  \vec{F} \) odvedljivo vektorsko polje na \(  \Omega \)

\[ \nabla \times \vec{F} = 0 \implies \vec{F} \text{ potencialno}
\]
** Dokaz
*** <1>1
Case 1: \(  \omega_0 \in \Omega \)
Case 2: poljuben \( \omega \in \Omega: \ u(\omega) = \int\limits_{\left[ \omega_0, \omega \right]}^{} \vec{F} \mathrm{d} \vec{r} \)

Velja

\[ \nabla u = \vec{F}
\]
**** <2>1
Case 3: daljico \(  \left[ \omega_0, \omega \right] = \left[ (x_0, y_0, z_0), (x, y, z) \right] \) parametriziramo

\[ \vec{r}(t) = \begin{bmatrix} (1 - t)x_0 + tx \\ (1 -t) y_0 + ty  \\ (1 -t) z_0 + tz  \end{bmatrix} = \begin{bmatrix} r_1(t) \\ r_2(t) \\ r_3(t) \end{bmatrix}
\]

Velja

\[ \int\limits_{\left[ \omega_0, \omega \right]}^{} \vec{F} \mathrm{d} \vec{r} = \int\limits_0^1 \left\langle \vec{F}(\vec{r}(t)), \odv{r}(t) \right\rangle_{\mathbb{R} ^3} \mathrm{dt} = \int\limits_0^1 \left\langle \vec{F}\left( \vec{r}(t) \right), \omega - \omega_0 \right\rangle \mathrm{dt}
\]

Dokaz: definicija integrala vektorskega polja ter definicija parametrizacije Case 3
**** <2>2
Case 4: \(  \left( \nabla u \right) \left( \omega \right) = \left( u_x, u_y, u_z \right) \left( \omega \right) \)

\[ u_x \left( \omega \right) = \int\limits_0^1 \left( \left\langle \frac{\partial }{\partial x} \left[ \vec{F}\left( \vec{r}(t) \right) \right], \omega - \omega_0  \right\rangle + \left\langle \vec{F} \left( \vec{r}(t) \right), \frac{\partial }{\partial x} \left( \omega - \omega_0 \right)  \right\rangle \right)
\]

Dokaz: \(  u \) je odvedljiv, ker je integrand \(  \vec{F} \) po predpostavki 2 odvedljiv, ter verižno pravilo <2>1
**** <2>3
Case 5: \(  \vec{F} = \left( F_1, F_2, F_3 \right) \)

Velja

\[ \frac{\partial }{\partial x} \left[ \vec{F}(\vec{r}(t)) \right] = \left( \frac{\partial }{\partial x} \left( F_1 (\vec{r}) \right), \frac{\partial }{\partial x} F_2 \left( \vec{r}(t) \right), \frac{\partial }{\partial x} \left( F_3 \left( \vec{r}(t) \right) \right) \right)
\]

Dokaz: Odvod vektorja je odvod posamezne komponente vektorja
**** <2>4
Case 6: \(  F_i = F_i \left( a_i, b_i, c_i \right), \ i = 1, 2, 3 \) in \(  a_i, b_i, c_i = r_1, r_2, r_3 \)

Za \(  i = 1 \) velja

\[ \frac{\partial }{\partial x} \left( F_1 \left( \vec{r} \right) \right) = \left( \frac{\partial F_1}{\partial a}   \right)  \left( \vec{r}(t) \right) \cdot \frac{\partial }{\partial x} \left( r_1 (t) \right) + \underbrace{ \left( \frac{\partial F_1}{\partial b}   \right) \left( \vec{r}(t) \right) \cdot \frac{\partial }{\partial x} \left( r_2 (t) \right)}_{0} +  \underbrace{ \left( \frac{\partial F_1}{\partial c}  \right) \left( \vec{r}(t) \right) \cdot \frac{\partial }{\partial x} \left( r_3 (t) \right)}_{0}
\]

Dokaz: Verižno pravilo, \(  a = r_1, b=r_2, c = r_3 \) ter to, da po Case 3, \(  r_2 \ne r_2(x) \) in \(  r_3 \ne r_3(x) \)
**** <2>5

\[ \frac{\partial }{\partial x} \left[ \vec{F} \left( \vec{r}(t) \right) \right] = t \left( \frac{\partial F_1}{\partial a} \left( \vec{r} \right), \frac{\partial F_2}{\partial a} \left( \vec{r} \right), \frac{\partial F_3}{\partial a} \left( \vec{r} \right)    \right)
\]

Dokaz: Odvod iz <2>4 je po definiciji <2>1 Case 3 enak \( \frac{\partial }{\partial x} \left( r_1 \right) = t  \) in to za vsak \( i \) \( F_i \)
**** <2>6

\[  t \left( \frac{\partial F_1}{\partial a} \left( \vec{r} \right), \frac{\partial F_2}{\partial a} \left( \vec{r} \right), \frac{\partial F_3}{\partial a} \left( \vec{r} \right)    \right) = t \left( \frac{\partial F_1}{\partial a} \left( \vec{r} \right), \frac{\partial F_1}{\partial b} \left( \vec{r} \right), \frac{\partial F_1}{\partial c} \left( \vec{r} \right)\right)
\]

Dokaz: iz predpostavke \( \mathrm{rot} \vec{F} = 0 \) dobimo sledeče ekvivalence:

\begin{align*}
\begin{vmatrix}
 i& j & k \\
\partial_a & \partial_b & \partial_c \\
F_1 & F_2 & F_3
\end{vmatrix} = \left( \partial_b F_3 - \partial_c F_2, \partial_c F_1 - \partial_a F_3, \partial_a F_2 - \partial_b F_1 \right) &= (0, 0, 0) \\
\implies \partial_c F_1 &= \partial_a F_3 \\
\implies \partial_a F_2 &= \partial_b F_1
\end{align*}
**** <2>7
Case 7: uvedemo oznako \(  \tilde{\nabla} = \left( \partial_a, \partial_b, \partial_c  \right) \)

\[ \left( u_x  \right) \left( \omega \right) = \int\limits_0^1 \left( \left\langle t \tilde{\nabla} F_1 \left( \vec{r} \right), \omega - \omega_0 \right\rangle  + F_1 \left( \vec{r} \right) \right) \,\mathrm{d x}
\]

Dokaz: <2>1 in notacija uvedena v <2>7 Case 7, definiciji \(  \omega, \omega_0 \)
**** <2>8

\[ \int\limits_0^1 \left[ t \frac{\mathrm{d} \left( F_1 \circ \vec{r} \right)}{\mathrm{d} t} + \left( F_1 \circ \vec{r} \right)  \right] \,\mathrm{d t}
\]

Dokaz: \(  \omega - \omega_0 = \dot{r} \), in skupaj z verižnim pravilom
**** <2>9

\[ \int\limits_0^1 \frac{\mathrm{d}  \left( t \cdot \left( F_1 \circ \vec{r} \right) \right)}{\mathrm{d} t} \,\mathrm{d t}  = \left. \left( t \cdot F_1 (\vec{r}(t)) \right) \right|_{t = 0}^{t=1} = F_1 \left( \vec{r}(1) \right) = F_1 \left( \omega \right)
\]

Dokaz: osnovni izrek analize ter definicija \(  \vec{r} \) iz <2>1 Case 3
**** <2>10 QED

Dokazali smo, da velja \(  u_x = F_1 \) in enako velja za \(  u_y = F_2, \ u_z = F_3\)
*** <1>2 QED
Dokaz: <2>10
* Definicija 6.16

Naj bo \(  M \subset \mathbb{R} \) neka regularna ploskev in \(  f: M \to \mathbb{R} \)
zvezna.

Ploskovni integral skalarnega polja \(  f \) definiramo kot

\[ \int\limits_M f \,\mathrm{d S}  = \iint\limits_D f(\vec{r}(u, v))
\left| \vec{r}_u \times \vec{r}_v \right| \, \mathrm{d u} \, \mathrm{ dv}
\]

kjer je \(  \vec{r}: D \to M \) poljubna regularna parametrizacija za M.
* Definicija 6.19

Naj bo \(  M \) ploskev z orientacijo \(  \vec{N} \). Ploskovni integral zveznega vektorskega polja \(  \vec{F}: M \to \mathbb{R} ^3 \) je definiran s predpisom

\[ \iint\limits_M \vec{F} \,\mathrm{d } \vec{S} = \iint\limits_M^{} \left\langle \vec{F}, \vec{N} \right\rangle \,\mathrm{d S}
\]
* Izrek 6.20 (Gaussov izrek)

Predpostavke:
- \(  \Omega \) odprta omejena množica v \(  \mathbb{R} ^3 \) z odsekoma gladkim robom
- \(  \vec{F} \in C^1 \) vektorsko polje v okolici \(  \bar{\Omega} = \Omega \cup \partial \Omega \)
- \(  \partial \Omega \) je ploskev z orientacijo \(  \vec{N} \), ki kaže ven iz \(  \Omega \)

Velja:

\[ \iint\limits_{\partial \Omega}^{} \vec{F} \,\mathrm{d } \vec{S} = \iiint\limits_{\Omega}^{} \mathrm{div} \vec{F} \,\mathrm{d V}
\]
** Dokaz
Dokaz je narejen samo za primer, ko lahko območje \(  \Omega \) zapišemo med dvema grafoma \(  \Gamma_f \) in \(  \Gamma_g \)
*** <1>1
Case 1: \(  \vec{F} = \left( X, Y, Z \right) \)
Case 2: \(  \vec{N} = \left( N_1, N_2, N_3 \right) \)
Case 3: \(  \Omega = \left\{ \left( x, y, z \right) \in \mathbb{R} ^3;\ f(x, y) < z < g(x, y) \right\} \)

Integral, ki ga dokazujemo, lahko zapišemo kot

\[ \iint\limits_{\partial \Omega}^{} \left( XN_1 + YN_2 + ZN_3 \right) \,\mathrm{d S} = \iiint\limits_{\Omega}^{} \left( X_x + Y_y + Z_z \right) \,\mathrm{d V}
\]

Dovolj je pokazati, da velja integral za eno komponento.
*** <1>2

Velja

\[ \iint\limits_{\partial \Omega}^{} ZN_3 \,\mathrm{d S} = \iiint\limits_{\Omega}^{} Z_z \,\mathrm{d V}
\]
Dokaz:
**** <2>1
Case 4: \(  \Omega = \Gamma_f + \Gamma_g + \mathrm{plasc} \)

\[ \mathrm{LS} = \iint\limits_{\Gamma_f}^{} ZN_3 \,\mathrm{d S} + \iint\limits_{\Gamma_g}^{} ZN_3 \,\mathrm{d S} + \underbrace{\iint\limits_{\mathrm{plasc}}^{} ZN_3 \,\mathrm{d S }}_{0}
\]

Dokaz: Integral po množici je vsota integralov podmnožic, ki jo sestavljajo. Po predpostavki 3 \(  \vec{N} \) kaže navzen in za plašč to pomeni \(  \vec{N} = \left( \cdot, \cdot, 0 \right) \)
**** <2>2
Case 5: parametrizacija \(  \Gamma_f \) je \(  \vec{r} (x, y) = \left( x, y, f(x, y) \right); \ (x, y) \in D \subset \mathbb{R} ^2 \)
Case 6: parametrizacija \(  \Gamma_g \) je \(  \vec{R}(x, y) = \left( x, y, g(x, y) \right); (x, y) \in D \subset \mathbb{R} ^2 \)

\[ LS = \iint\limits_D^{} Z(x, y, f(x,y)) \cdot \left( - \frac{1}{\sqrt{1 + f_x ^2 + f_y ^2}} \right) \cdot \sqrt{1 + f_x ^2 + f_y ^2} \,\mathrm{d x dy} + \iint\limits_D^{} Z(x, y, g(x, y)) \cdot  \left(  \frac{1}{\sqrt{1 + g_x ^2 + g_y ^2}} \right) \cdot \sqrt{1 + g_x ^2 + g_y ^2} \,\mathrm{dxdy }
\]

Dokaz:
***** <3>1

\[  \vec{r}_x \times \vec{r}_y = (- f_x, -f_y, -1)
\]

in

\[ \vec{R}_x \times \vec{R}_y = \left( - g_x, -g_y, 1 \right)
\]


Dokaz: odvod in vektorski produkt parametrizacije Case 5 za funkciji \(  f \) in \(  g \) in predpostavka 3
***** <3>2

\[ \vec{N} = \frac{\vec{r}_x \times \vec{r}_y}{\left| {\vec{r}_x \times \vec{r}_y} \right|} \implies N_3 = - \frac{1}{\sqrt{1 + f_x ^2 + f_y ^2}}
\]

Dokaz:

Vektorski produkt in <3>1
***** <3>3 QED
Dokaz: <3>2 ter uvedba parametrizacije v integralu Definicija 4.8
**** <2>3

\[ \iint\limits_D^{} \left[ Z(x, y, g(x, y)) - Z(x, y, f(x, y)) \right] \,\mathrm{d xdy} = \iint\limits_D^{} \int\limits_{f(x,y)}^{g(x, y)} Z_z(x, y, t) \,\mathrm{d t} \,\mathrm{d x dy}
\]

Dokaz: <2>2 in osnovni izrek analize
**** <2>4 QED

\[   \iint\limits_D^{} \int\limits_{f(x,y)}^{g(x, y)} Z_z(x, y, t) \,\mathrm{d t} \,\mathrm{d x dy} = \iiint\limits_{\Omega}^{} Z_z \,\mathrm{d V}
\]
*** <1>3 QED

Dokaz <1>2 in s enako lahko naredimo z ostalimi komponentami.
* Izrek 6.24 (Greenova formula)

Predpostavke:
- \(  D \subset \mathbb{R} ^2 \) območje z odsekoma gladkim robom
- \(  \partial D \) je končna unija odsekoma gladkih krivulj
- \(  \partial D \) orientirana skaldno z normalo \(  (0, 0, 1) \) na D
- \( \vec{F}(X, Y) \in C^1 \) vektorsko polje na okolici \(  \bar{D} \)

Velja

\[ \oint\limits_{\partial D}^{} X \,\mathrm{d x} + Y \, \mathrm{dy} = \iint\limits_D^{} \left( Y_x - X_y \right) \,\mathrm{d xdy}
\]
** Dokaz
Dokaz je podoben dvodimenzionalnemu Gaussovemu izreku
*** <1>1
Case 1: \(  \vec{G} = (U, V) \)

\[ \oint\limits_{\partial D}^{} \left\langle \vec{G}, \vec{N} \right\rangle \,\mathrm{d s} = \iint\limits_D^{} \mathrm{div} \vec{G} \,\mathrm{d S}
\]
*** <1>2
Case 2: \(  \vec{T} \) je tangenta krivulje

Integral <1>1 je zelo podoben temu, kar želimo dokazati, če \(  \vec{N} \) zamenjamo s \(  \vec{T} \)

Za \(  \vec{H} = (-V, U) \) velja

\[ \left\langle \vec{G}, \vec{N} \right\rangle = \left\langle \vec{H}, \vec{T} \right\rangle
\]
**** <2>1
Case 3: \(  \underline{R} = \begin{bmatrix}
0& -1 \\
1 & 0
\end{bmatrix} \)

\[ \vec{T} = \underline{R} \vec{N}
\]

Dokaz: \(  \underline{R} \in \mathbb{R} ^2 \) rotira \(  \vec{N} \) za kot \(  \frac{\pi}{2} \), kar pa je ravno vektor \(  \vec{T} \).
**** <2>2

\[ \vec{N} = R^{-1} \vec{T}
\]

Dokaz:

Množenje z \(  \underline{R}^{-1} \)

**** <2>3

\[ \left\langle \vec{G}, \vec{N} \right\rangle = \left\langle \vec{G}, \underline{R}^{-1} \vec{T} \right\rangle
\]

Dokaz:

Upoštevamo <2>2

**** <2>4

\[ \left\langle \vec{G}, \underline{R}^{-1} \vec{T} \right\rangle = \left\langle \underline{R} \vec{G}, \underline{T} \right\rangle
\]

Dokaz:

***** <3>1

Matrika \(  \underline{R} \) je ortogonalna

Dokaz: Za ortogonalno matriko velja

\[ \underline{R}^T = \underline{R}^{-1} \iff \ \left( \underline{R}^{-1} \right)^T = \underline{R} \iff \ \underline{R}^T \underline{R} = \underline{R} \underline{R}^T = I
\]

***** <3>2

\begin{align*}
 \left. \underline{R} \cdot \right/ \quad \left\langle \vec{G}, \underline{R}^{-1} \vec{T} \right\rangle &= \left\langle \underline{R} \vec{G}, \underline{R} \cdot \underline{R}^{-1} \vec{T} \right\rangle \\
&= \left\langle \underline{R} \vec{G}, \vec{T} \right\rangle
\end{align*}

Dokaz: Matrika je ortogonalna
***** <3>3 QED
**** <2>5 QED

\[ \underline{R} \vec{G} = H = (-V, U)
\]
*** <1>3

\[ \oint\limits_{\partial D}^{} \left\langle \vec{H}, \vec{T} \right\rangle \,\mathrm{d s} = \oint\limits_{\partial D}^{} -V \mathrm{dx} + U \,\mathrm{d y}
\]

Dokaz:<1>2  ter <1>1
*** <1>4

\[ \iint\limits_D^{} \mathrm{div} \vec{G} \,\mathrm{d S} = \iint\limits_D^{} U_x + V_y  \,\mathrm{d xdy}
\]

Dokaz: definicija divergence
*** <1>5

Z izborom \(  (U, V) = (Y, -X) \) velja

\[ \oint\limits_{\partial D}^{} -V \,\mathrm{d x} + U \, \mathrm{dy} = \iint\limits_D^{} U_x + V_y \,\mathrm{d xdy}
\]


Dokaz: analiza 1
*** <1>6 QED
* Izrek 6.25 (Stokesov izrek)

Predpostavke:

- \(  M \) omejena gladka orientirana ploskev v \(  \mathbb{R} ^3 \)
- \(  \vec{F} = (X, Y, Z): M \to \mathbb{R} \) vektorsko polje
- \(  \vec{F} \) definirano v okolici \(  M \)

Velja

\[ \int\limits_{\partial M}^{} \vec{F} \,\mathrm{d } \vec{r} = \iint\limits_M^{} \vec{F} \,\mathrm{d S}
\]
** (Skica) dokaza
*** <1>1
Case 1: \(  D \subset \mathbb{R} ^2 \)
Case 2: \(  f: D \to \mathbb{R} \)
Case 3: \(  M = \Gamma_f = \left\{ \vec{r}(x, y) = \left( x, y, f(x, y) \right); (x,y) \in D \right\} \)

\[ \int\limits_{\partial M}^{} \vec{F} \,\mathrm{d } \vec{r} = \int\limits_{\partial M}^{} X \,\mathrm{d x} + Y \, \mathrm{dy} + Z \left[ f_x \, \mathrm{dx} + f_y \, \mathrm{dy } \right]
\]

Dokaz:
Definicija 6.4, kjer je \(  d \vec{r} = \odv{r}(t) dt = \left( \mathrm{dx}, \mathrm{dy}, f_x \, \mathrm{dx} + f_y \mathrm{dy} \right) \)
*** <1>2
Case 4: \(  \vec{F} = (X, Y, Z) = \left( X (u, v, w), Y(u, v, w), Z(u, v, w) \right) \)

\begin{align*}
\int\limits_{\partial M}^{} \left[ X + Z f_x \right] \,\mathrm{d x} + \left[ Y + Zf_y \right] \, \mathrm{dy } = \iint\limits_D^{} &\left[ Y_u \left( \vec{r} \right) \frac{\partial x}{\partial x} + \underbrace{Y_v \left( \vec{r} \right) \cdot \frac{\partial y}{\partial x}}_{0} + Y_w \left( \vec{r} \right) \cdot \frac{\partial f(x, y)}{\partial x} + f_y \cdot \left( Z_u \left( \vec{r} \right) \cdot \frac{\partial x}{\partial x} + \underbrace{Z_v \left( \vec{r} \right) \cdot \frac{\partial y}{\partial x}}_{0} + Z_w \left( \vec{r} \right) \cdot \frac{\partial f(x, y)}{\partial x} \right) + Z \cdot f_{yx}    \right. \\
 &-  \left. \left( \underbrace{X_u \left( \vec{r} \right) \cdot \frac{\partial x}{\partial y}}_{0} + X_v \left( \vec{r} \right) \cdot \frac{\partial y}{\partial y} + X_w \left( \vec{r} \right) \cdot \frac{\partial f(x, y)}{\partial y} + f_x \left[ \underbrace{Z_v \left( \vec{r} \right) \cdot \frac{\partial x}{\partial y} }_0 + Z_v \left( \vec{r} \right) \cdot \frac{\partial y}{\partial y} + Z_w \left( \vec{r} \right) \cdot \frac{\partial f(x, y)}{\partial y} \right] + Z \cdot f_{yx} \right) \right] \,\mathrm{dx dy} \\
&= \iint\limits_D^{} \left[ -f_x \left( Z_v - Y_w \right) - f_y \left( X_w - Z_u \right) + \left( Y_u - X_v \right) \right] \,\mathrm{d xdy}
\end{align*}

Dokaz: Uporaba Greenove formule
*** <1>3

\[ \iint\limits_D^{} \left[ -f_x \left( Z_v - Y_w \right) - f_y \left( X_w - Z_u \right) + \left( Y_u - X_v \right) \right] \,\mathrm{d xdy} = \iint\limits_D^{} \left\langle  \mathrm{rot} \vec{F} \left( \vec{r} \right), \vec{N} \right\rangle \sqrt{1 + f_x ^2 + f_y ^2} \, \mathrm{dy dx}
\]

Dokaz: Definicija skalarnega produkta in rotorja vektorske funkcije \(  \vec{F} \)
*** <1>4 QED

\[ \iint\limits_D^{} \left\langle \mathrm{rot} \vec{F} \left( \vec{r} \right), \vec{N} \right\rangle \sqrt{1 + f_x ^2 + f_y ^2} \,\mathrm{dS } = \iint\limits_M^{} \mathrm{rot} \vec{F} \,\mathrm{d } \vec{S}
\]
* Posledica

Rotor je neodvisen od izbire ONB.
** Dokaz:
*** <1>1
Case 1: \(  \vec{r}_0 \in \mathbb{R} ^3 \)
Case 2: \(  \vec{F} \in C^1 \) vektorsko polje definirano v okolici točke \(  \vec{r}_0 \)
Case 3: \(  \vec{n} \in \mathbb{R} ^3 \)
Case 4: \(  \Pi_{\vec{n}} \subset R ^3 \) je ravnina skozi točko \(  \vec{r}_0 \) z normalo \(  \vec{n} \)
Case 5: \(  K_{\vec{n}} ^2 \left( \vec{r}_0, \epsilon \right) \) je krog v \(  \Pi_{\vec{n}} \) s središčem v \(  \vec{r}_0 \) in radijem \(  \epsilon \)
Case 6: \(  S_{\vec{n}} ^1 \) krožinica s središčem v \(  \vec{r}_0 \) in radijem \(  \epsilon \)

\[ \mathrm{rot} \vec{F} \left( \vec{r} \right) \cdot \vec{n} = \lim_{\epsilon \to 0} \overline{\left( \mathrm{rot} \vec{F} \cdot \vec{n} \right)}_{K_{\vec{n}}^2 \left( \vec{r}, \epsilon \right)}
\]

kjer je \(  \cdot \) skalarni produkt in \( \overline{\left( \cdot \right)}_{K_{\vec{n}} ^2 \left( \vec{r}, \epsilon \right)} \) povprečje na krogu Case 5
*** <1>2

\[ \lim_{\epsilon \to 0} \overline{\mathrm{rot} \vec{F} \cdot \vec{n}}_{K_{\vec{n}}^2 \left( \vec{r}, \epsilon \right)} = \lim_{\epsilon \to 0} \frac{1}{\pi \epsilon ^2} \iint\limits_{K_{\vec{n}} ^2 \left( \vec{r}, \epsilon \right)}^{} \mathrm{rot }\vec{F} \cdot \vec{n} \,\mathrm{d S}
\]

Dokaz: Definicija povprečja zvezne funkcije na krogu Case 5
*** <1>3

\[ \lim_{\epsilon \to \epsilon} \frac{1}{\pi \epsilon ^2} \iint\limits_{K_{\vec{n}} ^2 \left( \vec{r}, \epsilon \right)}^{} \mathrm{rot} \vec{F} \cdot \vec{n} \,\mathrm{d S} = \lim_{\epsilon \to 0} \frac{1}{\pi \epsilon ^2} \oint\limits_{S_{\vec{n}}^1 \left( \vec{r}, \epsilon \right)} \vec{F} \,\mathrm{d } \vec{r}
\]

Dokaz: Stokesov izrek

\[ \lim_{\epsilon \to 0} \frac{3}{4 \pi \epsilon ^3} \iint\limits_{S ^2 \left( \vec{r}, \epsilon \right)}^{} \vec{F}  \,\mathrm{d } \vec{S}
\]
*** <1>4 QED
Dokaz: <1>3
* Izrek 6.27 (Greenovi identiteti)
Predpostavke:
- \(  \Omega \subset \mathbb{R} ^3 \) odprta množica z odsekoma gladkim robom
- \(  u, v \in C^2 \) skalarni polji na neki odprti okolici zaprtja \(  \bar{\Omega} \)
- \(  \vec{n} \) je enotska zunanja normala na \(  \partial \Omega \)


Velja prve Greenova identiteta

\[ \varoiint\limits_{\partial \Omega}^{} u \frac{\partial v}{\partial \vec{n}}   \,\mathrm{d S} = \iiint\limits_{\Omega}^{} \left( u \Delta v + \left\langle \nabla u, \nabla v \right\rangle \right) \,\mathrm{d V}
\]

in druga Greenova identiteta

\[ \varoiint \limits_{\partial \Omega}^{} \left( u \frac{\partial v}{\partial \vec{n}} - v \frac{\partial u}{\partial \vec{n}}   \right) \,\mathrm{d S} = \iiint\limits_{\Omega}^{} \left( u \Delta v - v \Delta u \right) \,\mathrm{d V}
\]
** Dokaz:
*** <1>1 Dokaz druge Greenove identitete

\[ \varoiint \limits_{\partial \Omega}^{} u \frac{\partial v}{\partial \vec{n}}  \,\mathrm{d S} - \varoiint \limits_{\partial \Omega}^{} v \frac{\partial u}{\partial \vec{n}}  \,\mathrm{d S} = \varoiint \limits_{\partial \Omega}^{} \left( u \frac{\partial v}{\partial \vec{n}} - v \frac{\partial u}{\partial \vec{n}}   \right) \,\mathrm{d S}
\]

Dokaz: Razlika dveh integralov je enaka integralu razlik integrandov
*** <1>2

\[   \varoiint \limits_{\partial \Omega}^{} \left( u \frac{\partial v}{\partial \vec{n}} - v \frac{\partial u}{\partial \vec{n}}   \right) \,\mathrm{d S} = \iiint\limits_{\Omega}^{} \left( u \Delta v - v - \Delta u \right) \,\mathrm{d V}
\]

Dokaz: Upoštevamo 1. Greenovo identiteto.
*** <1>3 Dokaz prve Greenove identitete
Case 1: \(  \vec{F} = u \Delta v = u \cdot \left( v_x, v_y, v_z \right) \)

\[ \mathrm{div} \vec{F} = \left\langle \nabla u, \nabla v \right\rangle + u  \Delta v
\]

Dokaz: definicija divergence in verižno pravilo, ter \(  \Delta = \nabla ^2 \)
*** <1>4

\[ \iiint\limits_{\Omega}^{} \left( u \Delta v + \left\langle \nabla u, \nabla v \right\rangle \right) \,\mathrm{d V} = \iint\limits_{\partial \Omega}^{} \vec{F} \,\mathrm{d } \vec{S}
\]

Dokaz: Gaussova formula
*** <1>5

\[ \iint\limits_{\partial \Omega}^{} \vec{F} \,\mathrm{d } \vec{S} = \iint\limits_{\partial \Omega}^{} \left\langle \vec{F}, \vec{n} \right\rangle \,\mathrm{d S}
\]

Dokaz: Definicija integrala vektorskega polja
*** <1>6

\[ \iint\limits_{\partial \Omega}^{} \left\langle u \nabla v, \vec{n} \right\rangle \,\mathrm{d S} = \iint\limits_{\partial \Omega}^{} u \left\langle \nabla v, \vec{n} \right\rangle \,\mathrm{d S}
\]

Dokaz: \(  u \) je skalarna funkcija in se jo lahko izpostavi
*** <1>7

\[ \iint\limits_{\partial \Omega}^{} u \left\langle \nabla v, \vec{n} \right\rangle \,\mathrm{d S} = \iint\limits_{\partial \Omega}^{} u \frac{\partial v}{\partial \vec{n}}  \,\mathrm{d S}
\]

Dokaz:
**** <2>1
Vir:[[https://tutorial.math.lamar.edu/classes/calciii/directionalderiv.aspx][Directional derivati (slo. smerni odvod)]]
Case 1: točka \(  \vec{v} = (x_0, y_0, z_0) \in \mathbb{R} ^3 \)
Case 2: \(  u(x, y, z): \mathbb{R} ^2 \to \mathbb{R} \) zvezna realna funkcija, definirana v okolici točke \(  \vec{v} \)
Case 3: \(  \vec{a} = (a, b, c) \in \mathbb{R} ^3 \) enotski vektor, \(  \left| a \right|  = 1 \)

Definiramo /smerni odvod/ funkcije \(  u \) v točki \(  \vec{v} \) v smeri vektorja \(  \vec{a} \):

\[ \frac{\partial u}{\partial \vec{a}} \left( \vec{v} \right) = \lim_{h \to 0} \frac{u \left( \vec{v} + h \vec{a} \right) - u(\vec{v})}{h} = \lim_{h \to 0} \frac{u(x + ha, y + bh, z + ch)}{h}
\]
**** <2>2

Smerni odvod definiramo tudi kot

\[ \frac{\partial u}{\partial \vec{a}} \left( \vec{v} \right) = \left\langle \nabla u, \vec{a} \right\rangle
\]
Dokaz:
***** <3>1
Case 4: \(  x_0, y_0, z_0, a, b, c\) so konstante
Case 5: funkcija ene spremenljivke \(  g(t) = u(x_0 + ta, y_0 + tb, z_0 + tc) = u(x, y, z) \)

Velja

\[ g'(t) = \lim_{h \to 0} \frac{g(t + h) - g(t)}{h}
\]


***** <3>2

Za \(  t = 0 \) velja

\[ g'(0) = \lim_{h \to 0} \frac{g(h) - g(0)}{h} = \lim_{h \to 0} \frac{u(x_0 + ah, y_0 + bh, z_0 + ch) - u(x_0, y_0, z_0)}{h} = \frac{\partial u}{\partial \vec{a}} (x_0, y_0, z_0)
\]

Dokaz: definicija odvoda ene spremenljivke <3>1, definicija Case 5, ter <2>1

***** <3>3

Velja

\[ g'(t) = \frac{\mathrm{d} }{\mathrm{d} t} g = \frac{\partial u}{\partial x} \cdot \frac{\partial x}{\partial t} + \frac{\partial u}{\partial y} \cdot \frac{\partial y}{\partial t} + \frac{\partial u}{\partial z} \cdot \frac{\partial z}{\partial t} = u_x \cdot a + u_y \cdot b + u_z \cdot c
\]

Dokaz: Case 5 in verižno pravilo
***** <3>4

Za \(  t = 0 \) velja

\[ g'(0) = u_x (x_0, y_0, z_0) \cdot a + u_y (x_0, y_0, z_0) \cdot b + u_z (x_0, y_0, z_0) \cdot c
\]

Dokaz: \(  t = 0 \) za <3>3
***** <3>5 QED

\[ \frac{\partial u}{\partial \vec{a}} \left( \vec{v} \right) = \left\langle \nabla u, \vec{a} \right\rangle
\]

Dokaz: Izenačimo <3>4 in <3>2
**** <2>3 QED

Dokaz: <2>2
*** <1>8 QED

Dokaz: <1>6 in <1>7
* Cauchyjev problem (Initial value problem)

Eksplicitna diferencialna enačba prvega reda oblike \(  y' = f(x,y) \) s podanimi začetnimi, robnimi pogoji \(  y_0 = y(x_0) \), kjer so \(  f, x_0, y_0 \) podani.
* Eulerjeva metoda

Imamo Cauchyjev problem.
** <1>1
Case 1: \(  x \in \mathbb{R} \)
Case 2: \(  x > x_0 \)

Interval \(  [x_0, x] \) razdelimo na \(  n \) delov:

\[ x_0 < x_1 < x_2 < \ldots < x_n = x
\]
** <1>2

\[ x_j = x_0 + \frac{x - x_0}{n} j = x_0 + h j
\]

Dokaz: <1>1
** <1>3

Imamo nov Cauchyjev problem

\begin{align*}
  y' &= f(x, y) \\
y_1 &= y(x_1)
\end{align*}

Dokaz:

Za majhne \(  h \) (velike \(  n \)) je \(  y(x_1) \) blizu vrednosti tangente \(  y'(x_1) \).
** <1>4

Po \(  n \) korakih

\[ y(x_n) = y(x)
\]
** <1>5
Case 3: \(  Y = y_j \)
Case 4: \(  X = x_j \)

Tangenta skozi \(  (x_{j - 1}, y_{j -1}) \) z naklonom \(  f(x_{j -1}, y_{j -1}) \) je

\[ Y - y_{j -1} = f(x_{j -1}, y_{j -1}) \left( X -x_{j-1} \right)
\]

Dokaz: definicija tangente
** <1>6

Na koncu dobimo

\begin{align*}
  x_j &= x_{j - 1} + h \\
y_j &= y_{j - 1} + f(x_{j - 1}, y_{j - 1})h
\end{align*}
* Enačba z ločljivimi spremenljivkami

Enačbe oblike

\[ y' = P(x) \cdot Q(y)
\]
** What to do?

Funkcijo preoblikujemo

\[ \frac{y'}{Q(y)} = P(x)
\]

in rešimo

\begin{align*}
  \int\limits_{}^{} \frac{1}{Q(y)} \,\mathrm{d y} &= \int\limits_{}^{} P(x) \,\mathrm{d x} \\
F(y) &  = G(x)
\end{align*}
* Linearne diferencialne enačbe

Linearna diferencialna enačba (LDE) prvega reda je enačba oblike

\[ y' + py = q
\]

kjer sta \(  p, q \) dani integrabilni funkciji, \(  y \) pa iščemo.
* Trditev 7.6

Rešitve za \(  y \) so /afin/ prostor (linearno premaknjene rešitve). Če je \(  y_0 \) poljubna rešitev, in je \(  R \) prostor vseh rešitev za LDE, tedaj je

\[ R - y_0 = \left\{ y - y_0;\ y \in R \right\}
\]
** Dokaz
*** <1>1
Case 1: Diferencialni operator \(  \mathrm{L} \): \(  Ly = y' + py \)
/Opomba/: Operator je funkcija, ki vzame funkcijo in jo pretvori v neko novo funkcijo.
Case 2: \(  y_1, y_2 \in R - y_0 \)
Case 3: \(  Ly = q \)

Vektorski prostor je zaprt za seštevanje.

Dokaz:
**** <2>1

\[ y_1 + y_2 \in R - y_0 \iff y_0 + y_1 + y_2 \in R
\]

Dokaz:
***** <3>1

\[ L \left( y_1 + y_2 + y_0 \right) = L \left( \left( y_0 + y_1 \right) + \left( y_0 + y_2 \right) - y_0 \right)
\]
***** <3>2

\[   L \left( \left( y_0 + y_1 \right) + \left( y_0 + y_2 \right) - y_0 \right) = L \left( y_0 + y_1 \right) + L \left( y_0 + y_2 \right) - L \left( y_0 \right)
\]

Dokaz: Operator \(  L \) je linearen.
***** <3>3

\[ L \left( y_0 + y_1 \right) + L \left( y_0 + y_2 \right) - L \left( y_0 \right) = q + q - q
\]

Dokaz: Case 2 se lahko spremeni v \(  y_1 + y_0, y_2 + y_0 \in R \)
**** <2>2 QED
*** <1>2

Vektorski prostor je zaprt za množenje s skalarjem.

Dokaz:
**** <2>1
Case 4: \(  \lambda \in \mathbb{R} \)

\[ \lambda y_0 \in R
\]

Dokaz: ker je \(  y_0 \in R \)
**** <2>2

\[ \lambda y_1 \in R - y_0
\]

Dokaz:

\[ L(\lambda y_1) = \lambda Ly_1
\]
**** QED
*** <1>3 QED
* Posledica 7.7

Prostor \(  R \) vseh rešitev za LDE lahko zapišemo kot

\[ R = y_0 + \left\{ h; \mathrm{L}h = 0 \right\}
\]

\(  y_0 \) je partikularna rešitev, množica v oklepaju pa rešitev pripadajoče homogene enačbe.
** What to do?

Želimo odvod produkta

\begin{equation}
\label{eq:2}
 \left( y g \right) ' = y'g + g' y = q
\end{equation}

kjer je \(  g \) nepoznana funkcija.

Z upoštevanjem \ref{eq:2} dobimo LDE

\[ y' + p y = q \implies y' + py = y' g + g' y
\]

Enačbo pomnožimo z \(  m \) in primerjamo koeficienti z istimi \(  y \) in dobimo

\begin{align*}
  m &= g \\
mpy = g' y  & \implies mp = m'
\implies p = \log \left| m \right|  = p
\end{align*}

Tako dobimo

\[ m(x) = e^{\int\limits_{x_0}^x p \left( \xi \right) \,\mathrm{d } \xi}
\]

Ter iz \(  \left( y'm \right) = qm \) dobimo

\[ y(x) = \frac{1}{m(x)} \int\limits_{x_0}^x q \left( \eta \right) \cdot m \left( \eta \right) \,\mathrm{d } \eta
\]

Če sta \(  x_0 \) pri \(  m(x) \) in \(  y(x) \) enaka, potem vpeljemo konstanto \(  C \)

\[ y(x) = \frac{1}{m(x)} \int\limits_{x_0}^x q \left( \eta \right) \cdot m \left( \eta \right) \,\mathrm{d } \eta  + \frac{C}{m(x)}
\]
* Izrek

Splošna rešitev LDE \(  y' + py = q \) se glasi

\[ y(x) = Ce^{-P(x)} + e^{-P(x)} \int\limits_{x_0}^x q \left( s \right) e^{P(s)} \,\mathrm{d s}; \ C \in \mathbb{R}
\]

kjer je \(  P(x) = \int\limits_{x_0}^x p( \left( \xi \right) ) \,\mathrm{d \xi} \) in je \(  x_0 \) poljubna točka na intervalu, na katerem je \(  p \) definiran.
* Bernoullijeva DE

Je DE oblike

\[ y' + py = qy^{\alpha}
\]

kjer sta \(  p, q \) dani funkciji in \(  \alpha \in \mathbb{R} \) dan.
** What to do?

Z \(  \alpha = 1 \) dobimo homogeno LDE, za \(  \alpha \) imamo LDE.

Delimo z \(  y^{\alpha} \) in uvedemo novo spremenljivko \(  z = y^{1 - \alpha} \).

Dobimo

\[ z' + \left( 1 - \alpha \right) pz = \left( 1 - \alpha \right) q
\]

kar pa je LDE, ki jo znamo rešiti.
* Riccatijeva diferencialna enačba

Enačba oblike

\[ y' = ay ^2 + by + x
\]

kjer so \(  a, b, c \) podane funkcije in \( a \ne 0 \). Če je \(  c = 0 \), imamo Bernoullijevo enačbo.
** What to do?

Uganemo prvo rešitev \(  y_1 \), potem splošno rešitev dobimo s substitucijo \(  y = z + y_1 \).

\[ z' + y'_1 = a \left( x ^2 + 2azy_1 + y_1 \right) + b (z + y_1) + c
\]

Velja \(  y_1' = a y_1 ^2 + by_1 + c \) in dobimo:

\[ z' = az ^2 + \left( 2azy_1 + b \right)z
\]

kar pa je Bernoullijeva enačba.
* Singularne rešitve
Obravnavamo enačbo \(  y' = f(x, y) \). Splošna rešitev ima obliko \(  y = \psi (x, C), \ x \in J, \ C \in \mathcal{C} \subset \mathbb{R} \), kjer je \(  \mathcal{C} \) množica parametrov.
* Definicija (Singularne točke)

Točkam iz \(  \mathbb{R} ^2 \) skozi, katere gre več rešitev enačbe \(  y' = f(x, y) \) pravimo singularne točke.

/Opomba/: Če je \(  T(x_0 , y_0) \) singularna točka in sta \(  y_1 \) in \(  y_2 \) dve različni rešitvi enačbe \(  y' = f(x, y) \), ki gre skozi \(  T \), tedaj imata \(  y_1, y_2 \) v točki \(  x_0 \) enaka odvoda.
*** Kdaj ima LDE singularno točko?

Splošna rešitev je oblike \(  y = C \phi(x) + \psi (x) \) za neki funkciji \(  \phi \) in \(  \psi \) ter poljuben \(  C \in \mathbb{R} \).

Velja za \(  C_1 \ne C_2 \)

\begin{align*}
 y_1 &= C_1 \phi (x) + \psi(x) \\
y_2 &= C_2  \phi (x) + \psi(x)
\end{align*}

Poleg tega, da v točki \(  T \) velja \(  y_1(x_0) = y_2 (x_0) = y_0 \), velja tudi, da sta odvoda enaka:

\begin{align*}
  y_1 '(x_0 ) &= y_2 ' (x_0) \\
C_1 \phi' (x_0) + \psi'(x_0) &= C_2 \phi '(x_0) + \psi'(x_0) \\
C_1 \phi'(x_0) &= C_2 \phi'(x_0)\\
\implies \phi'(x_0) = 0
\end{align*}
** Ovojnica/singularna rešitev 

Splošna rešitev je oblike

\[ y = \psi(x, C); x \in J, C \in \mathcal{C} \subset \mathbb{R}
\]

Če odvajamo splošno rešitev za \(  \psi = \psi(u, v) \):

\begin{equation}
\label{eq:3}
y' = \frac{\partial \psi}{\partial u} \frac{\partial x}{\partial x} + 0
\end{equation}

saj je \(  C \) konstanta.

Singularna rešitev je, če obstaja podana z zahtevo, da v vsaki točki seka kakšno izmed krivulj \(  y = \psi(x, C) \) in da je nanjo tangentna. Graf singularne rešitev je ovojnica grafov splošne rešitve, ki bo imela obliko \(  \phi (x) = \psi(x, C(x)) \).

Za \(  \psi = \psi(u, v) \) sledi:

\begin{equation}
\label{eq:4}
 \phi'(x) = \frac{\partial \psi}{\partial u} \cdot \frac{\partial x}{\partial x} + \frac{\partial \psi}{\partial v} \cdot \frac{\partial C(x)}{\partial x}
\end{equation}

Vemo, da singularna rešitev \(  y = \phi(x) \) in splošna rešitev \(  y = \psi(x, C) \) rešita enačbo \(  y' = f(x, y) \).  Vemo tudi, da je odvod \ref{eq:4} singularne rešitve enak odvodu \ref{eq:3} splošne rešitve v \(  x_0 \in J \), ki je konstantna. Odvoda \(  \psi_u \) se pokrajšata med sabo, ko enačimo odvoda in dobimo pogoj, da je

\begin{equation}
\label{eq:5}
 \frac{\partial \psi}{\partial v} (x, C(x)) C'(x) = 0
\end{equation}

Ker je singularna rešitev ovojnica splošnih rešitev, to pomeni, da funkcija \(  C \) mora biti odvisna od \(  x \). Nadalje to pomeni, da odvod funkcije \(  C \) ne sme biti enak \(  0 \), saj bi to pomenilo, da je \(  C \) konstanta.

Edini način, da je \ref{eq:5} enaka \(  0 \), je, da

\[ \frac{\partial \psi}{\partial v} = 0
\]

Preko te enačbe lahko izračunamo \(  C = C(x) \) in posledično dobimo enačbo singularne rešitve \(  y = \phi(x) \).
* Clairautova diferencialna enačba
To je enačba oblike

\[ y' = xy' + f(y')
\]

kjer je \(  f \) odvedljiva na odprtem intervalu \(  J \subset \mathbb{R} \).
* Trditev 7.18

Splošna rešitev Clairautove diferencialne enačbe je podana s formulo

\[ y = Cx + f(C)
\]

za \(  C \in J \).

Singularna rešitev je podana z

\begin{align*}
  x &= - f'(t) \\
y &= - f'(t) t + f(t), t \in J
\end{align*}

kar je parametrični zapis krivulje.
** Dokaz:
*** <1>1

Velja

\[ 0 = \frac{\partial y}{\partial C}
\]

Dokaz: Definicija singularne rešitve.
*** <1>2

\[ 0 = x + f' (C) \implies x = - f' (C)
\]

Dokaz: <1>1 in odvod splošne rešitve Clairautove enačbe.
*** <1>3

\[ y = - f'(C) C + f(C)
\]

Dokaz: <1>2 in pa definicija splošne rešitve Clairautove enačbe.
* Definicija 7.8

Predpostavke:
- \(  F: \mathbb{R} \times \mathbb{R} = S \to \mathbb{R} \)
- \(  \alpha \in \mathbb{R} \)

Pravimo, da je funkcija \(  F \) homogena reda \(  \alpha \), če za vsak par \(  x, y \in S \) in za vsak \(  t > 0 \) velja

\[ F(tx, ty) = t^{\alpha} F(x, y)
\]
* Definicija 7.9

Homogena diferencialna enačba je enačba oblike

\[ y' = f(x, y)
\]

kjer je \(  f \) homogena funkcija reda \(  0 \), torej \(  f(x, y) = f \left( 1, \frac{y}{x} \right) \), če \(  x \ne 0 \).
** What to do?

Z vpeljavo \(  z = \frac{y}{x} \) dobimo rešitev

\[ F(z) = \log \left| x \right|  + C
\]
* Definicija 7.11 (Prvi integral)

Prvi integral DE  \(  F(x, y, y') =0 \) je takšna funkcija \(  u = u(x, y) \), da za vsako rešitev \(  y(x) \) velja

\[ \frac{\mathrm{d} }{\mathrm{d}x } u(x, y(x)) = 0
\]

oz. \(  u(x, y(x)) = C \) za neki \(  C \in \mathbb{R} \).
* Definicija 7.13

Enačbi

\[ P \, \mathrm{dx } + Q \, \mathrm{dy } = 0
\]

kjer je \(  P_y = Q_x \) pravimo eksaktna.
* Implicitno podane DE
Rešitve poiščemo parametrični obliki:

\begin{align*}
  x &= x(t) \\
y &= y(t); t \in I
\end{align*}

Ter oznake

\[ \dot{x} = \frac{\mathrm{d} x}{\mathrm{d} t} \quad \dot{y} = \frac{\mathrm{d} y}{\mathrm{d} t} \quad y' = \frac{\mathrm{d} y}{\mathrm{d} x}
\]

In pa zaradi verižnega pravila velja

\[ y' = \frac{\dot{y}}{\dot{x}}
\]

** Primer \(  F(x, y') = 0 \)

Primer, ki ga rešujemo \(  (x, y') \) leži na nivojnici \(  \left\{ F = 0 \right\} \). Nivojnico parametriziramo z \(  \left( \psi(t), \theta(t) \right), \ t \in J \).

To pomeni, da je \(  (x, y') = \left( \psi(t), \theta(t) \right) \).

Z upoštevanjem zgornjih oznak dobimo

\[ \dot{y} = y' \cdot \dot{x} = \theta(t) \cdot \dot{\psi}(t)
\]

in posledično je rešitev

\[ y(t) = \int\limits_{}^{} \dot{\psi} \cdot \theta \,\mathrm{d t}
\]
** Primer \(  F(y,y') = 0 \)

To pomeni \(  \left( y, y' \right) = \left( \psi(t), \theta(t) \right) \).

\[ \dot{x} = \frac{\dot{y}}{y'} = \frac{\dot{\psi}}{\theta}
\]

in posledično je rešitev

\[ x(t) = \int\limits_{}^{} \left( \frac{\dot{\psi}}{\theta} \right) \,\mathrm{d t} \quad y(t) = \psi (t)
\]
* Diferencialne enačbe višjih redov

Diferencialna enačba višjega reda je v splošnem podana kot

\[ F(x, y, y', y'', \ldots, y^{(n)}) =0
\]
** 1. možnost

\[ F(x, y^{(k)}, y^{k + 1}) = 0
\]

kjer vpeljemo \(  z = y^{(k)} \) in rešimo NDE.
** 2. možnost

\[ F(y, y') = 0
\]

torej \(  x \) ne nastopa direktno. Potem \(  y' = z(y) \) in \(  y'' = z'(y) y = zz' \)
** 3. možnost

Podano imamo eksplicitno enačbo reda \(  n \):

\begin{equation}
\label{eq:6}
 y^{(n)} = f(x, y, y', \ldots, y^{(n -1)})
\end{equation}

ki jo lahko zapišemo kot sistem diferencialnih enačb

\begin{align*}
  z_1' &= z_2 \\
z_2 ' &= z_{3} \\
z_3 ' &= z_4 \\
&\vdots \\
z_n' &= f(x, z_1, \ldots, z_n)
\end{align*}

s prehodom \(  z_j = y^{(j-1)} \) za \(  j = 1, \ldots, n \)
*** Trditev 7.20

Definirajmo

\[ \vec{N}(y) = \begin{bmatrix} y \\ y' \\ \vdots \\ y^{(n-1)} \end{bmatrix} = \begin{bmatrix} z_1 \\ z_2 \\ \vdots \\ z_n  \end{bmatrix}
\]

Tedaj je funkcija \(  \vec{N}: \left\{ \text{resitve za \ref{eq:6}} \right\} \to \left\{ \text{resitve za sistem DE } \right\}  \) bijektivna.
**** Dokaz
Dokazujemo injektivnost v obe smeri.
***** <1>1
Predpostavka 1:  \(  y \) reši enačbo \ref{eq:6}

Velja:

\[ \begin{bmatrix} z_1 \\ z_2 \\ \vdots  \\ z_n \end{bmatrix} = \vec{N}(y)
\]

Dokaz:
Definicija prehoda \(  z_j = y^{(j - 1)} \) velja

\begin{align*}
  z_1 ' &= y' = z_2 \\
z_2 ' &= y'' = z_3 \\
& \vdots \\
z_{n-1}' &= y^{(n -1)} = z_n \\
z_n ' &= y^{(n)} = f(x, y, y', \ldots, y^{(n -1)}) = f(x, z_1, \ldots, z_n)
\end{align*}
***** <1>2
Predpostavka 2:

\[ \begin{bmatrix} z_1 \\ z_2 \\ \vdots \\ z_n \end{bmatrix} = \vec{N}(y)
\]

reši sistem enačb

\begin{align*}
  z_1' &= z_2 \\
z_2 ' &= z_{3} \\
z_3 ' &= z_4 \\
&\vdots \\
z_n' &= f(x, z_1, \ldots, z_n)
\end{align*}

Rešitev je injektivna.

Dokaz:

Velja \(  y = z_1 \), \(  y' = z_1' = z_2 \), itd. do \(  y^{(n -1)} = z_{n-1}' = y_n \) in \(  y^{(n)} = z_n ' = f(x, z_1, \ldots, z_n) = f(x, y, y', \ldots, y^{(n-1)}) \)
* Eksistenčni izrek za DE 1. reda
** Definicija 7.21

Naj bodo \(  x_0, y_0 \in \mathbb{R} \) ter \(  a, b > 0 \). Označimo \(  P = \left[ x_0 - a, x_0 + a \right] \times \left[ y_0 - b, y_0 + b \right] \subset \mathbb{R} \).
Funkcija \(  f = f(u, v): P \to \mathbb{R} \) je zvezna in enakomerno (neodvisna od parametra) Lipschitzova v 2. spremenljivki, če obstaja \(  \gamma > 0 \) tako, da velja \(  \left| f(u, v_1) - f(u, v_2) \right| \le \gamma \left| v_1 - v_2 \right|\) za vsak \(  \left( u, v_1 \right), \left( u, v_2 \right) \in P \). Če je funkcija enakomerno Lipschitzova, \(  \gamma \) ne sme biti odvisen od \(  u \), sicer je lahko.

/Opomba/: pri razliki funkcij \(  f \) vzamemo isti \( u  \), vendar različna \(  v \). Beseda enakomerna pa je notri, ker velja za vse \(  u \in \left[ x_0 - a, x_0 + a \right] \). Prav tako je pogoj izpolnjen, če velja \(  \left| \frac{\partial f}{\partial v} \le \gamma  \right| \) na \(  P \).
** Trditev 7.22 (eksistenčni izrek/ Picard-Lindelöf)

Predpostavke:
- \(  x_0, y_0 \in \mathbb{R} \)
- \(  a, b > 0 \)
- pravokotnik \(  P = \left[ x_0 - a, x_0 + a \right]\times \left[ y_0 - b, y_0 + b  \right] \)
- Funkcija \(  f = f(u, v): P \to \mathbb{R} \) je zvezna in enakomerno Lipschitzova v 2. spremenljivki

Cauchyjev problem

\begin{align*}
  y' (x) &= f(x, y)\\
y(x_0) &= y_0
\end{align*}

ima takrat natanko eno rešitev \(  y = y(x): I \to \left[ y_0 - b, y_0 + b \right] \), kjer je \(  I \subset \left[ x_0 - a, x_0 + a \right]   \)

Oznaka \(  c = \min \left\{ a, \frac{b}{M}, \frac{1}{\gamma} \right\} \), kjer je \(  M = \max_{x \in I} f \)
*** Dokaz:
**** <1>1

Zapis

\[ \int\limits_{x_0}^x y'(\xi) \,\mathrm{d }\xi = y(x) - y(x_0) = y(x) - y_0
\]

je enak Cauchyjevemu problemu.

Dokaz: Dobili smo ga z integriranjem CP problema, in z odvajanjem ga dobimo nazaj.
**** <1>2

Obstaja natanko ena zvezna funkcija \(  y: I \to \left[ y_0 - b, y_0 + b \right] \), ki reši

\[ y(x)  = y_0 + \int\limits_{x_0}^x f \left( \xi, y \left( \xi \right) \right) \,\mathrm{d } \xi
\]

Temu problemu rečemo CiP

Dokaz:
***** <2>1

Problem CiP zadošča rešiti na zaprtem intervalu \(  I\delta \).

/Opomba/: \(  I\delta \) je interval \(  I \) skrajšan za \(  \delta \) na vsaki strani.

Dokaz: ¯\_(ツ)_/¯
***** <2>2
Case 1: Fiksiramo \(  \delta (0, c) \).

Definiramo operator \(  F: y \mapsto F(y) \), kjer je \(  y \) funkcija, kot

\[ F(y):x \mapsto y_0 + \int\limits_{x_0}^x f\left( \xi, y \left( \xi \right)\right) \,\mathrm{d }\xi
\]
***** <2>3

Operatorju \(  F \) določimo definicijsko območje kot prostor \(  \mathcal{M} = \mathcal{M}_{\delta} \) vseh zveznih funkcij \(  I\delta \to \left[ y_0 - b, y_0 + b \right] \) z maksimum normo.

****** Maksimum norma

Metrika, ki poljubnima funkcijama \(  \phi, \psi \in \mathcal{M}  \) pripiše vrednost

\[ d(\phi, \psi) = \max_{x \in I\delta} \left| \phi(x) - \psi(x) \right|
\]
****** Definicija metrike

Naj bo \(  \mathcal{N} \) poljubna množica.

Preslikavi \(  d: \mathcal{N} \times \mathcal{N} \to \mathbb{R} \) pravimo /metrika/ na množici \(  \mathcal{N} \), če za vse elemente \(  x, y, z \in \mathcal{N} \) velja

a) \(  d(x, y) = d(y, x) \)
b) \(  d(x, z) \le d(x, y) + d(y, z) \)
c) \(  d(x, y) \ge 0 \)
d) \(  d(x, x) = 0 \)
e) če \(  x \ne y \), potem \(  d(x, y) > 0 \)
***** <2>4

Obstaja natanko eden \(  y \in \mathcal{M} \), da je

\[ F(y) = y = y_0 + \int\limits_{x_0}^x f \left( \xi, y \left( \xi \right) \right) \,\mathrm{d } \xi
\]

tl;dr je, da iščemo fiksno točko operatorja \(  F: \mathcal{M} \to \mathcal{M} \) - slika se iz \(  \mathcal{M} \to \mathcal{M} \), ker je \(  y \in \mathcal{M} \)

Dokaz:
****** Banachov izrek o fiksni točki

Predpostavke:
- \(  \mathcal{N} \) poln neprazen metrični prostor
- \(  f: \mathcal{N} \to \mathcal{N} \) skrčitev

Tedaj obstaja natanko ena točka \(  b \in \mathcal{N} \), za katero velja \(  f(b) = b \)
****** <3>1
Vir: [[https://math.stackexchange.com/questions/5015683/doubts-about-proof-that-c-a-b-with-metric-rhoxt-yt-max-limits?rq=1]]

Metrični prostor \(  \mathcal{M} \) je poln.

Dokaz:
******* Definicije

Metrični prostor \(  \mathcal{N} \) je poln, če je vsako Cauchyjevo zaporedje v \(  \mathcal{N} \) konvergentno.

Zaporedje \(  \left( a_k \right) \) v metričnem prostoru \(  \left( \mathcal{N}, d \right) \) je /Cauchyjevo/, če za vsako \(  \epsilon > 0 \) obstaja tako velik \(  N \in \mathbb{N} \), da za vsaki dve \( k,j > N; \  k, j \in \mathbb{N} \) velja \(  d(a_k, a_j) < \epsilon \).

Zaporedje v metričnem prostoru \(  \mathcal{N} \) je preslikava \(  \mathbb{N} \to \mathcal{N}, \ k \mapsto a_k \), ki jo običajno zapišemo kot \( \left( a_k \right)_{k \in \mathbb{N}} = \left( a_k \right) = \left( a_1, a_2, \ldots \right) \).
******* <4>1
Predpostavka 1: \(  \left( \phi_n \right)_{n \in \mathbb{N}} \) je Cauchyjevo zaporedje

Prove: Za vsak \(  x \in I\delta \) je \(  \left( x_n \right) \) Cauchyjevo.

Dokaz:

******** <5>1
Za vsak \(  \epsilon > 0 \) obstaja \(  N \in \mathbb{N} \), da za vsaka \(  j, k > N; \ j, k \in \mathbb{N}  \) velja

\[ d(\phi_n, \phi_m) < \frac{\epsilon}{2}
\]

Dokaz: Predpostavka 1, da je \(  \left( \phi_n \right)_{n \in \mathbb{N}} \) Caucyjevo zaporedje.

**V katerem primeru to ne bi veljalo?**
******** <5>2

Za vsak \(  x \in I\delta \) velja

\[ \left| \phi_n (x) - \phi_m (x)  \right| < d(\phi_n, \phi_m)
\]

Dokaz: <5>1
******** <5>3 QED

Za vsak \(  x \in I\delta \) velja

\[ \left| \phi_n - \phi_m \right| < \frac{\epsilon}{2}
\]

Dokaz: iz <5>1 in <5>2

******* <4>2

Prove:

Ko gre \(  n \to \infty \), gre enakomerno \(  \phi_n \to \phi \) na \(  I_{\delta} \)

Dokaz:
******** <5>1
Predpostavka: \(  \lim_{m \to \infty} \phi_m = \phi  \)

Za vsak \(  \epsilon > 0 \) obstaja \(  N \in \mathbb{N} \) tako, da za vsak \(  n > N \) velja

\[ \left| \phi_n - \phi \right| = \left| \phi_n - \lim_{m \to \infty} \phi_m  \right| \le \lim_{m \to \infty} \left| \phi_n - \phi_m \right| < \frac{\epsilon}{2} < \epsilon
\]

za vsak \(  x \in I\delta  \)

Dokaz: <4>1 velja
/Opomba/: Dokazali smo enakomerno konvergenco
******** <5>2

Za vsak \(  I\delta \) intervala je so \(  \phi \) zvezne.

Dokaz: <5>1 drži in \(  \phi_n \) so zvezne
******** <5>3 QED

Dokaz: \(  \phi \in \mathcal{M} \)

******* <4>3

Funkcija \(  \phi_n \) je zvezna.

Dokaz: Predpostavka <2>3, \(  \mathcal{M} \) je prostor vseh zveznih funkcij.

****** <3>2

\(  F: \mathcal{M} \to \mathcal{M} \) je skrčitev.

******* Definicija

- \(  \left( \mathcal{M}, d \right) \)
- \(  \left( \mathcal{M}', d' \right) \)

Preslikava \(  f: \mathcal{M} \to \mathcal{M}' \) je skrčitev, če obstaja takšna realna konstanta \(  q \), da je \(  0 \le q < 1 \) in da velja


\[ d'(f(x) , f(y)) \le q d(x, y)
\]

za vse točke \(  x, y \in \mathcal{M} \)
******* <4>1
Case 2: \(  \phi, \psi \in \mathcal{M} \) dve funkciji

Velja

\[ d \left( F \left( \phi \right), F \left( \psi \right) \right) = d \left( y_0 + \int\limits_{x_0}^x f(\xi, \phi(\xi)) \,\mathrm{d }\xi, y_0 + \int\limits_{x_0}^x f \left( \xi, \psi(\xi) \right) \,\mathrm{d }\xi \right)
\]

Dokaz: Definicija operatorja \(  F \) <2>2
******* <4>2

Velja

\[   d \left( y_0 + \int\limits_{x_0}^x f(\xi, \phi(\xi)) \,\mathrm{d }\xi, y_0 + \int\limits_{x_0}^x f \left( \xi, \psi(\xi) \right) \,\mathrm{d }\xi \right) = \max_{x \in I\delta} \left| \int\limits_{x_0}^x f \left( \xi, \phi(\xi) \right)  \,\mathrm{d }\xi - \int\limits_{x_0}^{x} f \left( \xi, \psi \left( \xi \right) \right) \,\mathrm{d }\xi  \right|
\]

Dokaz: Definicija metrike \(  d \) <2>3
******* <4>4

\[ \max_{x \in I\delta }  \left| \int\limits_{x_0}^x \left[ f \left( \xi, \phi(\xi) \right) - f \left(\xi,  \psi \left( \xi \right) \right) \right] \,\mathrm{d } \xi \right| \ge \left| \int\limits_{x_0}^x \left[ f \left( \xi, \phi(\xi) \right) - f \left( \xi, \psi \left( \xi \right) \right) \right] \,\mathrm{d } \xi \right|
\]

******* <4>5

\[  \left| \int\limits_{x_0}^x f \left( \xi, \phi(\xi) \right)  \,\mathrm{d }\xi - \int\limits_{x_0}^{x} f \left( \xi, \psi \left( \xi \right) \right) \,\mathrm{d }\xi  \right| \le \int\limits_{x_0}^x \left| f \left( \xi, \phi \left( \xi \right) \right) - f \left( \xi, \psi \left( \xi \right) \right) \right| \,\mathrm{d }\xi
\]

Dokaz: Glej integrale s parametrom
******* <4>6
Case 3: \( \gamma \in [0, 1]  \)

\[    \int\limits_{x_0}^x \left| f \left( \xi, \phi \left( \xi \right) \right) - f \left( \xi, \psi \left( \xi \right) \right) \right| \,\mathrm{d }\xi \le \int\limits_{x_0}^x \gamma   \left| \phi(\xi) - \psi \left( \xi \right) \right| \,\mathrm{d }\xi
\]

Dokaz: Definicija enakomerno Lipschitzove funkcije
******* <4>7

\[ \int\limits_{x_0}^x \gamma \left| \phi - \xi \right| \,\mathrm{d } \xi \le \int\limits_{x_0}^x \gamma \max_{x \in I\delta} \left| \phi \left( \xi \right) - \psi \left( \xi \right) \right| \,\mathrm{d } \xi
\]

Dokaz: absolutna razlika bo vedno manjša ali enaka od maksimalne razlike

******* <4>7

\[ \int\limits_{x_0}^x \gamma d \left( \phi, \psi \right) \,\mathrm{d }\xi = \left( x - x_0 \right) \gamma d \left( \phi, \psi \right)
\]

Dokaz: Definicija metrike ter osnovni izrek analize
******* <4>8

\[ \gamma d \left( \phi, \psi \right) \left( x - x_0 \right) \le \gamma \left| a - \delta \right| d \left( \phi, \psi \right)
\]

Dokaz:  Predpostavka 2, definicija pravokotnika \(  P \), kjer ima \(  x \) maksimalno vrednost \(  a  + x_0 \) in potem je na skrčitvi \( I\delta  \) \(  x_0 + a - \delta \).
******* <4>9 QED

Dokaz: Za \(  \delta < a \), vendar da bo \(  \delta \) dovolj blizu \(  a \), bo \(  \gamma \left| a - \delta \right| < 1 \) in po definicije skrčitve, bo \(  F \) skrčitev.
****** <3>3 QED

Dokaz: <3>1 in <3>2
***** <2>5 QED

Pogoji za Banachov izrek so dokazani, in ga lahko uporabimo. Obstaja fiksna točka. <2>4
**** <1>3 QED

Dokaz: <1>2 velja
* Trditev 7.25

Imamo sistem enačb \(  \vec{y}' = A \vec{y} + \vec{b} \), kjer so \(  \vec{y}', \vec{y}, \vec{b} \in \mathbb{R}^n \) ter \(  A \in \mathbb{R}^{n \times n} \), ki ga zapišemo kot

\begin{equation}
\label{eq:7}
\vec{y}' = A \vec{y} + \vec{b}
\end{equation}

Predpostavke:

- \(  \vec{y}_0 \) je neka vektorska funkcija, ki reši \ref{eq:7}

Tedaj velja

\[ \left\{ \text{resitve enačbe } \ref{eq:7} \right\} = \left\{ \text{resitve enacbe } \vec{y}' = A \vec{y} \right\} + y_0
\]
** Dokaz:
*** <1>1
Case 1: \(  \vec{y} \) je rešitev enačbe \(  \vec{y}' = A \vec{y} \)

\[ \left( \vec{y} + \vec{y}_0 \right)' = \vec{y}' + \vec{y}_0 '
\]

Dokaz: Odvod vsote je vsota odvodov
*** <1>2

\[ \vec{y}' + \vec{y}_0' = A \vec{y} + A \vec{y}_0 + \vec{b} = A \left( \vec{y} + \vec{y}_0 \right) + \vec{b}
\]

Dokaz: enakosti v predpostavki v trditvi in Case 1
*** <1>3

\[ \vec{y} + \vec{y}_0
\]

je rešitev enačbe \[ \vec{z}' = A \vec{z} + \vec{b}
\]

Dokaz: <1>2
*** <1>4
Case 2: \(  \vec{y} \) je rešitev \(  \vec{y}' = A \vec{y} + \vec{b} \)

\[ \left( \vec{y} - \vec{y}_{0} \right) ' = A \vec{y} + \vec{b} - A \vec{y}_0 - \vec{b} = A  \left( \vec{y} - \vec{y}_0 \right)
\]

Dokaz: odvod razlike je razlika odvodov ter enakost predpostavke v trditvi in Case 2
*** <1>5

\[ \left( \vec{y} -  \vec{y}_0 \right)
\]

reši homogeno enačbo

Dokaz: <1>4
*** <1>6 QED

Dokaz: <1>3 ter <1>5
* Izrek 7.26

Predpostavke:
- \(  J \subseteq \mathbb{R} \) omejen odprt interval
- \(  A: \bar{J} \to \mathbb{R}^{n \times m} \) matrična funkcija z zveznimi koeficienti
Za \(  x_0 \in J \) in \(  \xi_0 \in \mathbb{R} ^n \) obstaja natanko ena rešitev sistema

\[ \vec{y}' = A \vec{y}, \ \vec{y} (x_0) = \xi_0
\]

ki je definirana *povsod* na \(  J \).

/Opomba/: Pri LDE so samo *nekje* na \(  J \).
* Izrek 7.27 (variacije konstante)
** Fundamentalna matrika

Homogene rešitve sistema \(  \vec{y}' = A \vec{y} \) tvorijo \(  n \) dimenzionalen vektorski prostor. Tedaj lahko izberemo linearno neodvisne rešitve \(  \vec{y}_1, \vec{y}_2, \ldots, \vec{y}_n \) za homogen sistem in tvorimo fundamentalno matriko

\[ \underline{Y} = \left[ \vec{y}_1 \vec{y}_2 \ldots \vec{y}_n\right]
\]

in velja \(  \underline{Y}' = A \underline{Y} \)
** Variacija konstante

Predpostavka:

- \(  \underline{Y} \) je fundamentalna matrika sistema \(  \vec{y}' = A \vec{y} \)

Potem je vektorska funkcija

\[ \vec{y}_p = \underline{Y} \int\limits_{}^{} \underline{Y}^{-1} \vec{b} \,\mathrm{d x}
\]

rešitev sistema \(  \vec{y}' = A \vec{y} + \vec{b} \)
*** Dokaz:
**** <1>1

\[ \vec{y}_p ' =  \left( \underline{Y}\int\limits_{}^{} \underline{Y}^{-1} \vec{b} \,\mathrm{d x} \right) '
\]

Dokaz: Trditev
**** <1>2

\[ \left( \underline{Y} \int\limits_{}^{} \underline{Y}^{-1} \vec{b} \,\mathrm{d x} \right)' =  \left( \underline{Y} \right)' \int\limits_{}^{} \underline{Y}^{-1} \vec{b} \,\mathrm{d x} +  \underline{Y} \left( \int\limits_{}^{} \underline{Y}^{-1}\vec{b} \,\mathrm{d x}\right) '
\]

Dokaz: odvod produkta
**** <1>3

\[   \left( \underline{Y} \right)' \int\limits_{}^{} \underline{Y}^{-1} \vec{b} \,\mathrm{d x} +  \underline{Y} \left( \int\limits_{}^{} \underline{Y}^{-1}\vec{b} \,\mathrm{d x}\right) ' = A\underline{Y} \int\limits_{}^{} \underline{Y}^{-1} \vec{b} \,\mathrm{d x} + \underline{Y} \underline{Y}^{-1} \vec{b}
\]

Dokaz:

Velja \(  \underline{Y}' = A \underline{Y} \) ter \(  \left( \int\limits_{}^{} \underline{Y}^{-1} \vec{b} \,\mathrm{d x} \right)' = \underline{Y}^{-1} \vec{b} \)
**** <1>4 QED

\[  A\underline{Y} \int\limits_{}^{} \underline{Y}^{-1} \vec{b} \,\mathrm{d x} + \underline{Y} \underline{Y}^{-1} \vec{b}  = A \left( \underline{Y} \int\limits_{}^{} \underline{Y}^{-1} \vec{b} \,\mathrm{d x} \right) + \vec{b} = A \vec{y}_p + \vec{b}
\]

Dokaz: \(  \underline{Y} \underline{Y}^{-1} = 1 \) ter trditev
* Definicija 7.28

Predpostavke:
- \(  I \subset \mathbb{R} \) je odprt interval
- \(  \vec{y}_1, \vec{y}_2, \ldots, \vec{y}_n \) so \(  n \) razsežne vektorske funkcije na \(  I \) oz. \(  \vec{y}_j: I \to \mathbb{R}^{n} \)
Za fundamentalno matriko \(  \underline{Y} = \left[ \vec{y}_1 \vec{y}_2 \ldots \vec{y}_n \right]: I \to \mathbb{R}^{n \times n} \) se

\[ W = \det \underline{Y}
\]

imenuje determinanta Wrónskega.
* Izrek 7.29 (Liouvilleova formula)
Predpostavke:
- \(  \underline{Y}: I \to \mathbb{R}^{n \times n} \) matrična funkcija, ki reši enačbo \(  \underline{Y}' = A \underline{Y} \)

Za \(  W = \det \underline{Y} \) velja

\[ W(x) = W (x_0) e^{\int\limits_{x_0}^x \mathrm{tr} A \left( \xi \right) \,\mathrm{d } \xi}
\]
** Dokaz za \(  n = 2 \):
*** <1>1
Case 1:

\[ \underline{Y} = \begin{bmatrix}
y_{11 } & y_{12} \\
y_{21} & y_{22}
\end{bmatrix}
\]

Case 2:

\[ A = \begin{bmatrix}
a_{11 } & a_{12} \\
a_{21} & a_{22}
\end{bmatrix}
\]

Velja

\[ \underline{Y}' = A \underline{Y}  \implies \begin{bmatrix}
y_{11 }' & y_{12}' \\
y_{21}' & y_{22}'
\end{bmatrix}  = \begin{bmatrix}
y_{11 } & y_{12} \\
y_{21} & y_{22}
\end{bmatrix} \cdot \begin{bmatrix}
a_{11 } & a_{12} \\
a_{21} & a_{22}
\end{bmatrix}
\]

Dokaz: Predpostavka trditve
/Opomba/: Dobili smo sistem enačb
*** <1>2

\[ W = \det \underline{Y} = y_{11 } y_{22} - y_{12} y_{21}
\]

Dokaz: definicija determinante
*** <1>3

\[ W' = y_{11 }' y_{22} + y_{11 } y_{22 }' - y_{12}' y_{21} - y_{12} y_{21}'
\]

Dokaz: Odvod produkta
*** <1>4

\[ W' = \left( a_{11 } + a_{22} \right) \left( y_{11 }y_{22} - y_{12} y_{21} \right) = \mathrm{tr} A \det \underline{Y}
\]

Dokaz: Upoštevamo sistem enačb iz <1>1 ter <1>2 in definicija sledi
\[ \mathrm{sl} A= \mathrm{tr }A = \sum\limits_{i = 1}^n b_{ii}
\]
*** <1>5 QED

Integracija <1>3 nam da

\[ W(x) = W(x_0) e^{\int\limits_{x_0}^x \mathrm{tr} A \left( \xi \right) \,\mathrm{d }\xi}
\]
* Definicija 7.31
Če je \(  A: J \to \mathbb{R}^{n \times n} \) matrična funkcija z zveznimi koeficienti, definiramo njeno normo kot \(  \lVert A \rVert = \sup_{u \in J} \left| A(u) \right|\), kjer je slednje operatorska norma matrike A.

Veljajo lastnosti za normo:

- \(  \left\lVert B \right\rVert \le 0 \) in \(  \left\lVert B \right\rVert  = 0 \iff B = 0 \)
- \(  \left\lVert \alpha B \right\rVert = \left| \alpha \right| \left\lVert B \right\rVert\) za vse \(  \alpha \in \mathbb{R} \) ter \(  B \in \mathbb{R}^{n \times n} \)
- trikotniška neenakost \(  \left\lVert A + B \right\rVert \le \left\lVert A \right\rVert + \left\lVert B \right\rVert\)
Ter ekstra stvari:
- \(  \left\lVert B\epsilon \right\rVert \le \left\lVert B \right\rVert \left| \epsilon \right|\) za vsak \(  B \in \mathbb{R} ^{n \times n} \) in vsak \(  \epsilon \in \mathbb{R}^{n} \)
- \(  \left\lVert A B \right\rVert \ge \left\lVert A \right\rVert \left\lVert B \right\rVert\) za vse \(  A, B \in \mathbb{R} ^{n\times n} \)

Norma prav tako definira metriko

\[ d (A, B) = \left\lVert A - B \right\rVert
\]

Za dano metriko \(  d \) je \(  \mathbb{R}^{n \times n} \) poln metričen prostor.
* Posledica 7.32

Za poljubna \(  u \in \tilde{J} \) in vektor \(  \vec{\xi} \in \mathbb{R}^n \) velja

\[ \left| A(u) \vec{\xi} \right| \le \left\lVert A \right\rVert \left| \vec{\xi} \right
\]
* Definicija 7.33

Naj bo \(  f(x) = e^x \). Za \(  B \in \mathbb{R} ^{n \times n} \) definiramo

\[ e^B = \sum\limits_{j = 0}^{\infty} \frac{B^j}{j!}
\]
** Trditev

Vrsta

\[ e^B = \sum\limits_{j = 0}^{\infty} \frac{B^j}{j!}
\]

konvergira.
*** Dokaz:
**** <1>1
Case 1: \(  s_n  \sum\limits_{j = 0}^{n} \frac{B^j}{j!} \)

Zaporedje \(  \left( s_n \right)_n \) je Cauchyjevo.

Spomnimo se: Za vsak \(  \epsilon > 0 \) obstaja tako velik \(  N \in \mathbb{N} \), da za vsaki števili \(  m, n > N; \ m, n \in \mathbb{N} \) velja \(  d(s_m, s_n) < \epsilon \)
Dokaz:
***** <2>1
Case 2: \(  m > n \)

\[ \left\lVert s_m - s_n \right\rVert = \left\lVert \sum\limits_{j = 0}^m \frac{B^j}{j!} - \sum\limits_{j = 0}^n \frac{B^j}{j!} \right\rVert
\]

Dokaz: definicija zaporedja.
***** <2>2

\[ \left\lVert \sum\limits_{j = n + 1}^m \frac{B^j}{j!} \right\rVert  \le \sum\limits_{j = n + 1}^m \frac{\left\lVert B^j \right\rVert}{j!}
\]

Dokaz: Vsoti v <2>1 se odštejeta in je tisto na levi strani, kar ostane ter neenakost
***** <2>3
\[  \sum\limits_{j = n + 1}^m \frac{\left\lVert B^j \right\rVert}{j!} \le \sum\limits_{j = n + 1}^{m} \frac{\left\lVert B \right\rVert^j}{j!}
\]

Dokaz: ponovno neenakost
***** <2>4

\[ \sum\limits_{j = n + 1}^m \frac{\left\lVert B \right\rVert^j}{j!}
\]

konvergira k 0, ko gresta \(  m, n \to \infty \)

Dokaz:

Taylorjeva vrsta \(  f(x) = e^x = \sum\limits_{j = 0}^{\infty} \frac{x^j}{j!} \) konvergira povsod na \(  \mathbb{R} \). Dana vsota je številska vrsta za \(  x = \left\lVert B \right\rVert \).
***** <2>5 QED

Zaradi <2>4, gre tudi <2>1 proti 0, ko gresta \(  m, n \to \infty \), kar pomeni, da je vrsta Cauchyjeva.
**** <2>2 QED
Dokaz: <1>1
* Izrek 7.34

Če \(  A, B \in \mathbb{R}^{n \times n} \) komutirata \(  AB = BA  \), potem je

\[ e^{A + B} = e^{A} e^{B}
\]
* Trditev 7.35
Predpostavke:
- \(  A \in \mathbb{R} ^{n \times n} \) poljubna matrika

Funkcija \(  Y: \mathbb{R} \to \left( \mathbb{R}^{n\times n}, \left\lVert \cdot \right\rVert \right), \ x \mapsto e^{xA } \) je odvedljiva v smilu, da obstaja tak \( Y' \in \mathbb{R}^{n \times n}   \), da velja

\[ \lim_{h \to 0} \left\lVert Y'(x) - \frac{Y(x + h) - Y(x)}{h} \right\rVert = 0
\]

in velja \(  Y'(x) = AY \)
** Dokaz
*** <1>1

\[   \left\lVert Y'(x) - \frac{Y(x + h) - Y(x)}{h} \right\rVert = \left\lVert AY - \frac{Y(x + h) - Y(x)}{h} \right\rVert
\]

Dokaz: Predpostavka trditve.
*** <1>2

\[   \left\lVert AY - \frac{Y(x + h) - Y(x)}{h} \right\rVert = \left\lVert Ae^{xA } - \frac{e^{(x + h) A} - e^{Ax }}{h} \right\rVert
\]

Dokaz: Predpostavka trditve
*** <1>3

\[  \left\lVert Ae^{xA } - \frac{e^{(x + h) A} - e^{Ax }}{h} \right\rVert = \left\lVert e^{xA } \left( A - \frac{e^{hA} - I}{h} \right) \right\rVert
\]

Dokaz: matriki \(  xA  \) in \(  hA \) komutirata in po izreku 7.34 si to lahko privoščimo. Prav tako smo izpostavili \(  e^{xA} \)
*** <1>4

\[  \left\lVert e^{xA } \left( A - \frac{e^{hA} - I}{h} \right) \right\rVert \le \left\lVert e^{xA} \right\rVert \cdot \left\lVert \frac{1}{h} e^{hA} - \frac{1}{h} I - A  \right\rVert
\]

Dokaz: To velja za našo normo.
*** <1>5


\[ \left\lVert e^{xA} \right\rVert \left\lVert \frac{1}{h} e^{hA} - \frac{1}{h} I - A \right\rVert = \left\lVert e^{xA } \right\rVert\cdot \left\lVert \sum\limits_{j = 2}^{\infty} \frac{h^{j - 1} A^j}{j!} \right\rVert
\]

Dokaz:

\(  e^{hA } = \sum\limits_{j = 0}^{\infty} \frac{\left( hA  \right)^j}{j!} \). Z upoštevanjem prvih dveh členov, tj. \(  j = 0, 1 \) se \(  \frac{1}{h}I \) in \(  A \) pokrajšajo. Prav tako ulomek iz leve strani premaknemo pod vsoto in zato je \(  h^{j - 1} \)
*** <1>6

\[  \left\lVert e^{xA } \right\rVert\cdot \left\lVert \sum\limits_{j = 2}^{\infty} \frac{h^{j - 1} A^j}{j!} \right\rVert \le \left\lVert e^{xA} \right\rVert \sum\limits_{j = 2}^{\infty} \left| h \right|^{j -1} \frac{\left\lVert A \right\rVert^j}{j!}
\]

Dokaz: Glej prejšnji dokaz <2>3
*** <1>7

\[  \left\lVert e^{xA} \right\rVert \sum\limits_{j = 2}^{\infty} \left| h \right|^{j -1} \frac{\left\lVert A \right\rVert^j}{j!} = \left\lVert e^{xA} \right\rVert \cdot \left| h \right| \cdot \left\lVert A \right\rVert ^2 \cdot \sum\limits_{j = 2}^{\infty} \frac{\left| h \right|^{j - 2} \left\lVert A \right\rVert^{j -2}}{j!}
\]
*** <1>8

\[ \left| h \right|  < 1
\]

Dokaz: Zanima nas \(  h \to 0 \) in je validna predpostavka.
*** <1>9

\[ \left\lVert e^{xA} \right\rVert \left| h \right| \left\lVert A \right\rVert ^2 \sum\limits_{j = 2}^{\infty} \frac{\left| h \right|^{j-2} \left\lVert A \right\rVert ^{j - 2} }{j!} \le  \left\lVert e^{xA} \right\rVert \left| h \right| \left\lVert A \right\rVert ^2 \sum\limits_{j = 2}^{\infty} \frac{ \left\lVert A \right\rVert^j}{j!}
\]

Dokaz: <1>8
*** <1>10

\[   \left\lVert e^{xA} \right\rVert \left| h \right| \left\lVert A \right\rVert ^2 \sum\limits_{j = 2}^{\infty} \frac{ \left\lVert A \right\rVert^j}{j!} = \left\lVert e^{xA }  \right\rVert \left| h \right| \left\lVert A \right\rVert ^2 \sum\limits_{k = 0}^{\infty} \frac{\left\lVert A \right\rVert^k}{ \left( k + 2 \right)! }
\]

Dokaz: uvedemo \(  k = j - 2 \)
*** <1>11

\[  \left\lVert e^{xA }  \right\rVert \left| h \right| \left\lVert A \right\rVert ^2 \sum\limits_{k = 0}^{\infty} \frac{\left\lVert A \right\rVert^k}{ \left( k + 2 \right)! } \le   \left\lVert e^{xA }  \right\rVert \left| h \right| \left\lVert A \right\rVert ^2 \sum\limits_{k = 0}^{\infty} \frac{\left\lVert A \right\rVert^k}{ \left( k \right)! } = \left\lVert e^{xA } \right\rVert \left| h \right| \left\lVert A \right\rVert ^2 e^{\left\lVert A \right\rVert} \left| h \right|
\]

Dokaz: Vsota v sredini je Taylorjev razvoj \(  f(x) = e^x \) za \(  x = \left\lVert A \right\rVert \)
*** <1>12 QED

<1>11 gre proti \(  0 \), ko gre \(  h \to 0 \), saj so ostali samo členi neodvisni od \(  h \). To pomeni, da za vse \(  x \in \mathbb{R} \) velja limita iz trditve.
* Eulerjeva DE

je DE oblike

\[ \sum\limits_{j = 0}^n a_j x^j y^{(j)} \left( x \right) = b(x)
\]
* Trditev 7.21
Predpostavke:
- \(  k \in \mathbb{N} \)
- \(  y: \left( 0, \infty \right) \to \mathbb{R} \)
- \(  y \in C^k \)

Definiramo \(  z\in C^k \left( \mathbb{R} \right) \) kot

\[ z(t) = y(e^t);\ t \in \mathbb{R}
\]

Označimo operator

\[ D = \frac{\mathrm{d} }{\mathrm{d} t}
\]

torej \(  D g = g' \).

Za vsak \(  x = e^t > 0 \),

\[ x^ky^{(k)} (x) = \left[ D(D - I)(D - 2I)\ldots (D - (k - 1)I)z \right] \left( t \right) = p_k \left( D \right)
\]

kjer je \(  I \) identiteta.
** Dokaz s pomočjo indukcije:
*** <1>1
Case 1: \(  k = 1 \)

\[ x y' (x) = e^t y'(e^t)
\]

Dokaz:

Predpostavka iz trditve.
*** <1>2

Desna stran enakosti:

\[ x y'(x) = \left[ p_1 \left( D \right)z \right] \left( t \right) = \dot{z}(t) = \frac{\mathrm{d} }{\mathrm{d} t}z(t) = \frac{\mathrm{d} }{\mathrm{d} t} y(e^t) = e^t y'(e^t)
\]
*** <1>3
Če velja za \(  k \), potem velja za \(  k + 1 \).

Za neki \(  k\in \mathbb{N} \) definiramo operator

\[ D - Ik: \phi \to \dot{\phi} - k \phi
\]



*** <1>4

Case 2: \(  p_k = x^k y^{(k)} \)
\[ x^{k+1} y^{(k + 1)} (x) = [(D - Ik)z](t) = \left[ x^k y^{(k)} \right] \dot{} - k \left[ x^k y^{(k)} \right]
\]

Dokaz: Verižno pravilo in pa definicija operatorja \(  D - Ik \)
*** <1>5 QED

/Opomba/: Slab dokaz, lahko da ker sem utrujen.
* Variacijski račun

Imamo funkcionale oblike

\[ I (y) = \int\limits_a^b L(x, y, y'(x) \,\mathrm{d x}
\]

kjer je \(  L = L(u, v, w): \mathbb{R} ^3 \to \mathbb{R} \) dana funkcija. \(  y \in C^1(J) \), kjer je \(  J = [a, b] \).

Pogosto uporabljamo funkcije iz razreda

\[ X = \left\{ y \in C^1 (J); y(a) = \alpha, y(b) = \beta \right\}
\]

Imamo fiksna krajišča.
* Definicija 8.1

(Lokalni) ekstrem/ ekstremala funkcionala \(  I \) definiramo kot funkcijo \(  y \in X \), v kateri ima \(  I \) v vseh "smereh" svoj ekstrem. To pomeni, da ima za vsako gladko funkcijo \(  \eta \), za katero je \(  y + \epsilon \eta \in X  \) za dovolj majhne \(  \epsilon \), ki je definirana na realnih številih, esktrem v \(  \epsilon = 0 \). Stacionarna točka za \(  I \) je funkcija, v kateri ima \(  I \) vse smerne odvode enake nič

\[ \left. \frac{\partial }{\partial \epsilon} I \left( y + \epsilon \eta \right) \right|_{\epsilon = 0} = 0
\]
** Opombe in druge oznake

Označimo množico \(  C^1_0 = \left\{ \eta \in C^1 (J); \ \left \eta \right|_{J_{\delta}} = 0 \right\} \). To je množica testnih funkcij, kjer ničla v indeksu pove, da imajo funkcije \(  \eta \) v krajiščih vrednosti \(  0 \).

* Lema 8.2 (variacijski lema)

Naj bo \(  J = [a, b] \) zaprt omejen interval v \(  \mathbb{R} \) in \(  f \in C(J) \). Če za vsako funkcijo \(  \eta \in C_0^1 \) velja

\[ \int\limits_{}^{} f \eta \,\mathrm{d x} = 0, \ \forall \eta \in C_0^1 \left( J \right)
\]

tedaj je \(  f= 0 \) na \(  J \) oz. za vsak \(  x \in J: \ f(x) = 0 \)
** Dokaz s protislovjem:

Obstaja \(  x \in J \), kjer

\[ f(x) \ne 0
\]

*** <1>1
Case 1: \(  f(x) \gneqq 0 \)

Obstaja \(  \delta > 0 \), da na \(  \left( x - \delta, x + \delta \right) \cap J \) velja

\[ f(t) \le \frac{f(x)}{2}; \ t \in \left( x -\delta, x + \delta \right) \cap J
\]

Dokaz: \(  f \) je zvezna
*** <1>2
Case 2:

\[ \eta = \begin{cases}
\eta \le 0; \\
\eta > 0; \ \left( x - \delta, x + \delta \right) \cap J \\
\eta = 0; \text{else}
\end{cases}
\]

Velja

\[ \int\limits_J^{} f \eta \,\mathrm{d x} = \int\limits_{\left( x- \delta, x + \delta \right) \cap J}^{} f\eta \,\mathrm{d x} + \int\limits_{\text{else}}^{}f \eta \,\mathrm{d x}  \gneq 0
\]
*** <1>3 QED

Protislovje, saj je integral večji od \(  0 \), ker je \(  f(x) \ne 0 \)
* Izrek 8.3

Predpostavke:
- \(  J = [a, b] \subset \mathbb{R} \)
- \(  L : J \times \mathbb{R} \times \mathbb{R} \to \mathbb{R} \) zvezno odvedljiva na vse spremenljivke
- \(  X \subset C^1 (J) \)
- \(  y \in X \) tako, da \(  y + C^0^1 (J) \subset X \)

Če je \(  y \) stacionarna točka za funkcional \(  I: X \to \mathbb{R} \), definiran s predpisom

\[ I(y) = \int\limits_a^b L(x, y, y') \,\mathrm{d x}
\]

tedaj \(  y \) ustrza EL pogoju

\[ L_y (x, y, y') = \frac{\mathrm{d} }{\mathrm{d}x } L_{y'} (x, y , y')
\]
** Dokaz:
*** <1>1
Case 1: \(  \eta \in C_0^1(J) \)

Velja

\[ y + \eta \epsilon \in X \ \forall \epsilon  \in \mathbb{R}
\]

Dokaz: Predpostavka 4
*** <1>2
Case 2: definiramo \(  F(I, y, \eta): \mathbb{R} \to \mathbb{R} \) s predpisom \(  F(\epsilon) = I(y + \epsilon \eta) \)

Velja \(  F'(0) = 0 \)

Dokaz: Predpostavka 5, da je \(  y \) stacionarna točka za \(  I \).
*** <1>3
Case 3: \(  \omega_{\epsilon}(x) = \left( x, y + \epsilon \eta, y' + \epsilon \eta' \right) \)

\[ \frac{\partial }{\partial \epsilon} F(\epsilon) = \int\limits_a^b \left[ \frac{\partial L}{\partial v} \left( \omega_{\epsilon} \right) \eta + \frac{\partial L}{\partial w} \left( \omega_{\epsilon} \right) \eta'   \right] \,\mathrm{d x}
\]

Dokaz: Verižno odvajanje pod integralom.
*** <1>4
Case 4: \(  \omega_0(x) = \left( x, y(x), y'(x) \right) \)

\[ F'(0) = 0 = \int\limits_a^b \left[ \frac{\partial L}{\partial v} \left( \omega_0 \right) \eta + \frac{\partial L}{\partial w} \left( \omega_0 \right) \cdot \eta'   \right] \,\mathrm{d x}
\]

Dokaz: <1>3 in <1>2
*** <1>5

\[ \int\limits_a^b \frac{\partial L}{\partial w} \left( \omega_0 \right)\cdot \eta'  \,\mathrm{d x} = \left. \eta \frac{\partial L}{\partial w} \right|_{x = a}^{x = b} - \int\limits_a^b \eta \frac{\mathrm{d} }{\mathrm{d}x }\left[ \frac{\partial L}{\partial w} \left( \omega_0 \right)  \right] \,\mathrm{d x} =  \int\limits_a^b \eta \frac{\mathrm{d} }{\mathrm{d}x }\left[ \frac{\partial L}{\partial w} \left( \omega_0 \right)  \right] \,\mathrm{d x}
\]

Dokaz: Integracija per partes ter Case 1, da je \(  \eta \) v krajiščih \(  0 \).
*** <1>6

\[ 0 = \int\limits_a^b \left[ \frac{\partial L}{\partial v} \left( \omega_0 \right) - \frac{\mathrm{d} }{\mathrm{d}x} \left[ \frac{\partial L}{\partial w} \left( \omega_0 \right)  \right]  \right]\cdot \eta \,\mathrm{d x}
\]

Dokaz: <1>4 in <1>5
*** <1>7 QED

\[  \left[ \frac{\partial L}{\partial v} \left( \omega_0 \right) - \frac{\mathrm{d} }{\mathrm{d}x} \left[ \frac{\partial L}{\partial w} \left( \omega_0 \right)  \right]  \right] = 0
\]

Dokaz: Variacijska lema ter <1>6
* Gibljiva krajišča

V primeru gibljivih krajišč, se integral v koraku <1>5 dokaza ne prevede na \(  0 \) in dobimo

\[ \int\limits_a^b \left[ \frac{\partial L}{\partial v} \left( \omega_0 \right) - \frac{\mathrm{d} }{\mathrm{d} x} \left[ \frac{\partial L}{\partial w} \left( \omega_0 \right)  \right]  \right]\eta \,\mathrm{d x} +\left. \eta(x) \frac{\partial L}{\partial w} \left( \omega_0 \right) \right|_{x = a} ^{x = b} = 0; \ \forall \eta \in C^1 (J)
\]


Edina možnost, da je produkt \(  \eta(x) \cdot C = 0; \forall \eta \in C^1(J)  \), je, če je \(  C = 0 \). Iz tega dobimo

\[ \frac{\partial L}{\partial w} \left( \omega_0(a) \right) = \frac{\partial L}{\partial w} lr(\omega_0 (b)) = 0
\]
* \(L = L(x, y) \)

EL se prevede na \(  L_{y'}= C \)
* \( L = L(y, y') \)

Dobimo /Beltramijevo identiteto/, ker je levi del EL pogoja enak \(  0 \).

\[ L - y' L_{y'} = C, \ C \in \mathbb{R}
\]

Z odvajanjem po \(  x \) in verižnim pravilom dobimo

\[ \left( L - y' L_{y'} \right)' = \left( L_y - \frac{\mathrm{d} }{\mathrm{d}x} L_{y'} \right) y'
\]
* Definicija 9.1

Prostor s skalarnim produktom je vektorski prostor \(  V \) nad \(  \mathbb{R} \) ali \(  \mathbb{C} \), na katerem obstaja preslikava

\[ \left\langle \cdot, \cdot \right\rangle : V \times V \to \mathbb{C}
\]

tako, da velja

1. \(  \left\langle x + y, z \right\rangle = \left\langle x, z  \right\rangle + \left\langle y, z \right\rangle\)
2. \(  \left\langle \lambda x, z \right\rangle =\lambda \left\langle  x, z\right\rangle\)
3. \(  \left\langle x, z \right\rangle = \overline{\left\langle z, x \right\rangle}\)
4. ter \(  \left\langle x, x \right\rangle \ge 0 \) in \(  \left\langle x, x \right\rangle = 0 \iff x = 0\)

/Opomba/: Ali je \(  0 \in V \)? Ja, ker je \(  V \) vektorski prostor.
* Definicija 9.2

Predpostavka:
- \(  V \) je prostor s skalarnim produktom

Norma, ki izhaja iz skalarnega produkta, je definirana s predpisom

\[ \lVert x \rVert = \sqrt{\left\langle x, x \right\rangle}
\]

Preslikava \(  \lVert \cdot \rVert: V \to [0, \infty) \) se imenuje norma, če velja

1. \(  \lVert x \rVert \ge 0 \forall x \in V \)
2. \(  \lVert x \rVert = 0 \iff x = 0\)
3. \(  \lVert \lambda x \rVert = \left| \lambda \right| \lVert x \rVert  \forall x \in V, \lambda \in \mathbb{C}/ \mathbb{R}\)
4. \(  \lVert x + y \rVert \le \lVert x \rVert + \lVert y \rVert\)

Če je \(  V \) prostor s skalarnim produktom, tedaj predpis

\[ \lVert x \rVert  = \sqrt{\left\langle x, x \right\rangle}
\]

res definira normo na \(  V \).
* Trditev 9.3 (CSB neenakost)

Za vsak \(  x, y \) iz prostor s skalarnim produktom \(  V \), velja

\[ \left| \left\langle x, y \right\rangle \right|  \le \lVert x \rVert \lVert y \rVert
\]
** Dokaz
*** <1>1
Case 1: prostor skalarjev je \(  \mathbb{R} \)
Case 2: \(  \lambda \in \mathbb{R} \)

o\[ 0 \le \lVert x \rVert ^2 + \lVert y \rVert ^2 + \lambda \left\langle x, y \right\rangle
\]

za vsak \(  x, y \in V \) ter za vsak \(  \lambda \in \mathbb{R} \)

Dokaz:
**** <2>1

\[ 0 \le \left\langle x + \lambda y, x + \lambda y \right\rangle
\]

Dokaz: Definicija 9.1, 4)
**** <2>2

\[ \left\langle x + \lambda y, x + \lambda y \right\rangle = \left\langle x, x + \lambda y \right\rangle + \left\langle \lambda y, x + \lambda y \right\rangle
\]

Dokaz: Definicija 9.1, 1)
**** <2>3

\[   \left\langle x, x + \lambda y \right\rangle + \left\langle \lambda y, x + \lambda y \right\rangle = \left\langle x, x + \lambda y \right\rangle + \lambda \left\langle y, x + \lambda y \right\rangle
\]

Dokaz: Definicija 9.1 2)
**** <2>4

\[  \left\langle x, x + \lambda y \right\rangle + \lambda \left\langle y, x + \lambda y \right\rangle = \left\langle x + \lambda y, x \right\rangle + \lambda \left\langle x + \lambda y, x \right\rangle
\]

Dokaz: Definicija 9.1 3) in pa smo na prostoru \(  \mathbb{R} \)
**** <2>5 QED

\[ \left\langle x + \lambda y, x \right\rangle  + \lambda \left\langle x + \lambda y, x \right\rangle = \lVert x \rVert ^2 + \lVert y \rVert ^2 + \lambda \left\langle x, y \right\rangle
\]

za vsak \(  x, y \in V \) ter za vsak \(  \lambda \in \mathbb{R} \)
Dokaz: Definicija 9.1 in definicija norme
***
*** <1>2
Case 3:

\[ \lVert x \rVert ^2 + \lVert y \rVert ^2 + \lambda \left\langle x, y \right\rangle = f( \lambda )
\]

\(  f(\lambda) \ge 0 \), ko je diskriminanta \(  D \le 0 \)

Dokaz: Kvadratna enačba
*** <1>3 QED

\[ \left| \left\langle x, y \right\rangle \right|  \le \lVert x \rVert \lVert y \rVert
\]

Dokaz:

Iz <1>2 velja

\begin{align*}
  D &= b ^2 - 4ac \le 0 \\
(2 \left\langle x, y \right\rangle) ^2 - 4 \lVert x \rVert ^2 \lVert y \rVert ^2 &\le 0 \\
4 \left\langle x, y \right\rangle &\le 4 \lVert x \rVert ^2 \lVert y \rVert ^2 \\
\left| \left\langle x, y \right\rangle \right| \le \lVert x \rVert \lVert y \rVert
\end{align*}
* Definicija 9.4

Prostor \(  V \) s skalarnim produktom je Hilbertov, če je v inducirani metriki poln.
* Definicija 9.9

Predpostavke:
- \(  X \) je prostor s skalarnim produktom
- \(  A \subset X \)

Množica

\[ A^{\perp } = \left\{ y \in X; y \perp a, \ \forall a \in A \right\}
\]
* Trditev 9.10

\(  A^{\perp } \) je zaprt vektorski prostor.
** Dokaz
*** <1>1

Velja linearnost (množenje s skalarjem).
*** <1>2

Konvergentno zaporedje v \(  A^{\perp } \) ima limito v \(  A^{\perp } \).

Dokaz:
**** <2>1
Case 1: \(  a \in A \)
Case 2: \(  y_n \in A^{\perp } \)
Case 3: \(  y_n \) konvergira k \(  y \)

\[ \lim_{n \to \infty} \left| \left\langle y - y_n, a \right\rangle \right|  \le \lim_{n \to \infty} \lVert y - y_n \rVert \lVert a \rVert
\]

Dokaz: CBS neenakost
**** <2>2

\[ \lim_{n \to \infty} \lVert y - y_n \rVert = 0
\]

Dokaz: Case 3
**** <2>3 QED

<2>1 gre proti 0, ker gre <2>2 proti 0, torej \(  y \in A^{\perp } \)
*** <1>3 QED
Dokaz: <1>1 in <1>2
* Definicija 9.11
Predpostavke:

- \(  X \) je prostor s skalarnim produktom
- \(  Y \subseteq X \)
- \(  x \in X \)

\(  y \) je ortogonalna projekcija vektorja \(  x \) na podprostor \(  Y \), če je \(  x - y \perp Y  \) oz. \(  x - y \in Y ^{\perp} \)

Oznake:

- \(  y = P_Y x \)
- preslikava \(  P_Y: X \to Y, x \mapsto y = P_Y x \) je ortogonalni projektor prostora \(  X \) na podprostor \(  Y \).
* Trditev 9.12
Predpostavke:
- \(  X \) je prostor s skalarnim produktom
- \(  Y \subseteq X \) linearni podprostor
- za vsak \(  x \in X \)  obstaja neki \(  P_Y x \) kot iz prejšnje definicije

Veljajo sledeče stvari:

1) \(  P_Y x \) je enolično določen
2) \(  P_Y x \) je najboljši približek za \(  x \) v \(  Y \), v smislu

   \[ \lVert x - P_Y x \rVert = \inf_{z \in Y} \lVert x - z \rVert = d(x, Y)
   \]
3) \(  P_Y \) je linearna
4) Preslikava \(  P_Y \) je zvezna, celo skrčitev: \(  \lVert P_Y x \rVert \le \lVert x \rVert\) za vsak \(  x \in X \)
5) \(  Y \) je zaprt v \(  X \)
** Dokaz:
*** 1)
**** <1>1
Case 1: \(  y_1, y_2 \in Y \)
Case 2: \(  x - y_1 \perp Y \)
Case 3: \(  x - y_2 \perp Y \)

\[ x - y_1 - x + y_2 = -y_1 + y_2 \in Y
\]

Dokaz: Odštejemo Case 2 in Case 3, ter Case 1
**** <1>2

\[ y_2 - y_1 \perp Y
\]

Dokaz: Case 3 in Case 2
**** <1>3 QED

Dokaz: iz <1>1 in <1>2 sledi, da je \(  y_2 - y_1 \perp y_2 - y_1 \), kar je možno samo, če \(  y_1 = y_2 \)
*** 2)
**** <1>1
Case 1: \(  z \in Y \)

\[ x - z = \underbrace{x - P_Y x}_{\in Y^{\perp}} + \underbrace{P_Yx - z}_{\in Y}
\]

Dokaz: Prištejemo in odštejemo isto vrednost ter definicija 9.11
**** <1>2 QED

\[ \lVert x - P_Y x \rVert  ^2 \le \lVert x - z \rVert ^2
\]

Dokaz: Pitagorov izrek
*** 3)
**** <1>1
Case 1: \(  x_1, x_2 \in X \)
Case 2: \(  x_1 - P_Y x_1, x_2 - P_Y x_2 \in Y^{\perp} \)

\[ \left( x_1 + x_2 \right) - \underbrace{\left( P_Y x_1 + P_Y x_2 \right)}_{\in Y} \in Y ^{\perp}
\]
**** <1>2 QED

Iz 1) sledi \(  P_Y x_1 + P_Y x_2 = P(x_1 + x_2) \)
*** 4)
**** <1>1
Case 1: \(  x = (x - P_Y x) + P_Y x \)

\[ \lVert x \rVert  ^2 = \underbrace{\lVert x - P_Y x \rVert ^2}_{\ge 0} + \lVert P_Y x \rVert \ge \lVert P_Y x \rVert
\]
**** <1>2 QED
Dokaz: <1>1
*** 5)
**** <1>1
Case 1: \(  \left( y_n \right)_n \subset Y \)
Case 2: \(  y_n \to x \) za neki \(  x \in X \)

\[ x \in Y
\]
***** <2>1

\[ P_Y y_n \to P_Y x
\]

Dokaz: \(  P \) je zvezen
***** <2>2

\[  \lVert P_Y y_n - P_Y x \rVert = \lVert P_Y \left( y_n - x \right) \rVert
\]

Dokaz: \(  P \) je linearen 3)
***** <2>3

\[ \lVert P_Y \left( y_n - x \right) \rVert \le \lVert y_n - x \rVert
\]

Dokaz: 4)
***** <2>4

<2>3 je enako 0

Dokaz: Case 2
***** <2>5

\[ P_Y y_n = y_n
\]

Dokaz: Case 1, \(  y_n \in Y \)
***** <2>6

\[ P_Y x = x
\]

Dokaz:

\[ P_Y x \Leftarrow P_Y y_n = y_n \Rightarrow x
\]
***** <2>7 QED

\(  x \in Y  \) iz <2>6
**** <1>2 QED
Prostor je linearen in zaprt
* Trditev
Predpostavke:
- \(  X \) je vektorski prostor s skalarnim produktom
- \(  Y \subseteq X \) končno dimenzionalen prostor
- \(  \left\{ e_1, \ldots, e_n \right\} \) njegova ONS

Tedaj je

\[ P_Y x = \sum\limits_{j = 1}^n \left\langle x, e_j \right\rangle e_j
\]
** Dokaz:
*** <1>1

\[ \left\langle x - \sum\limits_{j = 1}^n \left\langle x, e_j \right\rangle e_j, e_k \right\rangle = 0
\]

Dokaz: ko razpišemo dobimo \(  \left\langle x, e_k \right\rangle - \sum\limits_{j = 1}^n \left\langle x, e_j \right\rangle \delta_{j k} = 0 \)
*** <1>2
Case 1: \(  y = \left( x - \sum\limits_{j = 1}^{n \left\langle x, e_j \right\rangle}e_j \right) \)

Velja

\[ y \perp e_k, \ \forall k \in \left\{ 1, \ldots n \right\}
\]
*** <1>3

\[ y \perp \mathrm{Lin } \left\{ e_1, \ldots, e_n \right\} = Y
\]

Dokaz: <1>2
*** <1>4 QED

Po definicija ortogonalnega operatorja je vsota res enaka \(  P_Y x \)

* Definicija 9.14

Pravimo, da je družina \(  \left\{ e_j, j \in \mathbb{N} \right\} \) ortonormiran sistem, če velja \(  \left\langle e_j, e_k \right\rangle = \delta_{j k}\)
* Trditev 9.15 (Besselova neenakost)

Predpostavke:
- \(  X \) vektorski prostor s skalarnim produktom
- \(  \left\{ e_j, j \in N \right\} \) ortonormirana baza v \(  X \)

Za vsak \(  x \in X  \) velja

\[ \sum\limits_{j = 1}^{\infty} \left| \left\langle x, e_j \right\rangle \right| ^2 \le \lVert x \rVert ^2
\]
** Dokaz:
*** <1>1
Case 1: \(  Y_n = \mathrm{Lin } \left\{ e_1, \ldots e_n \right\} \)
Case 2: \(  P_{Y_n} x = \sum\limits_{j = 1}^n \left\langle x, e_j \right\rangle e_j \)

\[ \lVert P_{Y_n} x \rVert  ^2 = \sum\limits_{j = 1}^n \left| \left\langle x, e_j \right\rangle \right| ^2
\]

Dokaz: Pitagorov izrek in pa \(  e_j \) so ortogonalni med sabo
*** <1>2

\[ \sum\limits_{j = 1}^n \left| \left\langle x, e_j \right\rangle \right|  ^2 \le \lVert x \rVert ^2, \ \forall n  \in \mathbb{N}
\]

Dokaz: Trditev 9.12 4)
*** <1>3

\[ \sum\limits_{j = 1}^{\infty } \left| \left\langle x, e_j \right\rangle \right|  ^2 \le \lVert x \rVert ^2
\]

Dokaz: <1>2
