#+title: Anki Dokazi
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{esint}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}

* Trditev 2.19

Naj bo \(  K \subset \mathbb{R}^n \) kvader in \(  f: K \to [0, \infty) \) omejena. Tedaj velja

\[ \int\limits_K f \,dx = 0 \ \implies \  f = 0 \text{ s.p. } K
\]
** Dokaz
*** 1.
Case: \(  K_n = \left\{ x \in K; \ f(x) \le \frac{1}{n} \right\}, \ n \in \mathbb{N} \)
*** 2.
\(  0 \le \chi_{K_n} \le nf \) velja povsod na \(  K \)
**** <2>.1
\(  f \ge 0 \)
Dokaz: zaradi definicije funkcije \(  f(x) \) v 1.
**** <2>.2 QED
*** 3.
\[ 0 \le S(\chi_{K_n}) \le n \cdot S(f) = 0
\]
**** <3>.1
Case: \(  S(\chi_{K_n}) = \inf_D S(\chi_{K_n}, D)  \).
**** <3>.2
\(  0 \le S(\chi_{K_n}, D) \le S(nf, D) = n S(f, D) \) za vsako delitev \(  D \) kvadra \(  K \)
Dokaz: 2. ter definicije zgornje Darbouxove vsote:

\begin{align*}
  S(f, D) &= \sum\limits_{i = 1}^n \sum\limits_{j = 1}^m M_{ij} \left| P_{ij} \right| && M_{ij} = \sup f(x, y) \\
S(nf, D) &= \sum\limits_{i=1}^n \sum\limits_{j=1}^m n M_{ij} \left| P_{ij} \right|\\
= n S(f, D)
\end{align*}
**** <3>.3
\( n \cdot S(f) = 0  \), ker je \(  \int\limits_K^{} f\,\mathrm{d x} = 0 \)
Dokaz: predpostavka v trditvi
**** <3>.4 QED
*** 4.
\(  S(\chi_{K_n}) = 0 \)

Dokaz: 3.
*** 5.
\[ \int\limits_K^{} \chi_{K_n}\,\mathrm{d x} = \int\limits_{K_n}^{}1\,\mathrm{d x} = 0
\]

Dokaz: definicija karakteristične funkcije \(  \chi_{K_n} \) ter 4.

/zdi se mi, da je implicitno privzeto, da je funkcija integrabilna in po definiciji je integrabilna, ko sta \(  s(f) = S(f) \) enaki.
*** 6.
\[ V(K_n) \exists \ \land \ V(K_n = 0)
\]

Dokaz: 5.
*** 7.
\[ m(K_n) = 0 \ \forall n \in \mathbb{N}
\]

Dokaz: Trditev 2.17, če je \(  A \subset \mathbb{R}^n \) kompaktna množica, potem je \(  V(A) = 0 \ \iff \ m(A) = 0 \).
*** 8.
\[ m(\left\{ f \ne 0 \right\}) = m(\bigcup_{n \in \mathbb{N}} K_n) = 0
\]

Dokaz: 7.
* Izrek 2.20 (Fubini-Tonelli)

Naj bo \(  f:[a,b] \times [c, d] \to \mathbb{R} \) integrabilna. Privzamemo, da je \(  \forall x \in [a, b] \) funkcija \(  f(x, \cdot): [c, d] \to \mathbb{R}, \ y \mapsto f(x, y) \) definirana kot integrabilna na \(  [c, d] \). Tedaj je

\[ \iint\limits_{[a, b] \times [c, d]}^{} f(x, y) \,\mathrm{dx dy} = \int\limits_a^b \int\limits_c^d f(x, y) \,\mathrm{d y}\,\mathrm{d x}
\]

Če je \(  f \) zvezna, potem je

\[ \iint\limits_{[a, b]\times [c, d]}^{} f(x, y) \,\mathrm{d xdy} = \int\limits_{a }^b \left( \int\limits_c^d f(x, y) \,\mathrm{d y} \right)\,\mathrm{d x} = \int\limits_c^d \left( \int\limits_a^b f(x, y)\,\mathrm{d x} \right)\,\mathrm{d y}
\]

** Dokaz
*** <1>1
\(  g: [a, b] \to \mathbb{R} \),

\[ g (x) = \int\limits_c^d f(x, y) \,\mathrm{d y}
\]

Dokaz: Funkcija \(  g \) obstaja, ker je \(  f \) integrabilna.
*** <1>2
Assume: \(  I = [a, b], \ J = [c, d] \)
Prove:
\[ \iint\limits_{I \times J}^{} f(x, y)  \,\mathrm{d x dy} = \int\limits_I^{} g(x) \,\mathrm{d x}
\]
Dokaz:
**** <2>1
Assume: delitvi \(  D_1 = \left\{ I_i = [x_{i-1}, x_i]; \ i = 1, \ldots, m \right\} \) za \(  I \) in \( D_2 = \{J_j = [y_{j - 1}, y_j]; \ j = 1, \ldots n \} \) za \(  J \).
Prove: \(  D_1 \times D_2 \) je delitev za \(  I \times J \)
***** <3>1
\(  D_1 \) je projekcija na \(  I \)
***** <3>2
\(  D_2 \) je projekcija \(  J \)
***** <3>3 QED
By: <3>1 in <3>2
**** <2>2
Assume: \(  P_{ij} = I_i \times J_j \) in

\(  m_{ij} (f) = \inf_{P_{ij}} f \) in \(  M_{ij} (f) = \sup_{P_{ij}} f \)

Prove:
\[ s(f, D) \le \sum\limits_{i = 1}^m \inf_{x \in I_i} g(x) \left| I_i \right| = s(g, D_1)
\]

Dokaz:
***** <3>1
\[ s(f, D) = \sum\limits_{i = 1, j=1}^{m, n} m_{ij} (f) \left| P_{ij} \right| = \sum\limits_{i=1}^m \left( \sum\limits_{j = 1}^n m_{ij}(f) \left| J_j \right| \right) \left| I_i \right|
\]
Dokaz: definicija spodnje Darbouxove vsote ter \(  \left| P_{ij} \right| = \left| J_j \right| \left| I_i \right|\)
***** <3>2
\[ \sum\limits_{j =1}^{n} m_{ij} (f) \left| J_j \right| \le \sum\limits_{j = 1}^m m_j (f(x, \cdot)) \left| J_j \right| = s(f(x, \cdot), D_2) \le \int\limits_J^{} f(x, y) \,\mathrm{d y} = g(x)
\]

Dokaz: Integrabilno po Darbouxu ter definicije \(  m_{ij} \) in \(  m_j \).
***** <3>3
\[ \sum\limits_{j=1}^n m_{ij} (f) \left| J_j \right| \le \inf_{x \in I_i} g(x)
\]

Dokaz: <3>2 in \(  \inf_{x \in I_i} g(x) \le g(x) \)
***** <3>2 QED
Dokaz: <3>1, in <3>3 ter definicija spodnje Darbouxove vsote
**** <2>3
Simetrično s supremumi
**** <2>4
 \( s(f, D) \le s(g, D_1) \le S(g, D_1) \le S(f, D)  \)
 Dokaz: <2>2 in <2>3
**** <2>5
Assume: \(\forall \epsilon > 0 \)
Prove:
\[ S(g, D_1) - s(g, D_1) < \epsilon
\]
Dokaz:
***** <3>1
\[ S(f, D) - s(f, D) < \epsilon
\]
Dokaz: \(  f \) je integrabilna in obstaja taka delitev \(  D \)
***** <3>2 QED
Dokaz: <3>1 in <2>4
**** <2>6 QED
*** <1>3 QED
Dokaz: <1>2
* Trdite 2.43
Predpostavke:
- \( I = [a,b] \)
- \( \alpha, \beta: I \to \mathbb{R} \) zvezne in \( \alpha \le \beta \)
- \( A: \left\{ \left( x, y) \right) \in \mathbb{R} ^2, \ x \in I, y \in \left[ \alpha(x), \beta(x) \right] \right\} \)
- \( f: A \to \mathbb{R} \)

\[ \iint\limits_A^{} f(x, y)  \,\mathrm{d x dy} = \int\limits_a^b \int\limits_{\alpha(x)}^{\beta(x)} f(x, y) \mathrm{dy dx}
\]
** Dokaz
*** <1> 1
Obstaja pravokotnik \( P \subset \mathbb{R} ^2 \) tako, da \( A \subset P \)

Dokaz: \( \alpha(x), \beta (x) \) sta zvezni in na intervalu \( [a, b] \) omejeni.
*** <1>2
Case: \( \tilde{f}: A \to \mathbb{R} \):
\[ \tilde{f} (x, y) = \begin{cases}
f(x, y), \ (x, y) \in A \\
0; \text{ else}
\end{cases} = f \cdot \chi_{A}
\]
Prove: \( \tilde{f} \)  je integrabilna na \( P \)
Dokaz:
**** <2>1
Točke nezveznosti funkcije \( \tilde{f} \) so vsebovane v \( \Gamma_{\alpha} \cup \Gamma_{\beta} \).
**** <2>2
\( V(\Gamma_{\alpha} \cup \Gamma_{\beta}) = 0 \)
Dokaz:
Prostornina unije grafov s prostornino 0 je 0.
**** <2>3
\( \tilde{f}\) je zvezna skoraj povsod
Dokaz: <2>2 ter definicija s.p.
**** <2>4 QED
Dokaz: <2>3 in Lebesgue
*** <1>3
Prove: \( \tilde{f}(x, \cdot) \) je integrabilna \( \forall x \in I \)
Dokaz: \( \tilde{f} \) je odsekoma zvezna na \( [c, d] \)
*** <1>4
\begin{align*}
  \iint\limits_A^{} f(x, y) \,\mathrm{dx dy} &= \iint\limits_P^{} \tilde{f}(x, y) \,\mathrm{d x dy} \\
&= \int\limits_a^{ b } \left( \int\limits_c^d \tilde{f}(x, y) \mathrm{dy}) \right\mathbb{dx} \\
&= \int\limits_a^b \int\limits_{\alpha}^{\beta} f(x, y) \mathrm{dx dy}
\end{align*}
* Izrek 2.45
Predpostavke:
- \( A \subset \mathbb{R}^n, \ B \subset \mathbb{R} ^n  \) kvadra
- \( f: A \times B \to \mathbb{R} \) integrabilna
- \( f(x, \cdot) \) integrabilna na \( B \forall x \in A \)

\[ \iint\limits_{A \times B}^{}f \,\mathrm{d x dy} = \int\limits_A^{} \left( \int\limits_B^{}f(x, y) \, \mathrm{dx} \right) \, \mathrm{dy}
\]
* Posledica 2.46
\( F: K = [a, b] \times [c, d] \times [e, f] \to \mathbb{R} \) zvezna

\[ \iiint\limits_K^{} F(x, y, z) \,\mathrm{d V} = \iint\limits_{[a,b] \times [c, d]}^{} \left( \int\limits_e^f F(x, y, z)\, \mathrm{dz} \right) \,\mathrm{d dxdy} = \int\limits_a^b \left( \int\limits_c^d \left[ \int\limits_e^f F(x, y, z) \, \mathrm{dz} \right] \mathrm{dy} \right) \mathrm{dx}
\]
* Trditev 2.47
Predpostavke:
- \( A \subset \mathbb{R} ^2  \) ima ploščino
- \( \alpha, \beta: A \to \mathbb{R} \) zvezna in \( \alpha < \beta \)
- \( B = \left\{ (x, y, z) \in A \times \mathbb{R}, \, \alpha(x, y) \le y \le B(x, y) \right\} \)
- \( f: B \to \mathbb{R} \) je zvezna

\[ \iiint\limits_B^{} f(x,y, z)  \,\mathrm{d V} = \iint\limits_A^{} \left( \int\limits_{\alpha(x)}^{\beta(x)} f(x, y, z) \, \mathrm{dz} \right) \,\mathrm{d y dx}
\]
* Definicija 2.50
Predpostavke:
- \( U^{\text{odp}} \subset \mathbb{R}^n \)
- \( \phi_1, \ldots, \phi_m: U \to \mathbb{R} \) parcialno odvedljiva na vse spremenljivke

/Jacobijevo matriko/ za \( \phi = \left( \phi_1, \ldots, \phi_m \right) \) definiramo kot

\[ J\phi = \begin{bmatrix}
\frac{\partial \phi_1}{\partial x_1} & \mathbb{ldots} & \frac{\partial \phi_1}{\partial x_m}  \\
\vdots & \ddots & \ldots \\
\frac{\partial \phi_m}{\partial x_1} & \ldots & \frac{\partial \phi_m}{\partial x_m}
\end{bmatrix}
\]
* Izrek 2.51
Predpostavek:
- \( A \subset \mathbb{R} ^n \) omejena množica s prostornino
- \( \phi: A \to \mathbb{R} ^n \) injektivna in razreda \( C^1 \)
- \( \det J\phi(x) \ne 0 \forall x \in A \)
- \( x \mapsto \det(J(\phi(x))) \) omejena in različna od 0
- \( \phi(A) \) je odprta v \( R ^n \) s prostornino
- \( f: \phi(A) \to \mathbb{R} \) je integrabilna

  Tedaj je tudi \( x \mapsto f(\phi(x)) \left| \det J\phi(x) \right| \) integrabilna na \( A \) in velja

  \[ \int\limits_{\phi(A)}^{} f(x) \, \mathrm{dx} = \int\limits_A^{} f(\phi(t)) \left| \det J \phi(t) \right| \, \mathrm{dt}
  \]
* Skica dokaza:
*** <1>1
Case:
- \( A \) je pravokotnik,
- \( n = 2 \),
- \( f \) je zvezna,
- \( \left\{ P_j \right\} \) neka delitev za \( A \)
Prove:

\[ \iint\limits_{\phi(A)}^{} f(x, y)  \,\mathrm{d x dy} = \sum\limits_{ j}^{} \iint\limits_{\phi(P_j)}^{} f(x, y) \,\mathrm{d x dy}
\]

Dokaz: Injektivnost
*** <1>2
Prove:

\[ \sum\limits_j^{} \iint\limits_{\phi(P_j)}^{} f(x, y) \,\mathrm{d x dy} = \sum\limits_j^{} \left\langle f \right\rangle_{\phi(P_j)} \left| \phi(P_j) \right|
\]

Dokaz: Izrek o srednji vrednosti med \( f \) in \( Q \)

\[ \left\langle f \right\rangle_Q = \frac{1}{\left| Q \right|} \int\limits_Q^{} f \, \mathrm{dx}
\]
*** <1>3
\( \left\langle f \right\rangle_{\phi(P_j)} = f(\phi(u_j, v_j)) \)
*** <1>4
Prove:
\[ \left| \phi(P_j) \right| \approx = \left| \det J\phi  \right|
\]
Dokaz:
**** <2>1
[[file:jacobi_dokaz.svg]]
**** <2>2 QED

\begin{align*}
  \left| \phi(P_j) \right| &= \left| \left( \phi(u + \Delta u, v) - \phi(u, v) \right) \times \left( \phi(u, v + \Delta v) - \phi(u, v) \right) \right| \\
&= \frac{\partial \phi}{\partial u} \Delta u \times \frac{\partial \phi}{\partial v} \Delta v \\
&= \left| \phi_u \times \phi_v \right| \Delta u \Delta v \\
&= \begin{bmatrix}
\left( \phi_1 \right)_u & \left( \phi_1 \right)_v \\
\left( \phi_2 \right)_u & \left( \phi_2 \right)_v
 \end{bmatrix} = \left| \det J \phi \right|
\end{align*}
*** <1>5
Prove:
\[ \iint\limits_{\phi(A)}^{} f(x, y) \,\mathrm{d xdy} = \sum\limits_j^{} f(\phi(x, y)) \left| \det J\phi \right| \Delta u \Delta v
\]

Dokaz: <1>2, ter <1>4
*** <1>6 QED
Dokaz: <1>5 je Riemannova vsota za funkcijo \( f \circ \phi \left| \det J \phi \right|  \), kjer je \( \Delta u \Delta v \) velikost delilnega pravokotnika za \( A \). Posledično v limiti dobimo

\[ \int\limits_A^{} f \circ \phi \left| \det J \phi \right| \, \mathrm{dS} = \int\limits_A^{} f(\phi(\xi, \eta)) \left| \det J\phi(\xi, \eta) \right| \mathbb{d} \xi \mathrm{d}\eta
\]

* Definicija 2.16

Naj ima telo \(  T \subset \mathbb{R}^3 \) gostoto \(  \rho = \rho(x, y, z) \). Če je \(  \rho = \text{ konst. } \) je telo homogeno.

Masa telesa \(  T \) je definirana kot

\[ m(T) = \iiint\limits_T \rho(x, y, z) \, \mathrm{dV}
\]
* Definicija 2.17
Težišče telesa \(  T \) je točka \(  (x_t, y_t, z_t) \subset \mathbb{R} ^3 \) za katero velja

\begin{align*}
  x_t &= \frac{1}{m(T)} \iiint\limits_T x \rho(x, y, z) \, \mathrm{dV} \\
  y_t &= \frac{1}{m(T)} \iiint\limits_T y \rho(x, y, z) \, \mathrm{dV}\\
  z_t &= \frac{1}{m(T)} \iiint\limits_T z \rho(x, y, z) \, \mathrm{dV}
\end{align*}

Kompaktneje se to zapiše kot

\[ \mathbf{x}_t = \frac{1}{m(T)} \int\limits_T (x, y, z) \rho \,\mathrm{dx} = \frac{1}{m(T)} \int\limits_T \vec{\xi} \rho\,\mathrm{dV}
\]

kjer je \(  \vec{\xi} = (x, y, z) \) vektorska funkcija. Težišče nam pove povprečje položajev glede na utež \(  \rho \)
* Definicja 2.18

Vztrajnostni moment telesa \(  T \subset \mathbb{R} ^3 \) pri vrtenju okoli osi \(  \gamma \subset \mathbb{R}^3 \) je enako

\[ J_{\gamma} = \int\limits_T d(\vec{x}, \gamma) ^2 \rho(\vec{x}) \,\mathrm{d\vec{x}}
\]

kjer je \(  d(\vec{x}, \gamma) \) oddaljenost točke \(  \vec{x} = (x, y, z) \) od osi \(  \gamma \).

V posebnem primeru je to:

\[ J_z = \iiint\limits_T (x ^2 + y ^2) \rho(x, y, z) \, \mathrm{dx}\, \mathrm{dy} \mathrm{dz}
\]
* Posplošeni RD integral v \(  \mathbb{R} ^n \)
1) \(  f: D \to [0, \infty] \) omejena.

   \[ \int\limits_D f\,\mathrm{dV} := \lim_{a \to \infty} \int\limits_{D \cap [-a, a] ^n} f\,\mathrm{dV}
   \]

   Če vsi izrazi na desni obstajajo.

2) \(  f: D \to [0, \infty) \) neomejena. Tedaj definiramo

   \[ \int\limits_D f\,\mathrm{dV} := \lim_{M \to \infty} \int\limits_D \min \{f(x), M\}\,\mathrm{dx}
   \]

   če vsi izrazi na desni obstajajo.

3) \(  f:D \to \mathbb{R} \) (ni več pozitiven neskončen interval!)

   Poljubno funkcijo poskusimo izraziti s pomočjo pozitivnih funkcij (saj imam zanje že imamo definicijo).

   Definiramo

   \[ f_+ := \max \{f, 0\}
   \]
    Torej, če je funkcija pozitivna vzamemo njeno pozitivno vrednost, drugače je 0. Obratno velja za

    \[ f_- = \min\{-f, 0\}
    \]

   [[file:figures/izlimitirani_integral.svg]]

    In velja

    \[ f = f_+ - f_-, \quad f_{\pm} \ge 0
    \]

    Iz česar sledi

    \[ \int\limits_D f\,\mathrm{dx} := \int\limits_D f_+\,\mathrm{dV} - \int\limits_D f_-\,\mathrm{dV}
    \]

    Če oba integrala na desni obstaja in sta končna (nočemo razlike dveh neskončnosti).

    Poglejmo absolutno vrednost \(  \left| f \right|  = f_+ + f_-\), iz česar sledi, da je za definicijo \(  \int\limits_D f\,\mathrm{dV} \) pomembno, da obstaja \(  \int\limits_D \left| f \right| \,\mathrm{dV} \).
* Definicija 3.3
Pot je gladka, če je \(  \vec{r} \in C^1 (I) \) za \(  I \subset \mathbb{R} \).
* Definicija 3.4
Gladka krivulja v \(  \mathbb{R} ^3 \) je gladka pot \(  \vec{r} = \left( x, y, z \right): I \to \mathbb{R} ^3 \), za katero velja \(  \odv{r} (t) \ne 0 \) za vsak \(  t \in I \). Taka krivulja je tudi injektivna (in nima samopresečišč).
* Definicija 3.6
Če je \(  \vec{r}: [a, b] \to [0, \infty) \) gladka krivulja, katere tir označimo z \(  \Gamma \), je dolžina \(  \Gamma \) definirana kot

\[ l(\Gamma) = \int\limits_a^b \left| \odv{r}(t) \right|\,\mathrm{d t}
\]
* Trditev 3.7
Prove: Definicija 3.6 je dobra (torej neodvisna od izbrane parametrizacije)
** Dokaz
*** <1>1
Case 1: \(  \vec{r}: I = [a, b] \to \Gamma \)
Case 2: \(  \vec{\rho}: J = [\alpha, \beta] \to \Gamma \) (druga regularna parametrizacija)
Case 3: \(  h \in C^1:J \to I \)

Prove:

\[ \vec{\rho} = \vec{r} \circ h
\]

Dokaz: Case 3, 2, in 1
*** <1>2
\[ \int\limits_{\alpha}^{\beta} \left| \odv{\rho} (u) \right|\,\mathrm{d u} = \int\limits_{\alpha}^{\beta} \left| \odv{r}(h(u)) \right| \left| h'(u) \right|\,\mathrm{d u} = \int\limits_a^b \left| \odv{r} (t) \right|\,\mathrm{d t}
\]
Dokaz: <1>1 in verižno pravilo
*** <1>3 QED
Dokaz: <1>2
* Definicija 3.10
Enotski tangnenti vektor

\[ \frac{\odv{r}(t) }{\left| \odv{r} (t) \right|}
\]

Tangenta v točki \(  \odv{r}(t_0) \) premica skozi \(  \vec{r}(t_0) \) v smeri tangentnega vektorja na \(  \Gamma \) v točki \(  \vec{r}(t_0) \).

Enačba premice je

\[ (x, y, z) = \vec{r}(t_0) + \lambda \odv{r}(t_0)
\]

Normalna ravnina na \(  \vec{r}(t_0) \) je ravnina skozi \(  \vec{r}(t) \) pravokotna na tangentni vektor.
* Izrek 3.15
Predpostavke:

- \(  \gamma \) je regularna parametrizacija \(  C^2 \) neke krivulje \(  \mathbb{R} ^3 \)
- Za dani \(  t_0 \in \mathbb{R} \) privzamemo, da je

\[ \vec{v}_0 = \left( \odv{\gamma} \times \oddv{\gamma} \right) (t_0) \ne 0
\]

Tedaj obstaja \(  \delta > 0 \) tako, da sta za poljubni točki \(  t_1, t_2 \in \left( t_0 - \delta, t_0 + \delta \right) \), kjer so \(  t_1, t_2 \) in \(  t_0 \) različne, točke \(  \tilde{\gamma}(t_1), \vec{\gamma}(t_2), \vec{\gamma(t_0)} \) nekolinearne.

** Dokaz (s protislovjem)
*** <1>1
Assume: točke \(  \gamma(t_1), \gamma(t_2), \gamma(t_0) \) so kolinearne
Case 1: \(  l = l(t_1, t_2) \) je premica z izhodiščem \(  \left( \cdot, \gamma(t_0) \right) \), ki jih povezuje
Case 2: \( w \in l^{\perp}  \)
Case 3: \(  t_0 < t_1 < t_2 \)

Prove:

\[ \left\langle \gamma(t_1) - \gamma(t_0), w \right\rangle = \left\langle \gamma(t_2) - \gamma(t_0), w \right\rangle = 0
\]

Dokaz: Definicija skalarnega produkta ter Case 2, in Assume
*** <1>2 Rolleov izrek
Prove: Obstaja točki \(  \xi_1, \xi_2 \in \mathbb{R} \) tako, da velja

\[ t_0 < \xi_1 < t_1 < \xi_2 < t_2\ \ni: \ \left\langle \odv{\gamma}(\xi_1), w \right\rangle = \left\langle \odv{\gamma}(\xi_2), w \right\rangle = 0
\]

Dokaz: Rolleov izrek, matematika 1, ter odvod \( \frac{\mathrm{d} }{\mathrm{d} t} \left\langle \vec{\gamma}(t) - \vec{\gamma}(t_0), w \right\rangle \) (odvod konstante)

**** Rolleov izrek

/Spomni se/: Rolleov izrek (Matematika 1, Mrčun, str. 163)

Predpostavke:
- \( a, b \in \mathbb{R}, \ a < b \)
- \( f: [a, b] \to \mathbb{R} \) zvezna funkcija
- \( f \) odvedljiva na \( (a, b) \)

Če velja \( f(a) = f(b)  \), potem obstaja takšna točka \( c \in (a, b) \)

\[ f'(c) = 0
\]

V našem primeru je \( f(t) = \left\langle \gamma (t) - \gamma(t_0), w \right\rangle \)
***** Dokaz
****** <2>1

\( f \) omejena.

Dokaz: \( f \) je definirana na zaprti omejeni podmnožici in zvezna.
****** <2>2
Case: \( u, v \in [a, b], \ f(u) = \sup (f), \ f(v) = \inf(f) \)

Prove: \( c = u \)

Dokaz: \( u \in (a, b) \) je ekstrem funkcije \( f \), po Case <2>2
****** <2>3
\( c = v \)
Dokaz: \( v \in (a, b) \) je ekstrem funkcije f , po Case <2>2
****** <2>4
\( \forall c \in (a, b)  \)

Dokaz: \( f = \text{konst} \) za \( \left\{ u, v \right\} \subset \left\{ a, b \right\} \)
****** <2>5 QED
Dokaz: <2>2, <2>3, <2>4

*** <1>3
Prove: Obstaja \(  \xi_3 \in \left( \xi_1, \xi_2 \right) \) tako, da velja

\[ \left\langle \oddv{\gamma}(\xi_3), w \right\rangle = 0
\]

Dokaz: Rolleov izrek ter odvod iste funkcije
*** <1>4
Case 4: \( \epsilon > 0  \)

Prove:

\[ v_0 \times w = \left\langle \dot{\gamma}(t_0) - \dot{\gamma}(\xi_1), w \right\rangle \cdot \ddot{\gamma} (t_0) - \left\langle \ddot{\gamma} (t_0) - \ddot{\gamma}(\xi_3), w \right\rangle \cdot \dot{\gamma} (t_0)
\]

Dokaz: Linearna algebra \( (a \times b) \times c = (a \cdot c) \cdot b - (b \cdot c) \cdot a \) ter odšteli smo \( \dot{\gamma}(t_0) \) <1>2 in od \( \ddot{\gamma}(t_0) \) <1>3, saj je produkt <1>2 in <1>3 z \( w \) enak 0 - in se tako ne spremeni.
*** <1>5
\[ \left| v_0 \times w \right| \le \left( \left| \dot{\gamma}(t_0) - \dot{\gamma}(\xi_1) \right| \cdot \left| \ddot{\gamma}(t_0) \right| - \left| \ddot{\gamma}(t_0) - \ddot{\gamma}(\xi_3) \right| \cdot \left| \dot{\gamma}(t_0) \right|\right) \left| w \right|
\]

Dokaz: Cauchy-Schwartzova neenakost \( \left| \left\langle \vec{a}, \vec{b} \right\rangle \right| \le \left| \vec{a} \right|  \cdot \left| \vec{b} \right|\)
*** <1>6
Case 5: \( \alpha = \left| \dot{\gamma}(t_0) - \dot{\gamma}(\xi_1) \right| \)
Case 6: \( \beta = \left| \ddot{\gamma}(t_0) - \ddot{\gamma}(\xi_3) \right| \)

Prove: \( \alpha, \beta < \epsilon \)

Dokaz
**** <2>1
Obstaja \( \delta > 0 \), da za poljubna \( \xi_1, \xi_3 \in (t_0 - \delta, t_0 + \delta)  \)
Dokaz: \( \dot{\gamma}, \ddot{\gamma} \) sta zvezni v točki \( t_0 \).
**** <2>2 QED
Pogoj velja tudi za \( \xi_1, \xi_3 \) za \( t_1, t_2 \in (t_0, t_0 + \delta) \)
*** <1>7
Prove:

\[ \frac{\left| v_0 \times w \right|}{ \left| w \right|} \le \left( \left| \dot{\gamma}(t_0) \right| + \left| \ddot{\gamma}(t_0) \right| \right) \epsilon \quad \forall t_1, t_2 \in (t_0, t_0 + \delta), \ \forall w \in l(t_1, t_2) ^{\perp} \setminus \left\{ 0 \right\}
\]

Dokaz: \( \alpha = \epsilon, \ \beta = \epsilon \) <1>6, ter <1>5
*** <1>8

Prove: \( \frac{\left| v_0 \times w \right|}{\left| w \right|} = \left| v_0 \right| \sin \phi\)

Dokaz: definicija vektorskega produkta
*** <1>9
Prove:

\[ \sin \phi \le \frac{\left| \dot{\gamma}(t_0) \right| + \left| \ddot{\gamma}(t_0) \right|}{\left| \left( \dot{\gamma} \times \ddot{\gamma} \right) (t_0) \right|} \epsilon
\]

Dokaz: <1>8 in definicija \( \left| v_0 \right| = \left| \left( \dot{\gamma} \times \ddot{\gamma} \right) (t_0) \right| \)
*** <1>10 QED
Iz <1>9 vidimo, da je kot \( \phi \) med \( v_0 \) in \( w \in l(t_1, t_2)^{\perp} \) nujno majhen, za \( t_1 \) in \( t_2 \) blizu \( t_0 \). Tukaj naletimo na protislovje, ker \( l^{\perp} \) ni ravnina kot predpostavljeno na začetku, ampak ozek stožec okoli \( v_0 \).
* Izrek 3.15.1
Predpostavke:

- \(  \gamma \) je regularna parametrizacija \(  C ^2 \) neke krivulje \(  \mathbb{R} ^3 \)
- za poljuben \(  t_0 \in \mathbb{R} \) velja

  \[ v_0 = \left( \dot{\gamma} \times \ddot{\gamma} \right)(t_0) \ne 0
  \]
- \(  t_1, t_2 \in \left( t_0 - \delta, t_0 + \delta \right) \), in \(  t_1 \ne t_2 \ne t_0 \) so različne.

S \(  \Pi (t_1, t_2) \) označimo ravnino skozi \(  \gamma(t_1), \gamma(t_2), \gamma(t_0) \). Ravnina \(  \Pi(t_1, t_2) \) limitira proti ravnini z normalo \(  v_0 \), ko gresta \(  t_1, t_2 \to t_0 \).
** Dokaz
*** <1>1
Ravnina \(  \Pi (t_1, t_2) \) obstaja in je enolično določena.

Dokaz: Izrek 3.15
*** <1>2
Dovolj je dokazati:

Enotske normale \(  \vec{n}(t_1, t_2) \) na \(  \Pi(t_1, t_2) \) limitirajo k \(  \pm \frac{v_0}{\left| v_0 \right|} \), ko \(  t_1, t_2 \to t_0 \).
**** <2>1
Case 1: do predznaka natančno

\[ \vec{n} (t_1, t_2) = \frac{\left[ \gamma(t_1) - \gamma(t_2) \right] \times \left[ \gamma(t_2) - \gamma(t_1) \right]}{\left| \left[ \gamma(t_1) - \gamma(t_2) \right] \times \left[ \gamma(t_2) - \gamma(t_1) \right] \right|}
\]

Prove: \(  \vec{n}(t_1, t_2) \) je zvezna funkcija argumentov \(  t_1, t_2 \in \mathbb{R} ^2 \) na \(  \left( t_0 - \delta, t_0 + \delta \right) \times \left( t_0 - \delta, t_0 + \delta \right) \).

Dokaz: \(  \gamma \) je zvezna funkcija argumentov \(  t_2, t_1 \) iz predpostavke 1.
**** <2>2
Case 2: \(  \epsilon > 0 \)
Case 3: definiramo \(  f(t) = \left\langle \gamma(t) - \gamma(t_0), \vec{n} (t_1, t_2) \right\rangle \).

Obstajata \(  t_0 < \xi_1 < t_1 \xi_2 < t_2 \) tako, da velja

\begin{align*}
  0 &= f'(\xi_1) = \left\langle \dot{\gamma}(\xi_1), \vec{n}(t_1, t_2) \right\rangle \\
0 &= f'(\xi_2) = \left\langle \dot{\gamma} (\xi_2), \vec{n} (t_1, t_2) \right\rangle
\end{align*}

Dokaz: Rolleov izrek
**** <2>3

Obstaja \(  \xi_3 \in \left( \xi_1, \xi_2 \right) \) tako, da velja

\[ f''(\xi_3) = \left\langle \ddot{\gamma}(\xi_3), \vec{n}(t_1, t_2) \right\rangle = 0
\]

Dokaz: Rolleov izrek
**** <2>4

Velja

\[ \left| v_0 \times \vec{n}(t_1, t_2) \right| \le \left( \left| \dot{\gamma}(t_0 - \dot{\gamma}(\xi_1)) \right| \left| \ddot{\gamma})(t_0) \right| + \left| \ddot{\gamma} (t_0) - \ddot{\gamma}(\xi_3) \right| \left| \dot{\gamma}(t_0) \right|\right) \left| \vec{n}(t_1, t_2) \right|
\]

in \(  \left| \vec{n}(t_1, t_2) \right| = 1 \)

Dokaz:
***** <3>1

\begin{align*}
  v_0 &= \left[ \dot{\gamma}(t_0) \times \ddot{\gamma}(t_0) \right] \times \vec{n} (t_1, t_2) \\
&= \left\langle \dot{\gamma}(t_0), \vec{n}(t_1, t_2) \right\rangle \cdot \ddot{\gamma} (t_0) - \left\langle \ddot{\gamma}(t_0), \vec{n}(t_1, t_2) \right\rangle \cdot \dot{\gamma}(t_0) \\
&= \left\langle \dot{\gamma}(t_0) - \dot{\gamma}(\xi_1), \vec{n} (t_1, t_2) \right\rangle \cdot \ddot{\gamma}(t_0) - \left\langle  \ddot{\gamma}(t_0) - \ddot{\gamma}(\xi_3), \vec{n}(t_1, t_2) \right\rangle \cdot \dot{\gamma} (t_0)
\end{align*}

Dokaz:

\(  (a \times b) \times c = (a \cdot c) \cdot b - (b \cdot c) \cdot a \) ter v zadnji vrstici <2>2, ter <2>3
***** <3>2 QED
<3>1 in trikotniška neenakost
**** <2>5
Case 4: \(  \delta > 0 \)

Za \(  \xi_1, \xi_3 \in (t_0 - \delta, t_0 + \delta) \) velja

\begin{align*}
  \left| \dot{\gamma}(t_0) - \dot{\gamma}(\xi_1) \right| &< \epsilon  \\
\left| \ddot{\gamma}(t_0) - \ddot{\gamma}(\xi_3) \right| &< \epsilon
\end{align*}

Dokaz: definicija zveznosti funkcije
**** <2>6

\[ \sin \phi (t_1, t_2) \le \frac{\left| \dot{\gamma}(t_0) \right| + \left| \ddot{\gamma}(t_0) \right|}{\left| \dot{\gamma} \times \ddot{\gamma} \right|(t_0)} \epsilon
\]

Kot \(  \phi(t_1, t_2) \) je oster, saj je \(  \epsilon > 0 \), ampak majhen.

Dokaz:
***** <3>1
\[ \left| v_0 \times \vec{n}(t_1, t_2) \right| = \left| v_0 \right| \sin \phi
\]

Dokaz: definicija vektorskega produkta in \(  \left| \vec{n}(t_1, t_2) \right| = 1 \)
***** <3>2

\[ \left| v_0 \right| \sin \phi \le \frac{\left| \dot{\gamma}(t_0) \right| + \left| \ddot{\gamma}(t_0) \right|}{\left| \dot{\gamma} \times \ddot{\gamma} \right| (t_0)}
\]

Dokaz: <3>1 in <2>4
***** <3>3 QED
Dokaz: <3>2

**** <2>7
Case 5: \(  \tilde{v}_0 = \frac{v_0}{\left| v_0 \right|} \)

\[ \left| \tilde{v}_0 - \vec{n} \right| ^2 = 2(1 - \cos \phi)
\]

Dokaz: analiza 1

\[ \left| \tilde{v}_0 - \vec{n} \right| = \left| \tilde{v}_0 \right| + \left| \vec{n} \right| - 2 \left\langle \tilde{v}_0, \vec{n} \right\rangle = 2 - 2\cos \phi
\]

in \(  \left| \tilde{v}_0 \right| = \left| \vec{n} \right| = 1 \).
**** <2>8 QED
Dokaz: <2>7: razlika \(  1 - \cos \phi \) gre proti 0, ko \(  t_1, t_2 \to t_0 \), ker oster kot \(  \phi \to 0 \).
*** <1>3 QED
Dokaz: <1>2
* Definicija 3.16
Ravnini skozi \(  T_0 = \gamma(t_0) \) in z normalo \(  \left( \dot{\gamma} \times \ddot{\gamma} \right) (t_0) \ne 0  \) pravimo pritisnjena ravnina na krivuljo \(  \gamma \) v točki \(  T_0 \).
* Izrek 3.17

Če je \(  \Pi = \Pi(t_0) \) pritisnjena ravnina na \(  \gamma \) v točki \(  \gamma(t_0)\) velja

\[ d(\gamma(t_0 + h), \Pi) = o \left( h ^2 \right), \ h \to 0
\]

kjer je \(  f(h) = o(g(h)), h \to a \).
** Dokaz
*** <1>1
Case 1: \(  \gamma(t) = \left( \gamma_1(\tilde{t}), \gamma_2 (\tilde{t}), \gamma_3 (\tilde{t}) \right) \) za \(  \tilde{t} = t_0 + h \).
Case 2: \(  \vec{o}(h ^2) = \left( o(h ^2),  o(h ^2),  o(h ^2)  \right) \)

Velja

\[ d (\gamma(\tilde{t}), \Pi) = \left\langle \gamma(\tilde{t}) - \gamma(t_0), \frac{\dot{\gamma}(t_0) \times \ddot{\gamma}(t_0)}{\left| \dot{\gamma}(t_0)\times \ddot{\gamma}(t_0) \right|}  \right\rangle
\]

Dokaz:
Za razdaljo med vektorjem \(  \vec{R} \), ki kaže iz ravnine in poljubno ravnino \(  \Sigma \) z normalnim vektorjem \(  \vec{n}_{\Sigma} \) velja

\[ d \left( \vec{R}, \Sigma \right) = \left\langle \vec{R} - \vec{r}, \frac{\vec{n}_{\Sigma}}{\left| \vec{n}_{\Sigma} \right|} \right\rangle
\]
*** <1>2
Velja

\[ \left| \left\langle \dot{\gamma}(t_0) \cdot h ^2 + \ddot{\gamma}(t_0) \cdot \frac{h ^2}{2} + \vec{o}(h ^2), \vec{n} \right\rangle \right| = o(h ^2)
\]

Dokaz:
**** <2>1
\[ \gamma_i (\tilde{t}) = \gamma_i (t_0) + \dot{\gamma}_i (t_0) \cdot h + \ddot{\gamma}_i (t_0) \cdot \frac{ h ^2}{2} + o(h ^2), \quad i = 1, 2, 3
\]

Dokaz: Razvoj \(  \gamma_i (\tilde{t}) \) v Taylorjevo vrsto
**** <2>2

\begin{align*}
 \left| \left\langle \dot{\gamma}(t_0) \cdot h ^2 + \ddot{\gamma}(t_0) \cdot \frac{h ^2}{2} + \vec{o}(h ^2), \vec{n} \right\rangle \right| &= \left| \left\langle o(h ^2), \vec{n} \right\rangle \right| \\
& \le \left| o(h ^2) \right| = o(h ^2)
\end{align*}

Dokaz: Združimo <1>1 in <2>1, trikotniška neenakost in pa skalarni produkt pravokotnih vektorjev (\(  \dot{\gamma} \), \(  \ddot{\gamma} \) na \(  \vec{n} = \dot{\gamma} \times \ddot{\gamma} \)) je enak 0
**** <2>3 QED
*** <1>3 QED
* Definicija 4.1
Ploskev v \(  \mathbb{R} ^3 \) je podana s parametrizacijo \(  \vec{r} = \vec{r}(u, v): D \to \mathbb{R} \), pri čemer je \(  \vec{r}(u, v) = \left( X(u, v), Y(u, v), Z(u, v) \right) \) preslikava reda vsaj \(  C^2 \). Zahtevamo še, da je \(  \vec{r}_u \times \vec{r}_v \ne 0 \). V tem primeru pravimo, da je parametrizacija regularna. \(  u, v \) sta krivočrtni koordinati na ploskvi \(  M = \left\{ \vec{r}(u, v), \ (u, v)  \in D \right\} \)
* Definicija 4.2

(Afina) tangentna ravnina na ploskev \(  M \) skozi točko \(  m = \vec{r}(u, v) = (x_0, y_0, z_0) \) definiramo kot množico tangentnih vektorjev krivulj skozi to točko. Eksplicitno je to ravnina

\[ m + \mathrm{Lin} \left{ \vec{r}_u (u, v), \vec{r}_v (u, v) \right}
\]

Enačba tangentne ravnine je torej

\[ \left\langle (x, y, z) - \left( x_0, y_0, z_0 \right),  \left( \vec{r}_u \times \vec{r}_v \right)(u, v) \right\rangle
\]

/Opomba/: za predstavitev ravnine potrebujemo začetno točko \(  m \) ter bazna vektorja, ki razpenjata ravnino
** Dodatno:

Upoštevamo stvari definirane v definiciji 4.1

Zanima nas tangentna ravnina v točki \(  \vec{r}(u_0, v_0) \). Imamo krivuljo \(  \gamma: I \to D \), ki preslika \(  \gamma(t_0) = \left( \alpha(t), \beta(t) \right) = (u_0, v_0) \). Krivuljo preslikamo na ploskev \(  \vec{r} \circ \gamma: I \to M \).

\[  \frac{\mathrm{d} }{\mathrm{d} t} \vec{r}(\gamma(t)) = \vec{r}_u(\gamma(t)) \cdot \dot{\alpha}(t) + \vec{r}_v (\gamma(t)) \cdot \dot{\beta}(t)
\]

Pri \(  t_0 \) je to tangentni vektor na krivuljo \(  (\vec{r} \circ \gamma)(t_0) \)

\[ \vec{r}_u(\gamma(t_0)) \cdot \dot{\alpha}(t_0) + \vec{r}_v(\gamma(t_0)) \cdot \dot{\beta}(t_0) = a \cdot \vec{r}_u(u_0, v_0) + b \cdot \vec{r}_v (u_0, v_0)
\]

Kakor v opombi, sta \(  \vec{r}_u \) in \(  \vec{r}_v \) naša bazna vektorja.
* Implicitno podane ploskve

Funkcija \(  F: \mathbb{R} ^3 \to \mathbb{R} \) je funkcija 3 spremenljivk. Ploskev definiramo kot množico ničel oz. nivojnico

\[ M = \left\{ (x, y, z) \in \mathbb{R} ^3, F(x, y, z) = 0 \right\}
\]

z dodanim pogojem \(  \nabla F = \left( \frac{\partial F}{\partial x}, \frac{\partial F}{\partial y}, \frac{\partial F}{\partial z}  \right) \ne 0 \), kar je enakovredno \(  \vec{r}_u \times \vec{r}_v \ne 0 \) pri eksplicitni funkciji.
** Tangentna ravnina implicitno podane ploskve
Imamo točko \(  m = (x_0, y_0, z_0) \) na ploskvi \(  M \) in poljubno krivuljo, ki gre skozi to točko

\[ \vec{r}(t) = \left( x(t), y(t), z(t) \right)
\]

in leži na ploskvi \(  M \) za vsak \(  t \). Poleg tega imamo tudi funkcijo \(  F = F(x, y, z) \) in ker leži na ploskvi, po definiciji velja

\begin{equation}
\label{eq:1}
 F(x(t), y(t), z(t)) = 0
\end{equation}

Enačbo \ref{eq:1} odvajamo po \(  t \) in dobimo

\begin{align*}
  \frac{\mathrm{d} }{\mathrm{d} t} F(x, y, z) &= 0 \\
F_x \cdot \dot{x} + F_y \cdot \dot{y} + F_z \cdot \dot{z} &= 0 && \text{v točki } m\\
\left\langle \nabla F(m), \vec{r}(t_0) \right\rangle = 0
\end{align*}

Tangentni vektor krivulje \(  \odv{r}(t_0) \) leži v tangentni ravnini na ploskev \(  M \) v točki \(  m \), saj je krivulja v ravnini \(  M \). Vektor \(  \nabla F (m) \) je nanj pravokoten (saj je njun skalarni produkt enak 0), kar pomeni, da predstavlja normalni vektor ravnine. Enačba tangentne ravnine na ploskev \(  M \) v točki \(  m \) je torej

\[ \left\langle (x, y, z) - \vec{r}(t_0), \nabla F (\vec{r}(t_0)) \right\rangle = 0
\]
* Rotacijsko invariantne ploskve (vrtenine)

Način podajanja ploskev tako, da krivuljo v \(  xz \) ravnini zavtrimo okrog \(  z \) osi.

Začetna parametrizacija krivulje je

\[ \gamma(t) = \begin{bmatrix} x(t) \\ 0 \\ z(t) \end{bmatrix}, \ t \in I
\]

ki jo pomnožimo z rotacijsko matriko

\[ \begin{bmatrix}
\cos \phi & - \sin \phi & 0 \\
\sin \phi & \cos \phi & 0 \\
0 & 0 & 1
\end{bmatrix} \begin{bmatrix} x(t) \\ 0 \\ z(t) \end{bmatrix} = \begin{bmatrix} x(t) \cos \phi \\ x(t) \sin \phi \\ z(t)  \end{bmatrix}
\]
** Plašč valja

Daljico vzamemo za krivuljo \(  \gamma \):

\[ \gamma(t) = \begin{bmatrix} a \\ 0 \\ t \end{bmatrix}, \ t \in I
\]

in parametrizacija je torej

\[ \vec{r}(t, \phi) = \begin{bmatrix} a \cos \phi \\ a \sin \phi \\ t \end{bmatrix}, \ t \in I, \phi \in [0, 2\pi)
\]
** Stožec

Premica skozi izhodišče kot krivulja \(  \gamma \):

\[ \gamma(t) = \begin{bmatrix} t \\ 0  \\ at  \end{bmatrix}, t \in [0, b]
\]

Parametrizacija stožca je tako

\[ \vec{r}(t, \phi) = \begin{bmatrix} t \cos \phi \\ t \sin \phi \\ a \end{bmatrix}, t \in [0, b], \phi \in [0, 2\pi)
\]
** Sfera

Kot parametrizacijo vzamemo polkrožnico

\[ \gamma(t) = \begin{bmatrix} \cos t \\ 0 \\ \sin t \end{bmatrix}, t \in \left[ - \frac{\pi}{2},  \frac{\pi}{2} \right]
\]

Parametrizacija enotske sfere

\[ \vec{r}(t, \phi) = \begin{bmatrix} \cos t \cos \phi \\ \cos t \sin \phi \\ \sin t \end{bmatrix}, t \in  \left[ - \frac{\pi}{2},  \frac{\pi}{2} \right], \phi \in [0, 2 \pi)
\]
** Torus

Kot parametrizacijo vzamemo krožnico s polmerom \(  r \) na oddaljenosti \(  a \) od izhodišča:

\[ \gamma(t) = \begin{bmatrix} a + r \cos t \\ 0 \\ r \sin t \end{bmatrix}, t \in [0, 2\pi)
\]

Parametrizacija torusa je

\[ \vec{r}(t, \phi) = \begin{bmatrix} (a + r \cos t)\cos \phi \\ (a + r \cos t)\sin \phi  \\ r \sin t \end{bmatrix}, \ t \in [0, 2\pi), \phi \in [0, 2 \pi)
\]
* Površina ploskve
** Lagrangeov izrek
Predpostavke:
- \(  a, b \in \mathbb{R}, \ a < b \)
- \(  f: [a, b] \to \mathbb{R} \) zvezna funkcija
- \(  f \) odvedljiva na \(  (a, b) \)

Obstaja \(  c \in (a, b) \), da je

\[ f(b) - f(a) = f'(c)(b - a)
\]
*** Dokaz
**** <1>1
Case 1: \(  h(x) = f(x) (b - a) - x (f(b) - f(a)) \), zvezna na \(  [a, b] \), odvedljiva na \(  (a, b) \)

Velja

\begin{align*}
  h(a) &= f(a) (b - a) - a(f(b) - f(a)) = f(a) b - f(b) a \\
h(b) &= f(b) (b - a) - b(f(b) - f(a)) = - a f(b) + b f(a)
\end{align*}

Dokaz: Case 1
**** <1>2

\[ 0 = h'(c) = f'(c) (b - a) - (f(b) - f(a))
\]

Dokaz: <1>1 velja Rolleov izrek, \(  h'(x) \) obstaja po Case 1
**** <1>3 QED
Dokaz: <1>2
** Ploščina paralelograma
Predpostavke:
- parametrizacije ploskve \(  \vec{r}: D \to \mathbb{R} ^3 \)
*** <1>1
Majhen pravokotnik \(  P \) z oglišči v \(  (u, v) \) in stranicama \(  \Delta u \), \(  \Delta v \) preslikamo v \(  \vec{r} \).

Za dovolj majhen pravokotnik \(  P \) dobimo približno linearno preslikavo \(  \vec{r}(P) \), ki ga lahko aproksimiramo s ploščino paralelograma z oglišči \(  \vec{r}(u, v), \ \vec{r}(u + \Delta u, v), \vec{r}(u, v + \Delta v), \vec{r}(u + \Delta u, v + \Delta v) \).
*** <1>2

Velja

\begin{align*}
  \vec{r}(u + \Delta u, v) - \vec{r}(u, v) &= \vec{r}_u (u + \xi \Delta u, v) \Delta u && \xi \in (0, 1) \\
  \vec{r}(u, v + \Delta v ) - \vec{r}(u, v) &= \vec{r}_v (u, v  + \eta \Delta v) \Delta v && \eta \in (0, 1) \\
\end{align*}

Dokaz: Lagrangeov izrek za posamezno spremenljivko in definicija, da je \(  \vec{r} \in C^1 \)
*** <1>3

\begin{align*}
  \vec{r}_u(u + \xi \Delta u, v) &= \vec{r}_u (u, v) \\
\vec{r}_v (u, v + \eta \Delta v) &= \vec{r}_v (u, v)
\end{align*}

Dokaz: za majhne \( \xi, \eta  \) to se lahko aproksimira
*** <1>4

Ploščina paralelograma je pribložno enaka

\[ \left| \vec{r}_u \times \vec{r}_v \right| \Delta u \Delta v
\]

Dokaz: <1>3, <1>2
* Definicija 4. 8

Naj bo \(  D \subseteq \mathbb{R} ^2 \) območje in \(  \vec{r}: D \to \mathbb{R} ^3 \) parametrizirana ploskev \(  M = \left\{ \vec{r}(u, v); \ (u, v) \in D \right\} \). Njeno površino izračunamo kot

\[ P(M) = \iint\limits_D^{} \left| \vec{r}_u \times \vec{r}_v \right| \,\mathrm{d S}
\]
** Opomba

Oznaka \(  \left\lVert \cdot \right\rVert \) označuje normo.

\begin{align*}
  \left\lVert \vec{r}_u \times \vec{r}_v \right\rVert ^2 &= \left\lVert \vec{r}_u \right\rVert ^2 \left\lVert \vec{r}_v \right\rVert ^2 \sin \phi \\
&= \left\lVert \vec{r}_u \right\rVert ^2 \left\lVert \vec{r}_v \right\rVert ^2 \left( 1 - \cos ^2 \phi \right) \\
&= \left\lVert \vec{r}_u \right\rVert ^2 \left\lVert \vec{r}_v \right\rVert ^2 - \left| \left\langle \vec{r}_u, \vec{r}_v \right\rangle \right| ^2
\end{align*}

Z oznakami
\[ \left\lVert \vec{r}_u \right\rVert ^2 = E; \ \left\lVert \vec{r}_v \right\rVert ^2 = G; \ \left\langle \vec{r}_u, \vec{r}_v \right\rangle = F
\]

\[ P(M) = \iint\limits_D^{} \sqrt{EG - F ^2} \,\mathrm{d S}
\]
* Trditev 4.9

Definicija za površino ploskve je dobra (neodvisna od parametrizacije).
** Dokaz
*** <1>1
Case 1: \(  \vec{r}: D \to M \) parametrizacija ploskve \(  M \)
Case 2: \(  \vec{\rho} : \Delta \to M \) druga parametrizacija ploskve \(  M \)
Case 3: \(  \Phi: D \to \Delta, \ (x, y) \mapsto (U(x, y), V(x, y)) \) gladka bijekcija \(  \vec{\rho} = \vec{r} \circ \Phi \)

\begin{align*}
  \vec{\rho}_x &= \vec{r}_u \cdot U_x + \vec{r}_v \cdot V_x \\
\vec{\rho}_y &= \vec{r}_u \cdot U_y + \vec{r}_v \cdot V_y
\end{align*}

Dokaz: Verižno pravilo parcialnega odvoda \(  \vec{\rho} \).
*** <1>2

\[ \vec{\rho}_x \times \vec{\rho}_y = \det (J\Phi) \vec{r}_u \times \vec{r}_v
\]

Dokaz: Analiza 1 ter \(  \vec{r}_i \times \vec{r}_i = 0  \)

\begin{align*}
  \vec{\rho}_x \times \vec{\rho}_y &= \left( U_x \cdot V_y - V_x \cdot U_y \right) \cdot (\vec{r}_u \times \vec{r}_v) \\
&= \begin{vmatrix}
 U_x & U_y \\
V_x & V_y
 \end{vmatrix} \cdot (\vec{r}_u \times \vec{r}_v)
\end{align*}
*** <1>3 QED
Dokaz:

\begin{align*}
  P(M) &= \iint\limits_D^{} \left| \vec{r}_u \times \vec{r}_v (u, v) \right|  \,\mathrm{d S} \\
&= \iint\limits_{\Delta}^{} \left| \vec{r}_u \times \vec{r}_v (\Phi(x, y) \right| \left| \det (J \Phi) \right|\,\mathrm{d P} \\
&= \iint\limits_{\Delta}^{} \left| \vec{\rho}_x \times \vec{\rho}_y \right| \,\mathrm{d P}
\end{align*}
* Definicija 4.11

Lokalna orientacija gladke regularne krivulje \(  \Gamma \) brez samopresečišč v točki \(  \gamma \in \Gamma \) je podana z izbiro enotskega tangentnega vektorja v tej točki (imamo samo dve možni izbiri).

Globalna orientacija je podana z zvezno izbiro enotskih tangentnih vektorjev v vsaki točki \(  \gamma \in \Gamma \).
* Definicija 4.12

Lokalna orientacija gladke regularne ploskve \(  M \subseteq \mathbb{R} ^3 \) je izbira enotske normalne v točki \( m \in M \)

Globalna orientacija ploskve \(  M \) je zvezna izbira enotskih normalnih vektorjev za vse \(  m \in M \):


\begin{align*}
  \vec{n}:M &\to S ^2 \\
m & \mapsto \vec{n}(m)
\end{align*}

* Definicija 4.13
Naj bo \(  M \) orientabilna ploskev z robom \(  \partial M \). Za vsako točko \(  m \in \partial M \) naj bo \(  \vec{\mu} \) tisti enotski vektor iz tangentne ravnine \(  T_mM \), ki je pravokoten na \(  T_m\partial M \) (tangentno premico na \(  \partial \) v točki \(  m \)) in kaže ven iz \(  M \), in naj bo \(  \vec{n} \) enotski normalni vektor na \(  M \), podan z orientacijo.

Potem vektor \(  \vec{n} \times \vec{\mu} \) določa inducirano orientacijo roba \(  \partial M \) v točki \(  m \in \partial M \).
* Definicija 5.1
Naj bo \(  \Omega \subseteq \mathbb{R} ^3 \). Skalarno polje na \(  \Omega \) je funkcija \(  f: \Omega \to \mathbb{R} \). Vektorsko polje na \(  \Omega \) je preslikava \(  \vec{F}: \Omega \to \mathbb{R} ^3 \).

Definiramo nablo: \(  \nabla = \left( \frac{\partial }{\partial x}, \frac{\partial }{\partial y}, \frac{\partial }{\partial z}    \right) \)
* Standardni diferencialni operatorji v poljubnih ortogonalnih koordinatah
Vzamemo nabor ortogonalnih koordinat \(  \vec{\xi} = \left( \xi_1, \xi_2, \xi_3 \right) \) v \(  \mathbb{R} ^3 \). S parametrizacijo prostora \(  \mathbb{R} ^3 \) \(  \vec{r} \) dobimo kartezične koordinate

\[ \vec{r} = \vec{r}(\xi)
\]

Zahtevamo za vsak \(  \vec{\xi} \) in \(  \vec{r}_j = \vec{r}_j \left( \vec{\xi} \right) = \frac{\partial \vec{r}}{\partial \xi_j}  \), da velja

\[ \left\langle \vec{r}_j, \vec{r}_k \right\rangle _{\mathbb{R} ^3} = 0 \text{ za } j \ne k
\]

/Opomba/: z drugimi besedami, smerni odvodi oz. tangentni vektorji so me seboj ortogonalni v vsaki točki.
* Definicija 5.8 (Laméjevi koeficienti)
Laméjevi koeficienti so

\[ H_j = \left| \vec{r}_j \right| , \ j = 1, 2, 3
\]

in označimo

\[ H = H_1 H_2 H_3
\]

Definiramo še enotske tangentne vektorje na koordinate krivulje

\[ \vec{\eta}_j = \frac{\vec{r}_j}{H_j} = \frac{\vec{r}_j}{\left| \vec{r}_j \right|}
\]
* Definicija 5.2 (gradient)
Gradient skalarnemu polju \(  f \) priredi vektorsko polje \(  \nabla f \) na sledeč način

\[ \mathrm{grad} f = \nabla f = \left( \frac{\partial f}{\partial x}, \frac{\partial f}{\partial y}, \frac{\partial f}{\partial z}    \right)
\]
* Definicija 5.3 (divergenca)
Divergenca vektorskemu polju \(  \vec{F} = (U, V, W) \) priredi skalarno polje \(  \nabla \cdot \vec{F} \) na

\[ \mathrm{div} \vec{F} = X_x + Y_y + Z_z
\]
* Definicija 5.4 (rotor)
Rotor vektorskemu polju \(  \vec{F} = (U, V, W) \) priredi vektorsko polje \(  \nabla \times \vec{F}  \) na sledeč način

\[ \mathrm{rot} \vec{F} = (Z_y - Y_z, X_z - Z_x, Y_x - X_y)
\]
* Laplaceov operator

\[ \Delta = \mathrm{div} \circ \nabla = \frac{\partial ^2}{\partial x ^2} +  \frac{\partial ^2}{\partial y ^2 } + \frac{\frac{\partial  ^2}{\partial z ^2 }
\]
* Trditev 5.9
Predpostavke:

- nabor ortogonalnih koordinat \(  \vec{\xi} = \left( \xi_1, \xi_2, \xi_3 \right) \) v \(  \mathbb{R} ^3 \)
- skalarno polje \(  u: \mathbb{R} ^3 \to \mathbb{R} \)
- \(  U \) je izražava \(  u(\vec{x}) \) v \(  \xi \), torej \(  U(\vec{\xi}) = u \left( \vec{r} \left( \vec{\xi} \right) \right) \) oz. \(  U = u \circ \vec{r} \)

/Opomba/: \(  \vec{x} \) so kartezične in \(  \epsilon \) so poljubne koordinate

Velja

\[ \left( \nabla_{\vec{x}} u \right) \left( \vec{r} \right) = \left\langle \nabla_{\vec{\xi}} U, \begin{bmatrix} \frac{\vec{\eta}_1}{H_1}  \\ \frac{\vec{\eta}_2}{H_2} \\ \frac{\vec{\eta}_3}{H_3} \end{bmatrix} \right\rangle
\]
** Dokaz
*** <1>1
Case 1: \(  \vec{r} = (X, Y, Z) \)

Velja

\[ \frac{\partial U}{\partial \xi_j} = \left\langle \left( \nabla_{\vec{x}} u \right) \left( \vec{r}(\vec{\xi}) \right), \vec{r}_j (\vec{\xi}) \right\rangle
\]

Dokaz:
**** <2>1

\[ U(\vec{\xi}) = u \left( X (\vec{\xi}), Y(\vec{\xi}), Z(\vec{\xi}) \right) = u \left( \vec{r}(\vec{\xi}) \right)
\]

Dokaz: Case 1
**** <2>2

\[ \frac{\partial U}{\partial \xi_j} = \frac{\partial u}{\partial x} \left( \vec{r}(\vec{\xi}) \right) \cdot \frac{\partial X}{\partial \xi_j} \left( \vec{\xi} \right) + \frac{\partial u}{\partial y} \left( \vec{r}(\vec{\xi}) \right) \cdot \frac{\partial Y}{\partial \xi_j} \left( \vec{\xi} \right) + \frac{\partial u}{\partial z} \left( \vec{r}(\vec{\xi}) \right) \cdot \frac{\partial Z}{\partial \xi_j} \left( \vec{\xi} \right)
\]

Dokaz: <2>1 in verižno pravilo odvajanja
**** <2>3 QED
Dokaz: <2>2 se lahko zapiše kot

\[ \frac{\partial U}{\partial \xi_j} =  \left\langle \left( \nabla_{\vec{x}} u  \right) \left( \vec{r}(\vec{\xi}) \right), r_j \left( \vec{\xi} \right)  \right\rangle
\]
*** <1>2

\[ \left\langle \left( \nabla_{\vec{x}}u \right) \left( \vec{r} \left( \vec{\xi} \right) \right), \vec{r}_j \left( \vec{\xi} \right) \right\rangle = H_j \left\langle \left( \nabla_{\vec{x}} u \right) \left( \vec{r}\left( \vec{\xi} \right) \right), \vec{\eta}_j \right\rangle
\]

Dokaz: definicija Laméjevih koeficientov \(  \vec{r}_j = H_j \cdot \vec{\eta}_j \)
*** <1>3

\[ \left( \nabla_{\vec{x}} u \right) \left( \vec{r} \right) = \sum\limits_{j = 1}^3 \left\langle  \left( \nabla_{\vec{x}} u \right) \left( \vec{r} \right), \vec{\eta}_j  \right\rangle \cdot \vec{\eta}_j
\]

Dokaz: Ortonormirano bazo, kar \(  \vec{\eta}_j \) je, se zapiše za vsak \(  \vec{v} \in \mathbb{R} ^3 \) zapiše kot

\[ \vec{v} = \sum\limits_1^3 \left\langle \vec{v}, \vec{\eta}_j \right\rangle \cdot \vec{\eta}_j
\]

*** <1>4

\[ \sum\limits_{j = 1}^3 \left\langle \left( \nabla_{\vec{x}} u \right) \left( \vec{r} \right), \vec{\eta}_j \right\rangle \cdot \vec{\eta}_j = \left\langle \begin{bmatrix} \frac{\partial U}{\partial \xi_1} \\ \frac{\partial U}{\partial \xi_2}  \\ \frac{\partial U}{\partial \xi_3}  \end{bmatrix}, \begin{bmatrix} \frac{\vec{\eta}_1}{H_1} \\ \frac{\vec{\eta}_2}{H_2} \\ \frac{\vec{\eta}_3}{H_3} \end{bmatrix} \right\rangle
\]

Dokaz: linearna algebra

\begin{align*}
  \sum\limits_{j = 1}^3 \left\langle  \left( \nabla_{\vec{x}} u \right) \left( \vec{r} \right), \vec{\eta}_j \right\rangle \cdot \vec{\eta}_j &=  \sum\limits_{j= 1}^3 \frac{1}{H_j} \cdot \frac{\partial U}{\partial \xi_j} \cdot \vec{\eta}_j \\
&= \sum\limits_{j = 1}^3 \frac{\partial U}{\partial \xi_j} \cdot \frac{\vec{\eta}_j}{H_j}
\end{align*}
*** <1>5 QED
Dokaz: <1>4
* Lema

Predpostavke:
- nabor ortogonalnih koordinat \(  \vec{\xi} = \left( \xi_1, \xi_2, \xi_3 \right) \) v \(  \mathbb{R} ^3 \)
- \(  U \) je izražava \(  u(\vec{x}) \) v \(  \xi \), torej \(  U(\vec{\xi}) = u \left( \vec{r} \left( \vec{\xi} \right) \right) \) oz. \(  U = u \circ \vec{r} \)
- Predpostavka 1: Definiramo inverz \(  \vec{R} = \vec{r}^{-1} \), kjer velja

\[ x = \vec{r}(\vec{\xi}) \iff \vec{\xi} = \vec{R}(\vec{x})
\]

Dokaži

\[ \mathrm{rot}_{\vec{x}} \left( \frac{\vec{\eta}_j}{H_j} \circ \vec{R} \right)
\]

** Dokaz
*** <1>1
Case 1: \(  k = 1, 2, 3 \)
Case 2:

\(  U_k \left( \vec{\xi} \right) = \xi_k \)


Velja

\[ \frac{\partial U_k }{\partial \xi_k} = \delta_{jk} = \begin{cases}
1; \ k = j \\
0; \ k \ne j
\end{cases}
\]

Dokaz: Case 2
*** <1>2 QED
Case 2: \(  U_k \left( \vec{\xi} \right) = u_k \left( \vec{x} \right) \)

\[ \mathrm{rot} \left( \nabla u_{k} \left( \vec{r} \right) \right) = \mathrm{rot} \left( \frac{\vec{\eta}_k}{H_k} \circ \vec{R} \right) = 0
\]

Dokaz:

\[ \mathrm{rot} \circ \nabla = 0
\]

ter
\begin{align*}
\mathrm{rot} \left( \nabla u_k (\vec{r}) \right) &= \sum\limits_{k = 1}^3 \mathrm{rot} \left[ \left( \frac{\partial U}{\partial \xi_k} \cdot \frac{\vec{\eta}_k}{H_k} \circ \vec{R}  \right) \right] \\
&= \mathrm{rot} \left( \frac{\vec{\eta}_k}{H_k} \circ \vec{R} \right)
\end{align*}

za <1>2
* Posledica 1

\[ \mathrm{div} \left( \frac{\vec{r}_j}{H} \circ \vec{R} \right) = 0, \ \forall j
\]

/Opomba/: Pri Laméjevih koeficientih smo definirali \(  H = H_1 H_2 H_3 \), kar pomeni za \(  i, j, k \)

\[ \mathrm{div} \left( \frac{\vec{\eta}_i}{H_j H_k} \circ \vec{R} \right)
\]
** Dokaz:
*** <1>1

Velja

\[ \vec{\eta}_1 + \pm \vec{\eta}_2 \times \vec{\eta}_3
\]

Dokaz: \(  \left\{ \eta_j \right\} \) je ortonormirana baza za \(  \mathbb{R} ^3 \)
*** <1>2

\[ \mathrm{div} \left( \frac{\vec{\eta}_i}{H_j H_k} \right) = \pm \mathrm{div} \left( \frac{\vec{\eta}_j}{H_j} \times \frac{\vec{\eta}_k}{H_k} \right) = \left\langle \mathrm{rot} \left( \frac{\vec{\eta}_j}{H_j} \right), \frac{\vec{\eta}_k}{H_k} \right\rangle - \left\langle \mathrm{rot } \left( \frac{\vec{\eta}_k}{H_k} \right) , \frac{\vec{\eta}_j}{H_j}\right\rangle
\]

Dokaz:

Velja \(  \mathrm{div} \left( \vec{F} \times \vec{G} \right) = \left\langle \mathrm{rot } \vec{F}, \vec{G} \right\rangle - \left\langle \vec{F}, \mathrm{rot } \vec{G} \right\rangle\)
*** <1>3 QED

<1>2 je \(  0 - 0 \) zaradi leme
* Posledica 2

Predpostavka 1: \(  A_j = \frac{1}{H_j} \frac{\partial U}{\partial \xi_j}  \)

Velja

\[ \mathrm{div} \left[ \left( A_j \vec{\eta}_j \right) \circ  \vec{R} \right] = \left[ \frac{1}{H} \frac{\partial }{\partial \xi_j} \left( \frac{H}{H_j ^2} \frac{\partial U}{\partial \xi_j}  \right)  \right] \circ \vec{R}
\]
** Dokaz
*** <1>1
Case 1: \(  j = 1 \)

\[ \mathrm{div} \left( A_1 \vec{\eta}_1 \right) = \mathrm{div} \left( A_1 H_2 H_3 \cdot \frac{\vec{\eta}_1}{H_2 H_3} \right) = \left\langle \nabla \left( A_1 H_2 H_3 \right), \frac{\vec{\eta}_1}{H_2 H_3} \right\rangle + A_1 H_2 H_3 \cdot \mathrm{div} \left( \frac{\vec{\eta}_1}{H_2 H_3} \right)
\]

Dokaz:

Velja

\[  \mathrm{div} \left( \phi \vec{F} \right) = \left\langle \nabla \phi, \vec{F} \right\rangle_{\mathbb{R} ^3} + \phi \mathrm{div} \vec{F}
\]

*** <1>2

\[ \left\langle \nabla \left( A_1 H_2 H_3 \right), \frac{\vec{\eta}_1}{H_2 H_3} \right\rangle = \left\langle \nabla \left( \frac{H_2 H_3}{H_1} \frac{\partial U}{\partial \xi_1} , \frac{\vec{\eta}_1}{H_2 H_3} \right) \right\rangle = \frac{1}{H} \left\langle  \nabla \left( \frac{H}{H_1 ^2} \frac{\partial U}{\partial \xi_1}  \right), \vec{r}_1 \right\rangle
\]


Dokaz:

Velja \(  \vec{\eta}_1 = \frac{\vec{r}_1}{ \left| \vec{r}_1 \right|} = \frac{\vec{r}_1}{H_1} \) in potem posledično

\[ \frac{\vec{\eta}_1}{H_2 H_3} = \frac{\vec{r}_1}{H_1 H_2 H_3} = \frac{\vec{r}_1}{H}
\]

in predpostavka 1.
*** <1>3 QED

\[ \frac{1}{H} \left\langle \nabla \left( \frac{H}{H_1 ^2} \frac{\partial U}{\partial \xi_1}  \right), \vec{r}_1 \right\rangle = \frac{\partial }{\partial \xi_1} \left( \frac{H}{H_1 ^2} \frac{\partial U}{\partial \xi_1} \circ \vec{R}  \right)
\]

Dokaz:

Z verižnim pravilom iz desne strani dobimo, levo
* Izrek

\[  \Delta u = \frac{1}{H} \sum\limits_{j = 1}^3 \frac{\partial }{\partial \xi_j} \left( \frac{H}{H_j ^2} \cdot \frac{\partial U}{\partial \xi_j}  \right) \circ \vec{R}
\]
** Dokaz:
*** <1>1

\[ \Delta u = \mathrm{div} \left( \nabla u \right) = \sum\limits_{j = 1}^{ 3} \mathrm{div} \left[ A_j \vec{\eta}_j \circ \vec{R} \right]
\]
*** <1>2 QED
Upoštevamo posledico 2
* Definicija 6.1

Naj bo \(  \vec{r}: I \to \mathbb{R} ^3 \) regularna parametrizacija neke krivulje \(  \Gamma \) in \(  u: \Gamma \to \mathbb{R} \) zvezna. Integral skalarnega polja \(  u \) po \(  \Gamma \) definiramo kot

\[ \int\limits_{\Gamma}^{} u \, \mathrm{ds} = \int\limits_I^{} u(\vec{r}(t)) \left| \odv{r}(t) \right|\, \mathrm{dt}
\]
* Trditev 6.2

Definicija 6.1 je dobra.
** Dokaz:
*** <1>1
Case 1: \(  I = [a, b] \in \mathbb{R} \)
Case 2: \(  J = [\alpha, \beta] \in \mathbb{R} \)
Case 3: Druga parametrizacija \(  \vec{R}: J \to \mathbb{R} ^3 \) in \(  \phi: J \to I \) in tao velja \(  \vec{R} = \vec{r} \circ \phi \)

Prove:

\[ \int\limits_{\alpha}^{ \beta} u \left( \vec{R}(s) \right) \left| \odv{R} (s) \right| \, \mathrm{ds} = \int\limits_{\alpha}^{\beta} u(\vec{r}(\phi(s))) \cdot \left| \vec{r}(\phi(s)) \right| \, \mathrm{ds}
\]

Dokaz: Upoštevali smo \(  \vec{R} = \vec{r} \circ \phi \)
*** <1>2

\[ \int\limits_{\alpha}^{\beta} u \left( \vec{r}(\phi(s)) \right) \cdot \left| \vec{r}(\phi(s)) \right|\dot{} \, \mathrm{ds} = \int\limits_{\alpha}^{\beta} u \left( \vec{r}(\phi(s)) \right) \left| \odv{r}(\phi(s)) \cdot \dot{\phi}(s) \right|
\]

Dokaz: Verižno pravilo
*** <1>3
Case 4: \(  \phi(s) = w \)

\[ \int\limits_{\alpha}^{\beta} u \left( \vec{r}(\phi(s)) \left| \odv{r} \left( \phi(s)) \right) \cdot \dot{\phi}(s) \right| \right) \, \mathrm{ds} = \int\limits_a^b u \left( \vec{r}(w)\right) \left| \odv{r} (w) \right| \, \mathrm{dw}
\]

Dokaz:

\[ \dot{\phi}(s) = \dot{w}(s)
\]

ter menjava spremenljivk v integralu.
*** <1>4 QED

Imamo dve možnosti:

\[ \begin{cases}
(\alpha, \beta) \mapsto (a, b), \ \dot{\phi} > 0 \\
\left( \alpha, \beta) \mapsto (b, a), \ \dot{\phi} < 0 \right)
\end{cases}
\]
* Definicija 6.4

Naj bo \(  \vec{F}: \Gamma \to \mathbb{R} ^3 \) zvezna. Integral vektorskega polja \(  \vec{F} \) po \(  \Gamma \) definiramo kot

\[ \int\limits_{\Gamma}^{} \vec{F} \, \mathrm{d} \vec{r} = \int\limits_a^b \left\langle \vec{F}\left( \vec{r}(t)) \right), \odv{r}(t) \right\rangle \, \mathrm{ dt}
\]
* Trditev 6.5

Če v definiciji nadomestimo \(  \vec{r} \) z drugo parametrizacijo \(  \vec{R} \) iste krivulje, tedaj je novi izraz

\[ \int\limits_{\Gamma}^{} \left\langle \vec{F} \circ \vec{R}, \odv{R} \right\rangle \, \mathrm{dx}
\]

- enak, če \(  \vec{R} \) ohranja orientacijo
- nasprotno enak, če \(  \vec{R} \) obrne orientacijo.
** Dokaz
*** <1>1
Case 1: \(  I = [a, b] \in \mathbb{R} \)
Case 2: \(  J = [\alpha, \beta] \in \mathbb{R} \)
Case 3: Druga parametrizacija \(  \vec{R}: J \to \mathbb{R} ^3 \) in \(  \phi: J \to I \) in tao velja \(  \vec{R} = \vec{r} \circ \phi \)
* Definicija 6.8
Vektorsko polje \(  \vec{F}: \Omega \to \mathbb{R} ^3 \), kjer je \(  \Omega \subseteq \mathbb{R} ^3 \) odprta množica, je potencialno, če obstaja skalarno polje \(  u: \Omega \to \mathbb{R} \), da je \(  \vec{F} = \mathrm{grad} u = \nabla u \). Funkcijo \(  u \) imenujemo potencial polja \(  \vec{F} \).
* Trditev 6.9
Naj bo \(  \Gamma \) regularna krivulja med točkama \(  A, B \in \mathbb{R} ^3 \) in naj bo \(  \vec{F} = \nabla u \) potencialno vektorsko polje. Potem je

\[ \int\limits_{\Gamma}^{} \vec{F} \mathrm{d} \vec{r} = u(B) - u(A)
\]
** Dokaz
*** <1>1

\[ \int\limits_{\Gamma}^{} \vec{F} \mathrm{d} \vec{r} = \int\limits_{\Gamma}^{} \nabla u \mathrm{d} \vec{r}
\]

Dokaz: Predpostavka iz trditve
*** <1>2
Case 1: parametrizacija \( \vec{r}: [\alpha, \beta] \to \Gamma  \)

\[ \int\limits_{\Gamma}^{} \nabla u \mathrm{d} \vec{r} = \int\limits_{\alpha}^{\beta} \left\langle \left( \nabla u \right) \circ \vec{r}, \odv{r} \right\rangle_{\mathbb{R} ^3} \mathrm{dt}
\]

Dokaz: Definicija integrala vektorskega polja
*** <1>3
\[ \int\limits_{\Gamma}^{} \frac{\mathrm{d} }{\mathrm{d} t} \left( u \circ \vec{r} \right) \, \mathrm{ dt}
\]

Dokaz: Verižno pravilo
*** <1>4

\[ \int\limits_{\alpha}^{\beta} \frac{\mathrm{d} }{\mathrm{d} t} \left( u \circ \vec{r} \right) \, \mathrm{dt} = \left( u \circ \vec{r} \right) \left( \beta \right) - \left( u \circ \vec{r} \right) \left( \alpha \right)
\]

Dokaz: Osnovni izrek analize
*** <1>5 QED

\[ \left( u \circ \vec{r} \right) \left( \beta \right) - \left( u \circ \vec{r} \right) \left( \alpha \right) = u (B) - u(A)
\]
* Trditev 6.10
Predpostavke 1: \(  \Omega \subset \mathbb{R} ^3 \) povezana odprta množica
Predpostavka 2: \(  \vec{F}: \Omega \to \mathbb{R} ^3 \)

1) \(  \vec{F} \) je potencialno
2) integral \(  \vec{F} \) po vsaki sklenjeni krivulji je enak 0
3) za vsak \(  A, B \subset \Omega \) je integral \(  \vec{F} \) od \(  A \) do \(  B \) neodvisno od izbire poti med točkama
** Dokaz:
*** <1>1
\(  1 \implies 2 \)

Dokaz:
**** <2>1
Case 1: \(  \Gamma \) sklenjena krivulja v \(  \Omega \)
Case 2: \(  A \in \Gamma \)

\[ \oint\limits_{\Gamma}^{} \vec{F} \mathrm{d}\vec{r}  = u(A) - u(A) = 0
\]

Dokaz: Trditev 6.9
**** <2>2 QED
*** <1>2

\(  2 \implies 3 \)

Dokaz:
**** <2>1
Case 1: \(  \Gamma_1 \) in \(  \Gamma_2 \) sta dve krivulji, ki povezujeta točki \(  A \) in \(  B \)
Case 2: \(  \Gamma = \Gamma_1 \cup \left( - \Gamma_2 \right) \), kjer je \(  -\Gamma_2 \) krivulja \(  \Gamma_2 \) z nasprotno orientacijo.

\[ \int\limits_{\Gamma}^{} \vec{F} \mathrm{d} \vec{r} = 0
\]

Dokaz: 2)
**** <2>2

\[ \int\limits_{\Gamma_1}^{} \vec{F} \mathrm{d} \vec{r} + \int\limits_{- \Gamma_2}^{} \vec{F} \mathrm{d}\vec{r} = \int\limits_{\Gamma_1}^{} \vec{F} \mathrm{d}\vec{r} - \int\limits_{\Gamma_2}^{} \vec{F} \mathrm{d} \vec{r} = 0
\]


Dokaz: Trditev 6.5 za spremembo predznaka
**** <2>3 QED

Dokaz: <2>2

\[ \int\limits_{\Gamma_1}^{} \vec{F} \mathrm{d}\vec{r} = \int\limits_{\Gamma_2}^{} \vec{F} \mathrm{d} \vec{r}
\]
*** <1>3

\(  3 \implies 1 \)
**** <2>1
Case 1: \(  \vec{F} = \left( U, V, W \right) = \nabla u \)
Case 2: \(  \Gamma \) je pote od \(  A \) do \(  B \)

Definiramo funkcijo

\[ u(B) = u(A) + \int\limits_{\Gamma}^{} \vec{F} \mathrm{d} \vec{r}
\]

kjer je \(  u(A) \) konstanten.
Dokaz: Trditev 6.9
**** <2>2

\[ \nabla (u + C) = \vec{F}
\]

za konstanto \(  C \in \mathbb{R} \).

Dokaz: Case 1 in odvod po konstanti
**** <2>3

\[ u(A) = 0
\]

Dokaz: Gradient je po <2>2 in <2>1 določen do aditivne konstante natančno
**** <2>4
Case 3: \(  \Gamma \) je poljubna pot od \(  A \) do \(  T \) znotraj \(  \Omega \)

\[ u(T) = \int\limits_{\Gamma}^{} \vec{F} \mathrm{d} \vec{r}
\]

je dobro definiran.

Dokaz: Predpostavka
**** <2>5

Velja

\[ \nabla u = \vec{F}
\]
***** <3>1
Case 1: \(  \Gamma_1 \) je poljubna pot od \(  A \) do \(  (x, y, z) \)
Case 2: \(  \Gamma_2 \) je poljubna pot od \(  A \) do \(  (x + h, y, z) \)

\[ u_x = \lim_{h \to 0} \frac{1}{h} \left[ u(x + h, y, z) - u(x, y, z) \right] = \lim_{h \to 0} \frac{1}{h} \left[ \int\limits_{\Gamma_2}^{} \vec{F} \mathrm{d}\vec{r} - \int\limits_{\Gamma_1}^{} \vec{F} \mathrm{d} \vec{r} \right]
\]

Dokaz: Definicija odvoda funkcije \(  u \) po \(  x \) ter <2>4
***** <3>2
Case 3: \(  \Gamma_3 \) je daljica \(  \left( x, y, z \right) \) do \(  \left( x + h, y, z \right) \)

Velja \(  \Gamma_2 = \Gamma_1 \cup \Gamma_3 \)

Dokaz: \(  \Gamma_2  \) je poljubna pot
***** <3>3
Case 4: parametriziramo \(  \Gamma_2 \) \(  \vec{r}(t) = \left( x + ht, y, z \right), t \in [0, 1] \)
Case 5: \(  \odv{r} = \left( h, 0, 0 \right) \)

\[ u(x + h, y, z) - u(x, y, z) = \int\limits_{\Gamma_3}^{} \vec{F} \mathrm{d} \vec{r} = \int\limits_0^1 \vec{F}\left( \vec{r}(t) \right) \cdot \odv{r} \mathrm{dt} = \int\limits_0^1 U \left( x + h, y, z \right) h \mathrm{dt}
\]

Dokaz: <2>4, <3>2 ter Case 4 in Case 5
***** <3>4 QED

\[ u_x = \lim_{h \to 0} \frac{1}{h} \int\limits_0^1 h \cdot U (x + h, y, z) \mathrm{dt} = U(x, y, z)
\]

Dokaz: upoštevamo <3>1, <3>3, ter, da je U zvezna in posledično tudi integral.

Analogno še za \(  y \) in \(  z \).
**** <2>6 QED
Dokaz <2>5
*** <1>4 QED
* Izrek 6.12
Delo rezultante sil (= vsote vseh sil), ki delujejo na delec, je enako spremembi kinetične energije. Ker je celotna energija enaka vsota kinetične in potencialne energije, je delo enako negativni spremembi potencialne energije

\[ A = - \Delta u = U(r_0) - U(r_1)
\]
* Definicija 6.14
Območje \(  \Omega \subset \mathbb{R} ^3 \) je zvezdasto, če obstaja \(  \omega_0 \in \Omega \) tako, da velja za vsak \(  \omega \in \Omega \) je daljica \(  \left[ \omega_0, \omega \right] \) cela vsebovana v \(  \Omega \).

\[ \left[ \omega_0, \omega \right] = \left\{ (1 - t) \omega_0 + t \omega; \ t \in [0, 1] \right\}
\]

/Opomba/: Konveksna množica je množica, ki vsebuje vse daljice med dvema poljubnima točkama iz množice. Posledično je vsaka konveksna množica zvezdasta.
* Izrek 6.15

Predpostavka 1: \(  \Omega \subseteq \mathbb{R} ^3 \) zvezdasto območje
Predpostavka 2: \(  \vec{F} \) odvedljivo vektorsko polje na \(  \Omega \)

\[ \nabla \times \vec{F} = 0 \implies \vec{F} \text{ potencialno}
\]
** Dokaz
*** <1>1
Case 1: \(  \omega_0 \in \Omega \)
Case 2: poljuben \( \omega \in \Omega: \ u(\omega) = \int\limits_{\left[ \omega_0, \omega \right]}^{} \vec{F} \mathrm{d} \vec{r} \)

Velja

\[ \nabla u = \vec{F}
\]
**** <2>1
Case 3: daljico \(  \left[ \omega_0, \omega \right] = \left[ (x_0, y_0, z_0), (x, y, z) \right] \) parametriziramo

\[ \vec{r}(t) = \begin{bmatrix} (1 - t)x_0 + tx \\ (1 -t) y_0 + ty  \\ (1 -t) z_0 + tz  \end{bmatrix} = \begin{bmatrix} r_1(t) \\ r_2(t) \\ r_3(t) \end{bmatrix}
\]

Velja

\[ \int\limits_{\left[ \omega_0, \omega \right]}^{} \vec{F} \mathrm{d} \vec{r} = \int\limits_0^1 \left\langle \vec{F}(\vec{r}(t)), \odv{r}(t) \right\rangle_{\mathbb{R} ^3} \mathrm{dt} = \int\limits_0^1 \left\langle \vec{F}\left( \vec{r}(t) \right), \omega - \omega_0 \right\rangle \mathrm{dt}
\]

Dokaz: definicija integrala vektorskega polja ter definicija parametrizacije Case 3
**** <2>2
Case 4: \(  \left( \nabla u \right) \left( \omega \right) = \left( u_x, u_y, u_z \right) \left( \omega \right) \)

\[ u_x \left( \omega \right) = \int\limits_0^1 \left( \left\langle \frac{\partial }{\partial x} \left[ \vec{F}\left( \vec{r}(t) \right) \right], \omega - \omega_0  \right\rangle + \left\langle \vec{F} \left( \vec{r}(t) \right), \frac{\partial }{\partial x} \left( \omega - \omega_0 \right)  \right\rangle \right)
\]

Dokaz: \(  u \) je odvedljiv, ker je integrand \(  \vec{F} \) po predpostavki 2 odvedljiv, ter verižno pravilo <2>1
**** <2>3
Case 5: \(  \vec{F} = \left( F_1, F_2, F_3 \right) \)

Velja

\[ \frac{\partial }{\partial x} \left[ \vec{F}(\vec{r}(t)) \right] = \left( \frac{\partial }{\partial x} \left( F_1 (\vec{r}) \right), \frac{\partial }{\partial x} F_2 \left( \vec{r}(t) \right), \frac{\partial }{\partial x} \left( F_3 \left( \vec{r}(t) \right) \right) \right)
\]

Dokaz: Odvod vektorja je odvod posamezne komponente vektorja
**** <2>4
Case 6: \(  F_i = F_i \left( a_i, b_i, c_i \right), \ i = 1, 2, 3 \) in \(  a_i, b_i, c_i = r_1, r_2, r_3 \)

Za \(  i = 1 \) velja

\[ \frac{\partial }{\partial x} \left( F_1 \left( \vec{r} \right) \right) = \left( \frac{\partial F_1}{\partial a}   \right)  \left( \vec{r}(t) \right) \cdot \frac{\partial }{\partial x} \left( r_1 (t) \right) + \underbrace{ \left( \frac{\partial F_1}{\partial b}   \right) \left( \vec{r}(t) \right) \cdot \frac{\partial }{\partial x} \left( r_2 (t) \right)}_{0} +  \underbrace{ \left( \frac{\partial F_1}{\partial c}  \right) \left( \vec{r}(t) \right) \cdot \frac{\partial }{\partial x} \left( r_3 (t) \right)}_{0}
\]

Dokaz: Verižno pravilo, \(  a = r_1, b=r_2, c = r_3 \) ter to, da po Case 3, \(  r_2 \ne r_2(x) \) in \(  r_3 \ne r_3(x) \)
**** <2>5

\[ \frac{\partial }{\partial x} \left[ \vec{F} \left( \vec{r}(t) \right) \right] = t \left( \frac{\partial F_1}{\partial a} \left( \vec{r} \right), \frac{\partial F_2}{\partial a} \left( \vec{r} \right), \frac{\partial F_3}{\partial a} \left( \vec{r} \right)    \right)
\]

Dokaz: Odvod iz <2>4 je po definiciji <2>1 Case 3 enak \( \frac{\partial }{\partial x} \left( r_1 \right) = t  \) in to za vsak \( i \) \( F_i \)
**** <2>6

\[  t \left( \frac{\partial F_1}{\partial a} \left( \vec{r} \right), \frac{\partial F_2}{\partial a} \left( \vec{r} \right), \frac{\partial F_3}{\partial a} \left( \vec{r} \right)    \right) = t \left( \frac{\partial F_1}{\partial a} \left( \vec{r} \right), \frac{\partial F_1}{\partial b} \left( \vec{r} \right), \frac{\partial F_1}{\partial c} \left( \vec{r} \right)\right)
\]

Dokaz: iz predpostavke \( \mathrm{rot} \vec{F} = 0 \) dobimo sledeče ekvivalence:

\begin{align*}
\begin{vmatrix}
 i& j & k \\
\partial_a & \partial_b & \partial_c \\
F_1 & F_2 & F_3
\end{vmatrix} = \left( \partial_b F_3 - \partial_c F_2, \partial_c F_1 - \partial_a F_3, \partial_a F_2 - \partial_b F_1 \right) &= (0, 0, 0) \\
\implies \partial_c F_1 &= \partial_a F_3 \\
\implies \partial_a F_2 &= \partial_b F_1
\end{align*}
**** <2>7
Case 7: uvedemo oznako \(  \tilde{\nabla} = \left( \partial_a, \partial_b, \partial_c  \right) \)

\[ \left( u_x  \right) \left( \omega \right) = \int\limits_0^1 \left( \left\langle t \tilde{\nabla} F_1 \left( \vec{r} \right), \omega - \omega_0 \right\rangle  + F_1 \left( \vec{r} \right) \right) \,\mathrm{d x}
\]

Dokaz: <2>1 in notacija uvedena v <2>7 Case 7, definiciji \(  \omega, \omega_0 \)
**** <2>8

\[ \int\limits_0^1 \left[ t \frac{\mathrm{d} \left( F_1 \circ \vec{r} \right)}{\mathrm{d} t} + \left( F_1 \circ \vec{r} \right)  \right] \,\mathrm{d t}
\]

Dokaz: \(  \omega - \omega_0 = \dot{r} \), in skupaj z verižnim pravilom
**** <2>9

\[ \int\limits_0^1 \frac{\mathrm{d}  \left( t \cdot \left( F_1 \circ \vec{r} \right) \right)}{\mathrm{d} t} \,\mathrm{d t}  = \left. \left( t \cdot F_1 (\vec{r}(t)) \right) \right|_{t = 0}^{t=1} = F_1 \left( \vec{r}(1) \right) = F_1 \left( \omega \right)
\]

Dokaz: osnovni izrek analize ter definicija \(  \vec{r} \) iz <2>1 Case 3
**** <2>10 QED

Dokazali smo, da velja \(  u_x = F_1 \) in enako velja za \(  u_y = F_2, \ u_z = F_3\)
*** <1>2 QED
Dokaz: <2>10
* Definicija 6.16

Naj bo \(  M \subset \mathbb{R} \) neka regularna ploskev in \(  f: M \to \mathbb{R} \)
zvezna.

Ploskovni integral skalarnega polja \(  f \) definiramo kot

\[ \int\limits_M f \,\mathrm{d S}  = \iint\limits_D f(\vec{r}(u, v))
\left| \vec{r}_u \times \vec{r}_v \right| \, \mathrm{d u} \, \mathrm{ dv}
\]

kjer je \(  \vec{r}: D \to M \) poljubna regularna parametrizacija za M.
* Definicija 6.19

Naj bo \(  M \) ploskev z orientacijo \(  \vec{N} \). Ploskovni integral zveznega vektorskega polja \(  \vec{F}: M \to \mathbb{R} ^3 \) je definiran s predpisom

\[ \iint\limits_M \vec{F} \,\mathrm{d } \vec{S} = \iint\limits_M^{} \left\langle \vec{F}, \vec{N} \right\rangle \,\mathrm{d S}
\]
* Izrek 6.20 (Gaussov izrek)

Predpostavke:
- \(  \Omega \) odprta omejena množica v \(  \mathbb{R} ^3 \) z odsekoma gladkim robom
- \(  \vec{F} \in C^1 \) vektorsko polje v okolici \(  \bar{\Omega} = \Omega \cup \partial \Omega \)
- \(  \partial \Omega \) je ploskev z orientacijo \(  \vec{N} \), ki kaže ven iz \(  \Omega \)

Velja:

\[ \iint\limits_{\partial \Omega}^{} \vec{F} \,\mathrm{d } \vec{S} = \iiint\limits_{\Omega}^{} \mathrm{div} \vec{F} \,\mathrm{d V}
\]
** Dokaz
Dokaz je narejen samo za primer, ko lahko območje \(  \Omega \) zapišemo med dvema grafoma \(  \Gamma_f \) in \(  \Gamma_g \)
*** <1>1
Case 1: \(  \vec{F} = \left( X, Y, Z \right) \)
Case 2: \(  \vec{N} = \left( N_1, N_2, N_3 \right) \)
Case 3: \(  \Omega = \left\{ \left( x, y, z \right) \in \mathbb{R} ^3;\ f(x, y) < z < g(x, y) \right\} \)

Integral, ki ga dokazujemo, lahko zapišemo kot

\[ \iint\limits_{\partial \Omega}^{} \left( XN_1 + YN_2 + ZN_3 \right) \,\mathrm{d S} = \iiint\limits_{\Omega}^{} \left( X_x + Y_y + Z_z \right) \,\mathrm{d V}
\]

Dovolj je pokazati, da velja integral za eno komponento.
*** <1>2

Velja

\[ \iint\limits_{\partial \Omega}^{} ZN_3 \,\mathrm{d S} = \iiint\limits_{\Omega}^{} Z_z \,\mathrm{d V}
\]
Dokaz:
**** <2>1
Case 4: \(  \Omega = \Gamma_f + \Gamma_g + \mathrm{plasc} \)

\[ \mathrm{LS} = \iint\limits_{\Gamma_f}^{} ZN_3 \,\mathrm{d S} + \iint\limits_{\Gamma_g}^{} ZN_3 \,\mathrm{d S} + \underbrace{\iint\limits_{\mathrm{plasc}}^{} ZN_3 \,\mathrm{d S }}_{0}
\]

Dokaz: Integral po množici je vsota integralov podmnožic, ki jo sestavljajo. Po predpostavki 3 \(  \vec{N} \) kaže navzen in za plašč to pomeni \(  \vec{N} = \left( \cdot, \cdot, 0 \right) \)
**** <2>2
Case 5: parametrizacija \(  \Gamma_f \) je \(  \vec{r} (x, y) = \left( x, y, f(x, y) \right); \ (x, y) \in D \subset \mathbb{R} ^2 \)
Case 6: parametrizacija \(  \Gamma_g \) je \(  \vec{R}(x, y) = \left( x, y, g(x, y) \right); (x, y) \in D \subset \mathbb{R} ^2 \)

\[ LS = \iint\limits_D^{} Z(x, y, f(x,y)) \cdot \left( - \frac{1}{\sqrt{1 + f_x ^2 + f_y ^2}} \right) \cdot \sqrt{1 + f_x ^2 + f_y ^2} \,\mathrm{d x dy} + \iint\limits_D^{} Z(x, y, g(x, y)) \cdot  \left(  \frac{1}{\sqrt{1 + g_x ^2 + g_y ^2}} \right) \cdot \sqrt{1 + g_x ^2 + g_y ^2} \,\mathrm{dxdy }
\]

Dokaz:
***** <3>1

\[  \vec{r}_x \times \vec{r}_y = (- f_x, -f_y, -1)
\]

in

\[ \vec{R}_x \times \vec{R}_y = \left( - g_x, -g_y, 1 \right)
\]


Dokaz: odvod in vektorski produkt parametrizacije Case 5 za funkciji \(  f \) in \(  g \) in predpostavka 3
***** <3>2

\[ \vec{N} = \frac{\vec{r}_x \times \vec{r}_y}{\left| {\vec{r}_x \times \vec{r}_y} \right|} \implies N_3 = - \frac{1}{\sqrt{1 + f_x ^2 + f_y ^2}}
\]

Dokaz:

Vektorski produkt in <3>1
***** <3>3 QED
Dokaz: <3>2 ter uvedba parametrizacije v integralu Definicija 4.8
**** <2>3

\[ \iint\limits_D^{} \left[ Z(x, y, g(x, y)) - Z(x, y, f(x, y)) \right] \,\mathrm{d xdy} = \iint\limits_D^{} \int\limits_{f(x,y)}^{g(x, y)} Z_z(x, y, t) \,\mathrm{d t} \,\mathrm{d x dy}
\]

Dokaz: <2>2 in osnovni izrek analize
**** <2>4 QED

\[   \iint\limits_D^{} \int\limits_{f(x,y)}^{g(x, y)} Z_z(x, y, t) \,\mathrm{d t} \,\mathrm{d x dy} = \iiint\limits_{\Omega}^{} Z_z \,\mathrm{d V}
\]
*** <1>3 QED

Dokaz <1>2 in s enako lahko naredimo z ostalimi komponentami.
* Izrek 6.24 (Greenova formula)

Predpostavke:
- \(  D \subset \mathbb{R} ^2 \) območje z odsekoma gladkim robom
- \(  \partial D \) je končna unija odsekoma gladkih krivulj
- \(  \partial D \) orientirana skaldno z normalo \(  (0, 0, 1) \) na D
- \( \vec{F}(X, Y) \in C^1 \) vektorsko polje na okolici \(  \bar{D} \)

Velja

\[ \oint\limits_{\partial D}^{} X \,\mathrm{d x} + Y \, \mathrm{dy} = \iint\limits_D^{} \left( Y_x - X_y \right) \,\mathrm{d xdy}
\]
** Dokaz
Dokaz je podoben dvodimenzionalnemu Gaussovemu izreku
*** <1>1
Case 1: \(  \vec{G} = (U, V) \)

\[ \oint\limits_{\partial D}^{} \left\langle \vec{G}, \vec{N} \right\rangle \,\mathrm{d s} = \iint\limits_D^{} \mathrm{div} \vec{G} \,\mathrm{d S}
\]
*** <1>2
Case 2: \(  \vec{T} \) je tangenta krivulje

Integral <1>1 je zelo podoben temu, kar želimo dokazati, če \(  \vec{N} \) zamenjamo s \(  \vec{T} \)

Za \(  \vec{H} = (-V, U) \) velja

\[ \left\langle \vec{G}, \vec{N} \right\rangle = \left\langle \vec{H}, \vec{T} \right\rangle
\]
**** <2>1
Case 3: \(  \underline{R} = \begin{bmatrix}
0& -1 \\
1 & 0
\end{bmatrix} \)

\[ \vec{T} = \underline{R} \vec{N}
\]

Dokaz: \(  \underline{R} \in \mathbb{R} ^2 \) rotira \(  \vec{N} \) za kot \(  \frac{\pi}{2} \), kar pa je ravno vektor \(  \vec{T} \).
**** <2>2

\[ \vec{N} = R^{-1} \vec{T}
\]

Dokaz:

Množenje z \(  \underline{R}^{-1} \)

**** <2>3

\[ \left\langle \vec{G}, \vec{N} \right\rangle = \left\langle \vec{G}, \underline{R}^{-1} \vec{T} \right\rangle
\]

Dokaz:

Upoštevamo <2>2

**** <2>4

\[ \left\langle \vec{G}, \underline{R}^{-1} \vec{T} \right\rangle = \left\langle \underline{R} \vec{G}, \underline{T} \right\rangle
\]

Dokaz:

***** <3>1

Matrika \(  \underline{R} \) je ortogonalna

Dokaz: Za ortogonalno matriko velja

\[ \underline{R}^T = \underline{R}^{-1} \iff \ \left( \underline{R}^{-1} \right)^T = \underline{R} \iff \ \underline{R}^T \underline{R} = \underline{R} \underline{R}^T = I
\]

***** <3>2

\begin{align*}
 \left. \underline{R} \cdot \right/ \quad \left\langle \vec{G}, \underline{R}^{-1} \vec{T} \right\rangle &= \left\langle \underline{R} \vec{G}, \underline{R} \cdot \underline{R}^{-1} \vec{T} \right\rangle \\
&= \left\langle \underline{R} \vec{G}, \vec{T} \right\rangle
\end{align*}

Dokaz: Matrika je ortogonalna
***** <3>3 QED
**** <2>5 QED

\[ \underline{R} \vec{G} = H = (-V, U)
\]
*** <1>3

\[ \oint\limits_{\partial D}^{} \left\langle \vec{H}, \vec{T} \right\rangle \,\mathrm{d s} = \oint\limits_{\partial D}^{} -V \mathrm{dx} + U \,\mathrm{d y}
\]

Dokaz:<1>2  ter <1>1
*** <1>4

\[ \iint\limits_D^{} \mathrm{div} \vec{G} \,\mathrm{d S} = \iint\limits_D^{} U_x + V_y  \,\mathrm{d xdy}
\]

Dokaz: definicija divergence
*** <1>5

Z izborom \(  (U, V) = (Y, -X) \) velja

\[ \oint\limits_{\partial D}^{} -V \,\mathrm{d x} + U \, \mathrm{dy} = \iint\limits_D^{} U_x + V_y \,\mathrm{d xdy}
\]


Dokaz: analiza 1
*** <1>6 QED
* Izrek 6.25 (Stokesov izrek)

Predpostavke:

- \(  M \) omejena gladka orientirana ploskev v \(  \mathbb{R} ^3 \)
- \(  \vec{F} = (X, Y, Z): M \to \mathbb{R} \) vektorsko polje
- \(  \vec{F} \) definirano v okolici \(  M \)

Velja

\[ \int\limits_{\partial M}^{} \vec{F} \,\mathrm{d } \vec{r} = \iint\limits_M^{} \vec{F} \,\mathrm{d S}
\]
** (Skica) dokaza
*** <1>1
Case 1: \(  D \subset \mathbb{R} ^2 \)
Case 2: \(  f: D \to \mathbb{R} \)
Case 3: \(  M = \Gamma_f = \left\{ \vec{r}(x, y) = \left( x, y, f(x, y) \right); (x,y) \in D \right\} \)

\[ \int\limits_{\partial M}^{} \vec{F} \,\mathrm{d } \vec{r} = \int\limits_{\partial M}^{} X \,\mathrm{d x} + Y \, \mathrm{dy} + Z \left[ f_x \, \mathrm{dx} + f_y \, \mathrm{dy } \right]
\]

Dokaz:
Definicija 6.4, kjer je \(  d \vec{r} = \odv{r}(t) dt = \left( \mathrm{dx}, \mathrm{dy}, f_x \, \mathrm{dx} + f_y \mathrm{dy} \right) \)
*** <1>2
Case 4: \(  \vec{F} = (X, Y, Z) = \left( X (u, v, w), Y(u, v, w), Z(u, v, w) \right) \)

\begin{align*}
\int\limits_{\partial M}^{} \left[ X + Z f_x \right] \,\mathrm{d x} + \left[ Y + Zf_y \right] \, \mathrm{dy } = \iint\limits_D^{} &\left[ Y_u \left( \vec{r} \right) \frac{\partial x}{\partial x} + \underbrace{Y_v \left( \vec{r} \right) \cdot \frac{\partial y}{\partial x}}_{0} + Y_w \left( \vec{r} \right) \cdot \frac{\partial f(x, y)}{\partial x} + f_y \cdot \left( Z_u \left( \vec{r} \right) \cdot \frac{\partial x}{\partial x} + \underbrace{Z_v \left( \vec{r} \right) \cdot \frac{\partial y}{\partial x}}_{0} + Z_w \left( \vec{r} \right) \cdot \frac{\partial f(x, y)}{\partial x} \right) + Z \cdot f_{yx}    \right. \\
 &-  \left. \left( \underbrace{X_u \left( \vec{r} \right) \cdot \frac{\partial x}{\partial y}}_{0} + X_v \left( \vec{r} \right) \cdot \frac{\partial y}{\partial y} + X_w \left( \vec{r} \right) \cdot \frac{\partial f(x, y)}{\partial y} + f_x \left[ \underbrace{Z_v \left( \vec{r} \right) \cdot \frac{\partial x}{\partial y} }_0 + Z_v \left( \vec{r} \right) \cdot \frac{\partial y}{\partial y} + Z_w \left( \vec{r} \right) \cdot \frac{\partial f(x, y)}{\partial y} \right] + Z \cdot f_{yx} \right) \right] \,\mathrm{dx dy} \\
&= \iint\limits_D^{} \left[ -f_x \left( Z_v - Y_w \right) - f_y \left( X_w - Z_u \right) + \left( Y_u - X_v \right) \right] \,\mathrm{d xdy}
\end{align*}

Dokaz: Uporaba Greenove formule
*** <1>3

\[ \iint\limits_D^{} \left[ -f_x \left( Z_v - Y_w \right) - f_y \left( X_w - Z_u \right) + \left( Y_u - X_v \right) \right] \,\mathrm{d xdy} = \iint\limits_D^{} \left\langle  \mathrm{rot} \vec{F} \left( \vec{r} \right), \vec{N} \right\rangle \sqrt{1 + f_x ^2 + f_y ^2} \, \mathrm{dy dx}
\]

Dokaz: Definicija skalarnega produkta in rotorja vektorske funkcije \(  \vec{F} \)
*** <1>4 QED

\[ \iint\limits_D^{} \left\langle \mathrm{rot} \vec{F} \left( \vec{r} \right), \vec{N} \right\rangle \sqrt{1 + f_x ^2 + f_y ^2} \,\mathrm{dS } = \iint\limits_M^{} \mathrm{rot} \vec{F} \,\mathrm{d } \vec{S}
\]
* Posledica

Rotor je neodvisen od izbire ONB.
** Dokaz:
*** <1>1
Case 1: \(  \vec{r}_0 \in \mathbb{R} ^3 \)
Case 2: \(  \vec{F} \in C^1 \) vektorsko polje definirano v okolici točke \(  \vec{r}_0 \)
Case 3: \(  \vec{n} \in \mathbb{R} ^3 \)
Case 4: \(  \Pi_{\vec{n}} \subset R ^3 \) je ravnina skozi točko \(  \vec{r}_0 \) z normalo \(  \vec{n} \)
Case 5: \(  K_{\vec{n}} ^2 \left( \vec{r}_0, \epsilon \right) \) je krog v \(  \Pi_{\vec{n}} \) s središčem v \(  \vec{r}_0 \) in radijem \(  \epsilon \)
Case 6: \(  S_{\vec{n}} ^1 \) krožinica s središčem v \(  \vec{r}_0 \) in radijem \(  \epsilon \)

\[ \mathrm{rot} \vec{F} \left( \vec{r} \right) \cdot \vec{n} = \lim_{\epsilon \to 0} \overline{\left( \mathrm{rot} \vec{F} \cdot \vec{n} \right)}_{K_{\vec{n}}^2 \left( \vec{r}, \epsilon \right)}
\]

kjer je \(  \cdot \) skalarni produkt in \( \overline{\left( \cdot \right)}_{K_{\vec{n}} ^2 \left( \vec{r}, \epsilon \right)} \) povprečje na krogu Case 5
*** <1>2

\[ \lim_{\epsilon \to 0} \overline{\mathrm{rot} \vec{F} \cdot \vec{n}}_{K_{\vec{n}}^2 \left( \vec{r}, \epsilon \right)} = \lim_{\epsilon \to 0} \frac{1}{\pi \epsilon ^2} \iint\limits_{K_{\vec{n}} ^2 \left( \vec{r}, \epsilon \right)}^{} \mathrm{rot }\vec{F} \cdot \vec{n} \,\mathrm{d S}
\]

Dokaz: Definicija povprečja zvezne funkcije na krogu Case 5
*** <1>3

\[ \lim_{\epsilon \to \epsilon} \frac{1}{\pi \epsilon ^2} \iint\limits_{K_{\vec{n}} ^2 \left( \vec{r}, \epsilon \right)}^{} \mathrm{rot} \vec{F} \cdot \vec{n} \,\mathrm{d S} = \lim_{\epsilon \to 0} \frac{1}{\pi \epsilon ^2} \oint\limits_{S_{\vec{n}}^1 \left( \vec{r}, \epsilon \right)} \vec{F} \,\mathrm{d } \vec{r}
\]

Dokaz: Stokesov izrek

\[ \lim_{\epsilon \to 0} \frac{3}{4 \pi \epsilon ^3} \iint\limits_{S ^2 \left( \vec{r}, \epsilon \right)}^{} \vec{F}  \,\mathrm{d } \vec{S}
\]
*** <1>4 QED
Dokaz: <1>3
* Izrek 6.27 (Greenovi identiteti)
Predpostavke:
- \(  \Omega \subset \mathbb{R} ^3 \) odprta množica z odsekoma gladkim robom
- \(  u, v \in C^2 \) skalarni polji na neki odprti okolici zaprtja \(  \bar{\Omega} \)
- \(  \vec{n} \) je enotska zunanja normala na \(  \partial \Omega \)


Velja prve Greenova identiteta

\[ \varoiint\limits_{\partial \Omega}^{} u \frac{\partial v}{\partial \vec{n}}   \,\mathrm{d S} = \iiint\limits_{\Omega}^{} \left( u \Delta v + \left\langle \nabla u, \nabla v \right\rangle \right) \,\mathrm{d V}
\]

in druga Greenova identiteta

\[ \varoiint \limits_{\partial \Omega}^{} \left( u \frac{\partial v}{\partial \vec{n}} - v \frac{\partial u}{\partial \vec{n}}   \right) \,\mathrm{d S} = \iiint\limits_{\Omega}^{} \left( u \Delta v - v \Delta u \right) \,\mathrm{d V}
\]
** Dokaz:
*** <1>1 Dokaz druge Greenove identitete

\[ \varoiint \limits_{\partial \Omega}^{} u \frac{\partial v}{\partial \vec{n}}  \,\mathrm{d S} - \varoiint \limits_{\partial \Omega}^{} v \frac{\partial u}{\partial \vec{n}}  \,\mathrm{d S} = \varoiint \limits_{\partial \Omega}^{} \left( u \frac{\partial v}{\partial \vec{n}} - v \frac{\partial u}{\partial \vec{n}}   \right) \,\mathrm{d S}
\]

Dokaz: Razlika dveh integralov je enaka integralu razlik integrandov
*** <1>2

\[   \varoiint \limits_{\partial \Omega}^{} \left( u \frac{\partial v}{\partial \vec{n}} - v \frac{\partial u}{\partial \vec{n}}   \right) \,\mathrm{d S} = \iiint\limits_{\Omega}^{} \left( u \Delta v - v - \Delta u \right) \,\mathrm{d V}
\]

Dokaz: Upoštevamo 1. Greenovo identiteto.
*** <1>3 Dokaz prve Greenove identitete
Case 1: \(  \vec{F} = u \Delta v = u \cdot \left( v_x, v_y, v_z \right) \)

\[ \mathrm{div} \vec{F} = \left\langle \nabla u, \nabla v \right\rangle + u  \Delta v
\]

Dokaz: definicija divergence in verižno pravilo, ter \(  \Delta = \nabla ^2 \)
*** <1>4

\[ \iiint\limits_{\Omega}^{} \left( u \Delta v + \left\langle \nabla u, \nabla v \right\rangle \right) \,\mathrm{d V} = \iint\limits_{\partial \Omega}^{} \vec{F} \,\mathrm{d } \vec{S}
\]

Dokaz: Gaussova formula
*** <1>5

\[ \iint\limits_{\partial \Omega}^{} \vec{F} \,\mathrm{d } \vec{S} = \iint\limits_{\partial \Omega}^{} \left\langle \vec{F}, \vec{n} \right\rangle \,\mathrm{d S}
\]

Dokaz: Definicija integrala vektorskega polja
*** <1>6

\[ \iint\limits_{\partial \Omega}^{} \left\langle u \nabla v, \vec{n} \right\rangle \,\mathrm{d S} = \iint\limits_{\partial \Omega}^{} u \left\langle \nabla v, \vec{n} \right\rangle \,\mathrm{d S}
\]

Dokaz: \(  u \) je skalarna funkcija in se jo lahko izpostavi
*** <1>7

\[ \iint\limits_{\partial \Omega}^{} u \left\langle \nabla v, \vec{n} \right\rangle \,\mathrm{d S} = \iint\limits_{\partial \Omega}^{} u \frac{\partial v}{\partial \vec{n}}  \,\mathrm{d S}
\]

Dokaz:
**** <2>1
Vir:[[https://tutorial.math.lamar.edu/classes/calciii/directionalderiv.aspx][Directional derivati (slo. smerni odvod)]]
Case 1: točka \(  \vec{v} = (x_0, y_0, z_0) \in \mathbb{R} ^3 \)
Case 2: \(  u(x, y, z): \mathbb{R} ^2 \to \mathbb{R} \) zvezna realna funkcija, definirana v okolici točke \(  \vec{v} \)
Case 3: \(  \vec{a} = (a, b, c) \in \mathbb{R} ^3 \) enotski vektor, \(  \left| a \right|  = 1 \)

Definiramo /smerni odvod/ funkcije \(  u \) v točki \(  \vec{v} \) v smeri vektorja \(  \vec{a} \):

\[ \frac{\partial u}{\partial \vec{a}} \left( \vec{v} \right) = \lim_{h \to 0} \frac{u \left( \vec{v} + h \vec{a} \right) - u(\vec{v})}{h} = \lim_{h \to 0} \frac{u(x + ha, y + bh, z + ch)}{h}
\]
**** <2>2

Smerni odvod definiramo tudi kot

\[ \frac{\partial u}{\partial \vec{a}} \left( \vec{v} \right) = \left\langle \nabla u, \vec{a} \right\rangle
\]
Dokaz:
***** <3>1
Case 4: \(  x_0, y_0, z_0, a, b, c\) so konstante
Case 5: funkcija ene spremenljivke \(  g(t) = u(x_0 + ta, y_0 + tb, z_0 + tc) = u(x, y, z) \)

Velja

\[ g'(t) = \lim_{h \to 0} \frac{g(t + h) - g(t)}{h}
\]


***** <3>2

Za \(  t = 0 \) velja

\[ g'(0) = \lim_{h \to 0} \frac{g(h) - g(0)}{h} = \lim_{h \to 0} \frac{u(x_0 + ah, y_0 + bh, z_0 + ch) - u(x_0, y_0, z_0)}{h} = \frac{\partial u}{\partial \vec{a}} (x_0, y_0, z_0)
\]

Dokaz: definicija odvoda ene spremenljivke <3>1, definicija Case 5, ter <2>1

***** <3>3

Velja

\[ g'(t) = \frac{\mathrm{d} }{\mathrm{d} t} g = \frac{\partial u}{\partial x} \cdot \frac{\partial x}{\partial t} + \frac{\partial u}{\partial y} \cdot \frac{\partial y}{\partial t} + \frac{\partial u}{\partial z} \cdot \frac{\partial z}{\partial t} = u_x \cdot a + u_y \cdot b + u_z \cdot c
\]

Dokaz: Case 5 in verižno pravilo
***** <3>4

Za \(  t = 0 \) velja

\[ g'(0) = u_x (x_0, y_0, z_0) \cdot a + u_y (x_0, y_0, z_0) \cdot b + u_z (x_0, y_0, z_0) \cdot c
\]

Dokaz: \(  t = 0 \) za <3>3
***** <3>5 QED

\[ \frac{\partial u}{\partial \vec{a}} \left( \vec{v} \right) = \left\langle \nabla u, \vec{a} \right\rangle
\]

Dokaz: Izenačimo <3>4 in <3>2
**** <2>3 QED

Dokaz: <2>2
*** <1>8 QED

Dokaz: <1>6 in <1>7
* Cauchyjev problem (Initial value problem)

Eksplicitna diferencialna enačba prvega reda oblike \(  y' = f(x,y) \) s podanimi začetnimi, robnimi pogoji \(  y_0 = y(x_0) \), kjer so \(  f, x_0, y_0 \) podani.
* Eulerjeva metoda

Imamo Cauchyjev problem.
** <1>1
Case 1: \(  x \in \mathbb{R} \)
Case 2: \(  x > x_0 \)

Interval \(  [x_0, x] \) razdelimo na \(  n \) delov:

\[ x_0 < x_1 < x_2 < \ldots < x_n = x
\]
** <1>2

\[ x_j = x_0 + \frac{x - x_0}{n} j = x_0 + h j
\]

Dokaz: <1>1
** <1>3

Imamo nov Cauchyjev problem

\begin{align*}
  y' &= f(x, y) \\
y_1 &= y(x_1)
\end{align*}

Dokaz:

Za majhne \(  h \) (velike \(  n \)) je \(  y(x_1) \) blizu vrednosti tangente \(  y'(x_1) \).
** <1>4

Po \(  n \) korakih

\[ y(x_n) = y(x)
\]
** <1>5
Case 3: \(  Y = y_j \)
Case 4: \(  X = x_j \)

Tangenta skozi \(  (x_{j - 1}, y_{j -1}) \) z naklonom \(  f(x_{j -1}, y_{j -1}) \) je

\[ Y - y_{j -1} = f(x_{j -1}, y_{j -1}) \left( X -x_{j-1} \right)
\]

Dokaz: definicija tangente
** <1>6

Na koncu dobimo

\begin{align*}
  x_j &= x_{j - 1} + h \\
y_j &= y_{j - 1} + f(x_{j - 1}, y_{j - 1})h
\end{align*}
* Enačba z ločljivimi spremenljivkami

Enačbe oblike

\[ y' = P(x) \cdot Q(y)
\]
